// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * # JS_FetchCardanoWalletBalance
 * 
 * ## Description
 * 
 * The `JS_FetchCardanoWalletBalance` action is a JavaScript action used to fetch the balance of a Cardano wallet. This action does not require any parameters.
 * 
 * ## Usage
 * 
 * To use the `JS_FetchCardanoWalletBalance` action, you simply need to call it in your JavaScript code. Since it does not require any parameters, you do not need to pass any arguments to it.
 * 
 * Here is an example of how to use it:
 * 
 * ```javascript
 * JS_FetchCardanoWalletBalance();
 * ```
 * 
 * This will return the balance of the Cardano wallet.
 * 
 * ## Returns
 * 
 * This action returns a number representing the balance of the Cardano wallet.
 * 
 * ## Error Handling
 * 
 * In the event of an error, such as a failure to connect to the Cardano network or a problem with the wallet, the `JS_FetchCardanoWalletBalance` action will throw an error. This error should be caught and handled appropriately in your code.
 * 
 * ## Notes
 * 
 * Please note that this action requires a connection to the Cardano network in order to function. Ensure that your application has the necessary permissions and connectivity before using this action.
 * @returns {Promise.<void>}
 */
export async function JS_FetchCardanoWalletBalance() {
	// BEGIN USER CODE
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
