// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * # JS_FetchCardanoWalletUtxos JavaScript Action Documentation
 * 
 * ## Action Name
 * JS_FetchCardanoWalletUtxos
 * 
 * ## Description
 * This JavaScript action is designed to fetch Unspent Transaction Outputs (UTXOs) of a Cardano wallet. UTXOs represent a certain amount of cryptocurrency that was sent to a wallet and has not been spent yet. 
 * 
 * ## Parameters
 * This action does not require any parameters.
 * 
 * ## Returns
 * This action returns a list of UTXOs associated with a Cardano wallet. Each UTXO in the list includes the following information:
 * 
 * - Transaction ID: The unique identifier of the transaction.
 * - Output Index: The index of the output in the transaction.
 * - Address: The address of the wallet that the UTXO belongs to.
 * - Amount: The amount of cryptocurrency in the UTXO.
 * - Asset Information: Information about the asset that the UTXO represents.
 * 
 * ## Usage
 * This action can be used to fetch the UTXOs of a Cardano wallet. This can be useful for determining the balance of a wallet, as the balance is the sum of the amounts of all UTXOs that belong to the wallet.
 * 
 * ## Example
 * Here is an example of how to use this action:
 * 
 * ```javascript
 * const utxos = JS_FetchCardanoWalletUtxos();
 * console.log(utxos);
 * ```
 * 
 * This will fetch the UTXOs of a Cardano wallet and log them to the console.
 * 
 * ## Error Handling
 * This action will throw an error if it fails to fetch the UTXOs. The error message will provide more details about the cause of the failure.
 * @returns {Promise.<void>}
 */
export async function JS_FetchCardanoWalletUtxos() {
	// BEGIN USER CODE
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
