// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * ## JS_GetCardanoWalletRewardAddresses
 * 
 * ### Description
 * 
 * The `JS_GetCardanoWalletRewardAddresses` action is a JavaScript function in Mendix that retrieves the reward addresses associated with a Cardano wallet. This action is useful when you need to access the reward addresses for staking or other purposes.
 * 
 * ### Parameters
 * 
 * This action does not require any parameters.
 * 
 * ### Usage
 * 
 * To use this action, you simply need to call it in your JavaScript code. Since it does not require any parameters, you do not need to provide any arguments. Here is an example of how you can use this action:
 * 
 * ```javascript
 * const rewardAddresses = JS_GetCardanoWalletRewardAddresses();
 * ```
 * 
 * In this example, the `JS_GetCardanoWalletRewardAddresses` action is called and its return value is stored in the `rewardAddresses` variable. You can then use this variable in your code as needed.
 * 
 * ### Return Value
 * 
 * This action returns an array of strings. Each string in the array is a reward address associated with the Cardano wallet. If the wallet does not have any reward addresses, the action returns an empty array.
 * 
 * ### Error Handling
 * 
 * If an error occurs while retrieving the reward addresses, the action throws an exception. You should use a try-catch block to handle possible exceptions when calling this action.
 * 
 * ```javascript
 * try {
 *     const rewardAddresses = JS_GetCardanoWalletRewardAddresses();
 *     // Use rewardAddresses...
 * } catch (error) {
 *     console.error("Failed to get reward addresses: ", error);
 * }
 * ```
 * 
 * In this example, if the `JS_GetCardanoWalletRewardAddresses` action throws an exception, the catch block catches it and logs an error message to the console.
 * @returns {Promise.<void>}
 */
export async function JS_GetCardanoWalletRewardAddresses() {
	// BEGIN USER CODE
	// This action retrieves the stake (reward) address from the Cardano wallet

    try {
        // Ensure the Cardano wallet is enabled
        const wallet = await window.cardano.enable();

        // Get the reward addresses associated with the wallet
        const rewardAddresses = await wallet.getRewardAddresses();

        // Typically, you want the first reward address
        const stakeAddress = rewardAddresses[0];

        // Return the stake address as the output of this action
        return stakeAddress;

    } catch (error) {
        // Handle any errors that occur during the process
        console.error("Error retrieving the Cardano wallet stake address:", error);
        return null;
    }
	// END USER CODE
}
