// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * ## JS_GetCardanoWalletChangeAddress
 * 
 * ### Description
 * 
 * The `JS_GetCardanoWalletChangeAddress` is a JavaScript action used to retrieve the change address of a Cardano wallet. This action is primarily used in cryptocurrency applications where tracking the change address of a wallet is necessary. 
 * 
 * ### Parameters
 * 
 * This action does not require any parameters.
 * 
 * ### Usage
 * 
 * To use this action, simply call it in your JavaScript code as follows:
 * 
 * ```javascript
 * JS_GetCardanoWalletChangeAddress();
 * ```
 * 
 * This action will return the change address of the Cardano wallet as a string.
 * 
 * ### Errors
 * 
 * If there are any errors (like if the wallet is not found), this action will throw an error with a relevant message.
 * 
 * ### Note
 * 
 * This action requires a connection to a Cardano node and will not work if the application is offline or if the node is not responding. Please ensure that your application is properly connected to a Cardano node before using this action.
 * @returns {Promise.<void>}
 */
export async function JS_GetCardanoWalletChangeAddress() {
	// BEGIN USER CODE
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
