// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * # JS_GetUnusedCardanoWalletAddresses JavaScript Action
 * 
 * ## Description
 * 
 * The `JS_GetUnusedCardanoWalletAddresses` is a JavaScript action designed to retrieve unused addresses from a Cardano wallet. This action can be useful in managing and optimizing the use of addresses in a Cardano wallet.
 * 
 * ## Parameters
 * 
 * This JavaScript action does not require any parameters.
 * 
 * ## Return Type
 * 
 * This action returns an array of strings. Each string in the array represents an unused address in the Cardano wallet.
 * 
 * ## Usage
 * 
 * To use this action, simply call it in your JavaScript code as follows:
 * 
 * ```javascript
 * const unusedAddresses = JS_GetUnusedCardanoWalletAddresses();
 * ```
 * 
 * The `unusedAddresses` variable will then hold an array of unused addresses.
 * 
 * ## Error Handling
 * 
 * If the action encounters an error while trying to retrieve the unused addresses, it will throw an exception. Make sure to use try-catch blocks to handle these exceptions and prevent potential crashes.
 * 
 * ```javascript
 * try {
 *     const unusedAddresses = JS_GetUnusedCardanoWalletAddresses();
 * } catch (error) {
 *     console.error("An error occurred while retrieving unused addresses: ", error);
 * }
 * ```
 * 
 * ## Note
 * 
 * This action requires a connection to a Cardano wallet. Make sure that the wallet is properly set up and connected before calling this action.
 * @returns {Promise.<void>}
 */
export async function JS_GetUnusedCardanoWalletAddresses() {
	// BEGIN USER CODE
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
