// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * ## JS_GetUsedCardanoWalletAddresses
 * 
 * ### Description
 * The `JS_GetUsedCardanoWalletAddresses` is a JavaScript action that retrieves all used addresses from a Cardano wallet. This action does not require any parameters.
 * 
 * ### Usage
 * This action can be used when you need to get a list of all used addresses from a Cardano wallet. It can be beneficial in tracking transactions, managing wallet balances, and for security purposes.
 * 
 * ### Parameters
 * This action does not require any parameters.
 * 
 * ### Return Type
 * This action returns an array of strings. Each string in the array represents a used address from the Cardano wallet.
 * 
 * ### Errors
 * This action throws an error if it fails to retrieve the used addresses from the Cardano wallet.
 * 
 * ### Example
 * Here is an example of how to use the `JS_GetUsedCardanoWalletAddresses` action:
 * 
 * ```javascript
 * const usedAddresses = JS_GetUsedCardanoWalletAddresses();
 * console.log(usedAddresses);
 * ```
 * 
 * In this example, the `JS_GetUsedCardanoWalletAddresses` action retrieves all used addresses from the Cardano wallet and logs them to the console.
 * 
 * ### Note
 * Ensure that the Cardano wallet is properly configured and accessible from the environment where this action is executed.
 * @returns {Promise.<void>}
 */
export async function JS_GetUsedCardanoWalletAddresses() {
	// BEGIN USER CODE
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
