// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * # JS_ListAvailableWallets JavaScript Action Documentation
 * 
 * ## Description
 * 
 * The `JS_ListAvailableWallets` is a JavaScript action that is designed to list all available wallets. This action does not require any parameters.
 * 
 * ## Parameters
 * 
 * This action does not have any parameters.
 * 
 * ## Usage
 * 
 * To use the `JS_ListAvailableWallets` action, simply call it in your JavaScript code.
 * 
 * ```javascript
 * JS_ListAvailableWallets();
 * ```
 * 
 * ## Returns
 * 
 * This action returns an array of available wallets. Each wallet in the array is represented as an object with properties such as `walletId`, `walletName`, `walletBalance`, etc. The exact structure of the wallet object will depend on your specific implementation.
 * 
 * ## Errors
 * 
 * This action does not throw any errors. However, if there are no available wallets, it will return an empty array.
 * 
 * ## Example
 * 
 * Here is an example of how you might use the `JS_ListAvailableWallets` action:
 * 
 * ```javascript
 * let wallets = JS_ListAvailableWallets();
 * for (let i = 0; i < wallets.length; i++) {
 *     console.log(wallets[i].walletName);
 * }
 * ```
 * 
 * In this example, the `JS_ListAvailableWallets` action is called and the returned array of wallets is stored in the `wallets` variable. Then, a for loop is used to iterate over each wallet in the array and log the name of each wallet to the console.
 * 
 * ## Notes
 * 
 * This action does not modify any data. It only retrieves and returns information about the available wallets.
 * @returns {Promise.<MxObject[]>}
 */
export async function JS_ListAvailableWallets() {
	// BEGIN USER CODE
	if (typeof window.cardano !== 'undefined') {
        const wallets = Object.keys(window.cardano).filter(wallet => window.cardano[wallet].enable);
        const walletDetails = wallets.map(wallet => ({
            name: window.cardano[wallet].name,
            icon: window.cardano[wallet].icon,
            identifier: wallet
        }));

        const mxObjects = [];
        const walletEntity = "CardanoWallet.WalletAPI";

        for (const wallet of walletDetails) {
            const mxObject = await new Promise((resolve, reject) => {
                mx.data.create({
                    entity: walletEntity,
                    callback: resolve,
                    error: reject
                });
            });
            mxObject.set("Name", wallet.name);
            mxObject.set("Icon", wallet.icon);
            mxObject.set("_id", wallet.identifier);
            mxObjects.push(mxObject);
        }

        return mxObjects;
    } else {
        throw new Error('No Cardano wallets found');
    }
	// END USER CODE
}
