// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * # JS_SubmitCardanoWalletTransaction JavaScript Action Documentation
 * 
 * ## Description
 * 
 * The `JS_SubmitCardanoWalletTransaction` JavaScript action is designed to submit a transaction from a Cardano wallet. The action does not require any parameters.
 * 
 * ## Parameters
 * 
 * This action does not require any parameters.
 * 
 * ## Usage
 * 
 * To use the `JS_SubmitCardanoWalletTransaction` action, simply call the function in your JavaScript code. Since it doesn't require any parameters, you don't need to pass any arguments.
 * 
 * Here is a basic usage example:
 * 
 * ```javascript
 * JS_SubmitCardanoWalletTransaction();
 * ```
 * 
 * ## Return Value
 * 
 * The `JS_SubmitCardanoWalletTransaction` action returns a promise. If the transaction is successful, the promise will resolve with a transaction receipt. If the transaction fails, the promise will reject with an error message.
 * 
 * ## Error Handling
 * 
 * If an error occurs while attempting to submit the transaction, the `JS_SubmitCardanoWalletTransaction` action will throw an error. You should use a try/catch block to handle these errors in your code.
 * 
 * Here is an example of how to handle errors:
 * 
 * ```javascript
 * try {
 *     const receipt = await JS_SubmitCardanoWalletTransaction();
 *     console.log(receipt);
 * } catch (error) {
 *     console.error(`Failed to submit transaction: ${error.message}`);
 * }
 * ```
 * 
 * ## Remarks
 * 
 * The `JS_SubmitCardanoWalletTransaction` action requires a connection to a Cardano node. Make sure your application is properly configured to connect to a Cardano node before using this action.
 * @param {string} walletIdentifier
 * @param {string} signedCBOR
 * @returns {Promise.<string>}
 */
export async function JS_SubmitCardanoWalletTransaction(walletIdentifier, signedCBOR) {
	// BEGIN USER CODE
    try {
		const cardanoWallet = await window.cardano[walletIdentifier].enable();

        // Sign the transaction with the wallet
        const txHash = await cardanoWallet.submitTx(signedCBOR);

        return txHash;
    } catch (error) {
        console.error("Error submitting the transaction:", error);
        return null;
    }	
	// END USER CODE
}
