// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * # JS_SignCardanoWalletData JavaScript Action
 * 
 * ## Description
 * 
 * The `JS_SignCardanoWalletData` action is a JavaScript function that is designed to sign data for a Cardano wallet. However, this action does not take any parameters.
 * 
 * ## Usage
 * 
 * Due to the lack of parameters, the usage of this action is straightforward. You simply need to call the function in your JavaScript code. Here is an example:
 * 
 * ```javascript
 * JS_SignCardanoWalletData();
 * ```
 * 
 * ## Function Details
 * 
 * ### Name
 * 
 * `JS_SignCardanoWalletData`
 * 
 * ### Parameters
 * 
 * This function does not take any parameters.
 * 
 * ### Returns
 * 
 * This function's return value is not defined in this documentation. The return value depends on the specific implementation of the function.
 * 
 * ## Notes
 * 
 * Since this function does not take any parameters, it is likely that it uses some form of global state or pre-configured values. Make sure you understand how this function is implemented before using it.
 * 
 * ## Example
 * 
 * Here is an example of how you might use this function:
 * 
 * ```javascript
 * // Sign the Cardano wallet data
 * JS_SignCardanoWalletData();
 * 
 * // Continue with the rest of your code
 * ```
 * 
 * In this example, the `JS_SignCardanoWalletData` function is called without any arguments. The function then performs its task, which is assumed to be signing some Cardano wallet data. After the function call, the rest of the code can continue.
 * @param {MxObject} wallet
 * @param {string} payloadHex
 * @returns {Promise.<string>}
 */
export async function JS_SignCardanoWalletData(wallet, payloadHex) {
	// BEGIN USER CODE
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
