// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * ## JS_SignAndSubmitCardanoWalletTransaction
 * 
 * ### Description
 * The `JS_SignAndSubmitCardanoWalletTransaction` action is a JavaScript function designed to sign and submit transactions for Cardano wallets. 
 * 
 * ### Parameters
 * This action does not require any parameters.
 * 
 * ### Usage
 * To use the `JS_SignAndSubmitCardanoWalletTransaction` action, you simply need to call it in your JavaScript code. Since it doesn't require any parameters, you don't need to provide any arguments.
 * 
 * Here is an example of how to use it:
 * 
 * ```javascript
 * JS_SignAndSubmitCardanoWalletTransaction();
 * ```
 * 
 * ### Return Value
 * This action returns a Promise that resolves once the transaction has been signed and submitted. If the transaction is successful, the Promise will resolve with a transaction ID. If the transaction fails, the Promise will be rejected with an error message.
 * 
 * ### Error Handling
 * If an error occurs while signing or submitting the transaction, the Promise returned by this action will be rejected with an error message. You should always include error handling when using this action to ensure that your application can gracefully handle any issues that may arise.
 * 
 * Here is an example of how to handle errors:
 * 
 * ```javascript
 * JS_SignAndSubmitCardanoWalletTransaction()
 *     .then(transactionId => {
 *         console.log(`Transaction successful! ID: ${transactionId}`);
 *     })
 *     .catch(error => {
 *         console.error(`An error occurred: ${error}`);
 *     });
 * ```
 * 
 * In this example, if the transaction is successful, the transaction ID will be logged to the console. If an error occurs, the error message will be logged to the console.
 * 
 * ### Note
 * Please ensure that the wallet has enough balance for the transaction to be successful. Also, ensure that the transaction is valid and meets all the necessary conditions of the Cardano blockchain.
 * @param {string} walletIdentifier
 * @param {string} transactionData - CBOR-encoded transaction data
 * @returns {Promise.<string>}
 */
export async function JS_SignAndSubmitCardanoWalletTransaction(walletIdentifier, transactionData) {
	// BEGIN USER CODE
    try {
		const cardanoWallet = await window.cardano[walletIdentifier].enable();

        // Sign the transaction with the wallet
        const signedTransaction = await cardanoWallet.signTx(transactionData, false);
        const txHash = await cardanoWallet.submitTx(signedTransaction);

        return signedTransaction;
    } catch (error) {
        console.error("Error signing the transaction:", error);
        return null;
    }
	// END USER CODE
}
