// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * # JS_SignCardanoWalletTransaction
 * 
 * ## Description
 * 
 * The `JS_SignCardanoWalletTransaction` is a JavaScript action used to sign a transaction for a Cardano wallet. This action is crucial for ensuring the security and integrity of transactions made with the Cardano wallet.
 * 
 * ## Parameters
 * 
 * This action does not require any parameters.
 * 
 * ## Usage
 * 
 * To use the `JS_SignCardanoWalletTransaction` action, simply call it in your JavaScript code. Since it does not require any parameters, you do not need to pass any arguments to it. 
 * 
 * Here is a basic example of how to use the `JS_SignCardanoWalletTransaction` action:
 * 
 * ```javascript
 * JS_SignCardanoWalletTransaction();
 * ```
 * 
 * This will sign the current transaction in the Cardano wallet.
 * 
 * ## Returns
 * 
 * This action does not return any value.
 * 
 * ## Errors
 * 
 * If an error occurs while signing the transaction, the action will throw an error with a description of what went wrong. This can be caught and handled in your JavaScript code.
 * 
 * ## Note
 * 
 * Please ensure that you have the necessary permissions and the correct environment set up before using this action. The action assumes that a Cardano wallet transaction is in progress and will fail if this is not the case.
 * @param {MxObject} wallet
 * @param {string} transactionData - CBOR-encoded transaction data
 * @returns {Promise.<string>}
 */
export async function JS_SignCardanoWalletTransaction(wallet, transactionData) {
	// BEGIN USER CODE
    const walletIdentifier = wallet.get('_id');
    if (!cardano || !cardano[walletIdentifier]) {
        console.error('Wallet not found');
        return false;
    }

    try {
        // Re-enable the wallet and retrieve the wallet API object
        const cardanoWallet = await cardano[walletIdentifier].enable();
        if (!cardanoWallet) {
            throw new Error('Could not enable wallet');
        }

        console.info('Cardano Wallet enabled:', cardanoWallet);

        // Sign the transaction with the wallet
        const signedTransaction = await cardanoWallet.signTx(transactionData, false);

        return signedTransaction;
    } catch (error) {
        console.error("Error signing the transaction:", error);
        return null;
    }
	// END USER CODE
}
