// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.cardanofoundation.signify.cesr.Saider;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_BuildBindingMessage extends UserAction<java.lang.String>
{
	private final java.lang.String AIDPrefix;
	private final java.lang.String CardanoAddress;
	private final java.lang.String NFTPolicyId;
	private final java.lang.String NFTAssetName;

	public JA_BuildBindingMessage(
		IContext context,
		java.lang.String _aIDPrefix,
		java.lang.String _cardanoAddress,
		java.lang.String _nFTPolicyId,
		java.lang.String _nFTAssetName
	)
	{
		super(context);
		this.AIDPrefix = _aIDPrefix;
		this.CardanoAddress = _cardanoAddress;
		this.NFTPolicyId = _nFTPolicyId;
		this.NFTAssetName = _nFTAssetName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode log = Core.getLogger("KERIAIntegration");

		// Validate inputs
		if (AIDPrefix == null || AIDPrefix.trim().isEmpty()) {
			throw new IllegalArgumentException("AIDPrefix is required");
		}
		if (CardanoAddress == null || CardanoAddress.trim().isEmpty()) {
			throw new IllegalArgumentException("CardanoAddress is required");
		}
		// Build deterministic binding message using LinkedHashMap (preserves insertion order)
		String dt = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSSSS'+00:00'")
			.withZone(ZoneOffset.UTC)
			.format(Instant.now());

		Map<String, Object> bindingMsg = new LinkedHashMap<>();
		bindingMsg.put("d", "");  // SAID placeholder
		bindingMsg.put("aid", AIDPrefix);
		bindingMsg.put("cardanoAddress", CardanoAddress);
		if (NFTPolicyId != null && !NFTPolicyId.trim().isEmpty()
				&& NFTAssetName != null && !NFTAssetName.trim().isEmpty()) {
			bindingMsg.put("nftId", NFTPolicyId + "." + NFTAssetName);
		}
		bindingMsg.put("timestamp", dt);

		// SAIDify for tamper-evidence
		Saider.SaidifyResult saidResult = Saider.saidify(bindingMsg);
		Map<String, Object> saidifiedMsg = saidResult.sad();

		ObjectMapper mapper = new ObjectMapper();
		String json = mapper.writeValueAsString(saidifiedMsg);

		log.info("Built binding message with SAID: " + saidifiedMsg.get("d"));
		log.debug("Binding message: " + json);

		return json;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_BuildBindingMessage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
