// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.util.Date;
import org.cardanofoundation.signify.app.aiding.CreateIdentifierArgs;
import org.cardanofoundation.signify.app.aiding.EventResult;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.app.coring.Operation;
import org.cardanofoundation.signify.cesr.Salter;
import org.cardanofoundation.signify.core.States.HabState;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_BootstrapBackendAID extends UserAction<java.lang.Void>
{
	/** @deprecated use BackendIdentity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __BackendIdentity;
	private final keriaintegration.proxies.BackendIdentity BackendIdentity;

	public JA_BootstrapBackendAID(
		IContext context,
		IMendixObject _backendIdentity
	)
	{
		super(context);
		this.__BackendIdentity = _backendIdentity;
		this.BackendIdentity = _backendIdentity == null ? null : keriaintegration.proxies.BackendIdentity.initialize(getContext(), _backendIdentity);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		ILogNode log = Core.getLogger("KERIAIntegration");

		// Validate input
		if (BackendIdentity == null) {
			throw new IllegalArgumentException("BackendIdentity entity is required");
		}

		// Check if AIDPrefix is already set - if so, nothing to do
		String existingPrefix = BackendIdentity.getAIDPrefix(context);
		if (existingPrefix != null && !existingPrefix.trim().isEmpty()) {
			log.debug("BackendIdentity already has AIDPrefix set, skipping bootstrap");
			Core.commit(context, BackendIdentity.getMendixObject());
			return null;
		}

		// Load constants
		String keriaUrl = getConstant("KERIAIntegration.KERIA_URL");
		String keriaBootUrl = getConstant("KERIAIntegration.KERIA_BOOT_URL");
		String controllerBran = getConstant("KERIAIntegration.KERIA_CONTROLLER_BRAN");
		String tierString = getConstant("KERIAIntegration.KERIA_SALTER_TIER");
		String identifierAlias = getConstant("KERIAIntegration.BACKEND_IDENTIFIER_ALIAS");

		// Validate required constants
		validateConstant(keriaUrl, "KERIA_URL");
		validateConstant(keriaBootUrl, "KERIA_BOOT_URL");
		validateConstant(controllerBran, "KERIA_CONTROLLER_BRAN");
		validateConstant(identifierAlias, "BACKEND_IDENTIFIER_ALIAS");

		// Parse tier (default to low if not specified or invalid)
		Salter.Tier tier = parseTier(tierString);

		log.info("Bootstrapping backend AID with alias: " + identifierAlias);
		log.debug("KERIA URL: " + keriaUrl);
		log.debug("KERIA Boot URL: " + keriaBootUrl);

		// Create SignifyClient
		SignifyClient client = new SignifyClient(
			keriaUrl,
			controllerBran,
			tier,
			keriaBootUrl,
			null  // No external modules
		);

		// Boot and connect to KERIA agent
		// First check if agent already exists by calling state()
		boolean needsBoot = false;
		try {
			client.state();
			log.debug("Agent already exists");
		} catch (IllegalArgumentException e) {
			if (e.getMessage() != null && e.getMessage().contains("Agent does not exist")) {
				needsBoot = true;
			} else {
				throw new RuntimeException("Failed to check agent state: " + e.getMessage(), e);
			}
		}

		if (needsBoot) {
			log.info("Agent does not exist, booting new agent...");
			client.boot();
			log.debug("KERIA agent booted successfully");
		}

		// Connect to the agent (this internally calls approveDelegation())
		log.debug("Connecting to KERIA agent...");
		client.connect();
		log.debug("Connected to KERIA agent");

		// Note: Do NOT call approveDelegation() again - connect() already does it.
		// Calling it twice creates duplicate interaction events that corrupt auth state.

		// Try to get existing identifier, or create if not found
		// Note: cf-signify-java may have auth issues - we try create directly if get fails
		String aidPrefix;
		HabState existingIdentifier = null;

		try {
			log.debug("Checking if identifier '" + identifierAlias + "' already exists...");
			existingIdentifier = client.identifiers().get(identifierAlias).orElse(null);
		} catch (Exception e) {
			// May fail with 401 or 404 - we'll try to create instead
			log.debug("Could not get identifier (may not exist): " + e.getMessage());
		}

		if (existingIdentifier != null) {
			// Identifier exists - retrieve its prefix
			aidPrefix = existingIdentifier.getPrefix();
			log.info("Found existing backend identifier with prefix: " + aidPrefix);

			// Ensure agent end role exists (may be missing from older bootstrap)
			ensureAgentEndRole(client, identifierAlias, log);
		} else {
			// Create new transferable identifier with default thresholds
			log.info("Creating new backend identifier: " + identifierAlias);

			try {
				CreateIdentifierArgs args = CreateIdentifierArgs.builder()
					.transferable(true)
					.isith("1")   // Signing threshold = 1
					.nsith("1")   // Next signing threshold = 1
					.build();

				EventResult result = client.identifiers().create(identifierAlias, args);
				log.debug("Identifier creation initiated, waiting for operation...");

				// Wait for the operation to complete
				Operation<?> operation = Operation.fromObject(result.op());
				client.operations().wait(operation);
				log.debug("Operation completed");

				// Retrieve the created identifier to get the prefix
				HabState createdIdentifier = client.identifiers().get(identifierAlias)
					.orElseThrow(() -> new RuntimeException("Failed to retrieve newly created identifier: " + identifierAlias));

				aidPrefix = createdIdentifier.getPrefix();
				log.info("Created backend identifier with prefix: " + aidPrefix);

				// Add agent end role so OOBIs can be generated
				// The eid (endpoint id) is the agent's AID prefix
				String agentAid = client.getAgent().getPre();
				log.debug("Adding agent end role with agent AID: " + agentAid);

				EventResult endRoleResult = client.identifiers().addEndRole(
					identifierAlias, "agent", agentAid, null);

				// Wait for the end role operation to complete
				Operation<?> endRoleOp = Operation.fromObject(endRoleResult.op());
				client.operations().wait(endRoleOp);
				log.debug("Agent end role added successfully");

			} catch (Exception e) {
				// If create also fails with 401, the library has an auth bug
				log.error("Failed to create identifier: " + e.getMessage());
				throw new RuntimeException(
					"KERIA API calls failing with 401 after successful connect(). " +
					"This appears to be a bug in cf-signify-java library. " +
					"The approveDelegation() step may not be completing properly. " +
					"Original error: " + e.getMessage(), e);
			}
		}

		// Update BackendIdentity entity
		BackendIdentity.setAIDPrefix(context, aidPrefix);
		BackendIdentity.setIdentifierAlias(context, identifierAlias);
		BackendIdentity.setIsActive(context, true);

		// Only set CreatedAt if not already set
		if (BackendIdentity.getCreatedAt(context) == null) {
			BackendIdentity.setCreatedAt(context, new Date());
		}

		// Commit the changes
		Core.commit(context, BackendIdentity.getMendixObject());
		log.info("BackendIdentity committed successfully");

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_BootstrapBackendAID";
	}

	// BEGIN EXTRA CODE
	/**
	 * Retrieves a Mendix constant value by its full name.
	 * @param constantName The full constant name (e.g., "ModuleName.ConstantName")
	 * @return The constant value as String, or null if not found
	 */
	private String getConstant(String constantName) {
		Object value = Core.getConfiguration().getConstantValue(constantName);
		return value != null ? value.toString() : null;
	}

	/**
	 * Validates that a constant has a non-empty value.
	 * @param value The constant value
	 * @param constantName The constant name for error messaging
	 * @throws IllegalStateException if the constant is null or empty
	 */
	private void validateConstant(String value, String constantName) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalStateException(
				"Required constant KERIAIntegration." + constantName + " is not configured"
			);
		}
	}

	/**
	 * Parses the tier string to a Salter.Tier enum value.
	 * Defaults to Tier.low if the string is invalid or null.
	 * @param tierString The tier string ("low", "med", or "high")
	 * @return The corresponding Salter.Tier value
	 */
	private Salter.Tier parseTier(String tierString) {
		if (tierString == null || tierString.trim().isEmpty()) {
			return Salter.Tier.low;
		}
		return switch (tierString.toLowerCase().trim()) {
			case "low" -> Salter.Tier.low;
			case "med" -> Salter.Tier.med;
			case "high" -> Salter.Tier.high;
			default -> Salter.Tier.low;
		};
	}

	/**
	 * Ensures the agent end role is configured for the identifier.
	 * This is required for OOBIs to be generated.
	 * If the end role already exists, this is a no-op.
	 */
	private void ensureAgentEndRole(SignifyClient client, String identifierAlias, ILogNode log)
			throws Exception {
		String agentAid = client.getAgent().getPre();
		log.debug("Ensuring agent end role with agent AID: " + agentAid);

		try {
			EventResult endRoleResult = client.identifiers().addEndRole(
				identifierAlias, "agent", agentAid, null);

			// Wait for the end role operation to complete
			Operation<?> endRoleOp = Operation.fromObject(endRoleResult.op());
			client.operations().wait(endRoleOp);
			log.debug("Agent end role added/verified successfully");
		} catch (Exception e) {
			// If the end role already exists, KERIA may return an error
			// Log but don't fail - the role may already be configured
			log.debug("End role operation result: " + e.getMessage());
		}
	}
	// END EXTRA CODE
}
