// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.util.Date;
import java.util.List;
import java.util.Map;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.app.coring.Operation;
import org.cardanofoundation.signify.app.coring.Operations;
import org.cardanofoundation.signify.app.credentialing.registries.CreateRegistryArgs;
import org.cardanofoundation.signify.app.credentialing.registries.RegistryResult;
import org.cardanofoundation.signify.cesr.Salter;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_CreateCredentialRegistry extends UserAction<java.lang.Void>
{
	/** @deprecated use BackendIdentity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __BackendIdentity;
	private final keriaintegration.proxies.BackendIdentity BackendIdentity;
	/** @deprecated use CredentialRegistry.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CredentialRegistry;
	private final keriaintegration.proxies.CredentialRegistry CredentialRegistry;

	public JA_CreateCredentialRegistry(
		IContext context,
		IMendixObject _backendIdentity,
		IMendixObject _credentialRegistry
	)
	{
		super(context);
		this.__BackendIdentity = _backendIdentity;
		this.BackendIdentity = _backendIdentity == null ? null : keriaintegration.proxies.BackendIdentity.initialize(getContext(), _backendIdentity);
		this.__CredentialRegistry = _credentialRegistry;
		this.CredentialRegistry = _credentialRegistry == null ? null : keriaintegration.proxies.CredentialRegistry.initialize(getContext(), _credentialRegistry);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		ILogNode log = Core.getLogger("KERIAIntegration");

		// Validate inputs
		if (BackendIdentity == null) {
			throw new IllegalArgumentException("BackendIdentity entity is required");
		}
		if (CredentialRegistry == null) {
			throw new IllegalArgumentException("CredentialRegistry entity is required");
		}

		String existingRegId = CredentialRegistry.getRegistryID(context);
		if (existingRegId != null && !existingRegId.trim().isEmpty()) {
			log.info("CredentialRegistry already has RegistryID set (" + existingRegId + "), skipping creation");
			return null;
		}

		// Load constants
		String keriaUrl = getConstant("KERIAIntegration.KERIA_URL");
		String keriaBootUrl = getConstant("KERIAIntegration.KERIA_BOOT_URL");
		String controllerBran = getConstant("KERIAIntegration.KERIA_CONTROLLER_BRAN");
		String tierString = getConstant("KERIAIntegration.KERIA_SALTER_TIER");
		String identifierAlias = getConstant("KERIAIntegration.BACKEND_IDENTIFIER_ALIAS");
		String registryName = getConstant("KERIAIntegration.CREDENTIAL_REGISTRY_NAME");
		String vleiServerUrl = getConstant("KERIAIntegration.VLEI_SERVER_URL");
		String qviSchemaSaid = getConstant("KERIAIntegration.QVI_SCHEMA_SAID");

		validateConstant(keriaUrl, "KERIA_URL");
		validateConstant(keriaBootUrl, "KERIA_BOOT_URL");
		validateConstant(controllerBran, "KERIA_CONTROLLER_BRAN");
		validateConstant(identifierAlias, "BACKEND_IDENTIFIER_ALIAS");
		validateConstant(registryName, "CREDENTIAL_REGISTRY_NAME");

		Salter.Tier tier = parseTier(tierString);

		log.info("Creating credential registry '" + registryName + "' for alias: " + identifierAlias);

		// Connect to KERIA
		SignifyClient client = new SignifyClient(keriaUrl, controllerBran, tier, keriaBootUrl, null);
		client.connect();
		log.debug("Connected to KERIA agent");

		// Check if registry already exists
		String regk = null;
		try {
			Object registries = client.registries().list(identifierAlias);
			@SuppressWarnings("unchecked")
			List<Map<String, Object>> registryList = (List<Map<String, Object>>) registries;
			if (registryList != null && !registryList.isEmpty()) {
				for (Map<String, Object> reg : registryList) {
					String name = reg.get("name") != null ? reg.get("name").toString() : "";
					if (registryName.equals(name)) {
						regk = reg.get("regk").toString();
						log.info("Registry already exists with regk: " + regk);
						break;
					}
				}
			}
		} catch (Exception e) {
			log.debug("Could not list registries (may not exist yet): " + e.getMessage());
		}

		// Create registry if it doesn't exist
		if (regk == null) {
			log.info("Registry not found, creating new registry: " + registryName);

			CreateRegistryArgs registryArgs = CreateRegistryArgs.builder().build();
			registryArgs.setName(identifierAlias);
			registryArgs.setRegistryName(registryName);

			RegistryResult regResult = client.registries().create(registryArgs);

			// RegistryResult.op() returns String (raw response body) - need Operation.fromObject
			Operation<?> operation = Operation.fromObject(regResult.op());
			client.operations().wait(operation);
			log.debug("Registry creation operation completed");

			// List registries to get the regk
			Object registries = client.registries().list(identifierAlias);
			@SuppressWarnings("unchecked")
			List<Map<String, Object>> registryList = (List<Map<String, Object>>) registries;
			if (registryList == null || registryList.isEmpty()) {
				throw new RuntimeException("Registry was created but not found in list");
			}
			for (Map<String, Object> reg : registryList) {
				String name = reg.get("name") != null ? reg.get("name").toString() : "";
				if (registryName.equals(name)) {
					regk = reg.get("regk").toString();
					break;
				}
			}
			if (regk == null) {
				throw new RuntimeException("Registry was created but could not find regk for: " + registryName);
			}
			log.info("Created registry with regk: " + regk);
		}

		// Resolve schema OOBIs (if vLEI server URL is properly configured)
		if (vleiServerUrl != null && vleiServerUrl.startsWith("http")
				&& qviSchemaSaid != null && !qviSchemaSaid.trim().isEmpty()) {
			String schemaOobiUrl = vleiServerUrl + "/oobi/" + qviSchemaSaid;
			log.info("Resolving schema OOBI: " + schemaOobiUrl);
			try {
				Object resolveResult = client.oobis().resolve(schemaOobiUrl, "");
				Operation<?> resolveOp = Operation.fromObject(resolveResult);

				// Use 30-second timeout to prevent hanging on unreachable servers
				Operations.AbortSignal abortSignal = new Operations.AbortSignal();
				abortSignal.setTimeout(30_000L);
				Operations.WaitOptions waitOptions = Operations.WaitOptions.builder()
					.abortSignal(abortSignal)
					.build();
				client.operations().wait(resolveOp, waitOptions);
				log.info("Schema OOBI resolved successfully for: " + qviSchemaSaid);
			} catch (Exception e) {
				log.warn("Failed to resolve schema OOBI (non-fatal): " + e.getMessage());
			}
		} else {
			log.warn("VLEI_SERVER_URL not configured as a valid URL or QVI_SCHEMA_SAID missing, skipping schema OOBI resolution");
		}

		// Populate CredentialRegistry entity
		CredentialRegistry.setRegistryID(context, regk);
		CredentialRegistry.setRegistryName(context, registryName);
		CredentialRegistry.setIdentifierAlias(context, identifierAlias);
		CredentialRegistry.setCreatedAt(context, new Date());
		CredentialRegistry.setIsActive(context, true);
		CredentialRegistry.setCredentialRegistry_BackendIdentity(context, BackendIdentity);

		Core.commit(context, CredentialRegistry.getMendixObject());
		log.info("CredentialRegistry committed successfully with regk: " + regk);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CreateCredentialRegistry";
	}

	// BEGIN EXTRA CODE
	private String getConstant(String constantName) {
		Object value = Core.getConfiguration().getConstantValue(constantName);
		return value != null ? value.toString() : null;
	}

	private void validateConstant(String value, String constantName) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalStateException(
				"Required constant KERIAIntegration." + constantName + " is not configured"
			);
		}
	}

	private Salter.Tier parseTier(String tierString) {
		if (tierString == null || tierString.trim().isEmpty()) {
			return Salter.Tier.low;
		}
		return switch (tierString.toLowerCase().trim()) {
			case "low" -> Salter.Tier.low;
			case "med" -> Salter.Tier.med;
			case "high" -> Salter.Tier.high;
			default -> Salter.Tier.low;
		};
	}
	// END EXTRA CODE
}
