// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

public class JA_FetchNFTBindingMetadata extends UserAction<java.lang.Void>
{
	/** @deprecated use NFTVerification.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __NFTVerification;
	private final keriaintegration.proxies.NFTVerification NFTVerification;
	private final java.lang.String AssetUnit;
	private final java.lang.String BlockfrostAPIKey;
	private final java.lang.String BlockfrostBaseUrl;

	public JA_FetchNFTBindingMetadata(
		IContext context,
		IMendixObject _nFTVerification,
		java.lang.String _assetUnit,
		java.lang.String _blockfrostAPIKey,
		java.lang.String _blockfrostBaseUrl
	)
	{
		super(context);
		this.__NFTVerification = _nFTVerification;
		this.NFTVerification = _nFTVerification == null ? null : keriaintegration.proxies.NFTVerification.initialize(getContext(), _nFTVerification);
		this.AssetUnit = _assetUnit;
		this.BlockfrostAPIKey = _blockfrostAPIKey;
		this.BlockfrostBaseUrl = _blockfrostBaseUrl;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode log = Core.getLogger("KERIAIntegration");

		if (AssetUnit == null || AssetUnit.trim().isEmpty())
			throw new IllegalArgumentException("AssetUnit is required");
		if (BlockfrostAPIKey == null || BlockfrostAPIKey.trim().isEmpty())
			throw new IllegalArgumentException("BlockfrostAPIKey is required");
		if (BlockfrostBaseUrl == null || BlockfrostBaseUrl.trim().isEmpty())
			throw new IllegalArgumentException("BlockfrostBaseUrl is required");

		// Call Blockfrost
		String url = BlockfrostBaseUrl.replaceAll("/$", "") + "/assets/" + AssetUnit;
		OkHttpClient client = new OkHttpClient();
		Request request = new Request.Builder()
			.url(url)
			.header("project_id", BlockfrostAPIKey)
			.build();

		String responseBody;
		try (Response response = client.newCall(request).execute()) {
			if (!response.isSuccessful())
				throw new RuntimeException("Blockfrost request failed: " + response.code() + " " + response.message());
			responseBody = response.body().string();
		}

		log.debug("Blockfrost asset response: " + responseBody);

		// Parse onchain_metadata
		ObjectMapper mapper = new ObjectMapper();
		JsonNode root = mapper.readTree(responseBody);
		JsonNode meta = root.get("onchain_metadata");
		if (meta == null || meta.isNull())
			throw new RuntimeException("No onchain_metadata found for asset: " + AssetUnit);

		if (NFTVerification == null)
			throw new IllegalArgumentException("NFTVerification is required");

		// Populate the input NFTVerification in-place
		NFTVerification.setOnChainKERISAID(textValue(meta, "KERIChallengeSAID"));
		NFTVerification.setCardanoSignatureHex(reassembleChunks(meta.get("CardanoSignatureHex")));
		NFTVerification.setCardanoKeyHex(reassembleChunks(meta.get("CardanoKeyHex")));
		NFTVerification.setBindingMessage(reassembleChunks(meta.get("BindingMessage")));

		log.info("Fetched NFT binding metadata for asset: " + AssetUnit);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_FetchNFTBindingMetadata";
	}

	// BEGIN EXTRA CODE
	private String reassembleChunks(com.fasterxml.jackson.databind.JsonNode node) {
		if (node == null || node.isNull()) return null;
		if (node.isTextual()) return node.asText();
		if (node.isArray()) {
			StringBuilder sb = new StringBuilder();
			node.forEach(chunk -> sb.append(chunk.asText()));
			return sb.toString();
		}
		return null;
	}

	private String textValue(com.fasterxml.jackson.databind.JsonNode node, String field) {
		com.fasterxml.jackson.databind.JsonNode child = node.get(field);
		if (child == null || child.isNull()) return null;
		return child.asText();
	}
	// END EXTRA CODE
}
