// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.cardanofoundation.signify.app.Exchanging;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.app.coring.Operation;
import org.cardanofoundation.signify.app.credentialing.ipex.IpexGrantArgs;
import org.cardanofoundation.signify.cesr.Salter;
import org.cardanofoundation.signify.cesr.Serder;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_GrantCredentialToWallet extends UserAction<java.lang.Void>
{
	/** @deprecated use BackendIdentity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __BackendIdentity;
	private final keriaintegration.proxies.BackendIdentity BackendIdentity;
	/** @deprecated use IssuedCredential.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __IssuedCredential;
	private final keriaintegration.proxies.IssuedCredential IssuedCredential;
	/** @deprecated use WalletContact.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __WalletContact;
	private final keriaintegration.proxies.WalletContact WalletContact;

	public JA_GrantCredentialToWallet(
		IContext context,
		IMendixObject _backendIdentity,
		IMendixObject _issuedCredential,
		IMendixObject _walletContact
	)
	{
		super(context);
		this.__BackendIdentity = _backendIdentity;
		this.BackendIdentity = _backendIdentity == null ? null : keriaintegration.proxies.BackendIdentity.initialize(getContext(), _backendIdentity);
		this.__IssuedCredential = _issuedCredential;
		this.IssuedCredential = _issuedCredential == null ? null : keriaintegration.proxies.IssuedCredential.initialize(getContext(), _issuedCredential);
		this.__WalletContact = _walletContact;
		this.WalletContact = _walletContact == null ? null : keriaintegration.proxies.WalletContact.initialize(getContext(), _walletContact);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		ILogNode log = Core.getLogger("KERIAIntegration");

		// Validate inputs
		if (BackendIdentity == null) {
			throw new IllegalArgumentException("BackendIdentity is required");
		}
		if (IssuedCredential == null) {
			throw new IllegalArgumentException("IssuedCredential is required");
		}
		if (WalletContact == null) {
			throw new IllegalArgumentException("WalletContact is required");
		}

		String credentialId = IssuedCredential.getCredentialID(context);
		if (credentialId == null || credentialId.trim().isEmpty()) {
			throw new IllegalArgumentException("IssuedCredential has no CredentialID set - issue credential first");
		}
		String holderPrefix = WalletContact.getAIDPrefix(context);
		if (holderPrefix == null || holderPrefix.trim().isEmpty()) {
			throw new IllegalArgumentException("WalletContact has no AIDPrefix set");
		}

		// Load constants
		String keriaUrl = getConstant("KERIAIntegration.KERIA_URL");
		String keriaBootUrl = getConstant("KERIAIntegration.KERIA_BOOT_URL");
		String controllerBran = getConstant("KERIAIntegration.KERIA_CONTROLLER_BRAN");
		String tierString = getConstant("KERIAIntegration.KERIA_SALTER_TIER");
		String identifierAlias = getConstant("KERIAIntegration.BACKEND_IDENTIFIER_ALIAS");

		validateConstant(keriaUrl, "KERIA_URL");
		validateConstant(keriaBootUrl, "KERIA_BOOT_URL");
		validateConstant(controllerBran, "KERIA_CONTROLLER_BRAN");
		validateConstant(identifierAlias, "BACKEND_IDENTIFIER_ALIAS");

		Salter.Tier tier = parseTier(tierString);

		log.info("Granting credential " + credentialId + " to wallet: " + holderPrefix);

		// Connect to KERIA
		SignifyClient client = new SignifyClient(keriaUrl, controllerBran, tier, keriaBootUrl, null);
		client.connect();
		log.debug("Connected to KERIA agent");

		// Retrieve the issued credential from KERIA
		// Returns: {sad: {...}, anc: {...}, iss: {...}, status: {...}, atc: "..."}
		Object credentialObj = client.credentials().get(credentialId)
			.orElseThrow(() -> new RuntimeException(
				"Credential not found in KERIA: " + credentialId +
				". Ensure JA_IssueCredential was called before granting."));
		@SuppressWarnings("unchecked")
		LinkedHashMap<String, Object> credential = (LinkedHashMap<String, Object>) credentialObj;

		@SuppressWarnings("unchecked")
		Map<String, Object> sad = (Map<String, Object>) credential.get("sad");
		@SuppressWarnings("unchecked")
		Map<String, Object> anc = (Map<String, Object>) credential.get("anc");
		@SuppressWarnings("unchecked")
		Map<String, Object> iss = (Map<String, Object>) credential.get("iss");

		log.debug("Retrieved credential SAD, ANC, ISS for IPEX grant");

		// Build IPEX Grant args
		String dt = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSSSS'+00:00'")
			.withZone(ZoneOffset.UTC)
			.format(Instant.now());

		IpexGrantArgs grantArgs = IpexGrantArgs.builder().build();
		grantArgs.setSenderName(identifierAlias);
		grantArgs.setAcdc(new Serder(sad));
		grantArgs.setAnc(new Serder(anc));
		grantArgs.setIss(new Serder(iss));
		grantArgs.setAncAttachment(null); // Auto-generated by Ipex.grant()
		grantArgs.setRecipient(holderPrefix);
		grantArgs.setDatetime(dt);

		// Create and submit the IPEX grant exchange message
		log.info("Creating IPEX grant exchange message...");
		Exchanging.ExchangeMessageResult result = client.ipex().grant(grantArgs);

		List<String> recipients = Collections.singletonList(holderPrefix);
		log.info("Submitting IPEX grant to recipient...");
		Object op = client.ipex().submitGrant(identifierAlias, result.exn(), result.sigs(), result.atc(), recipients);

		// Wait for operation to complete
		Operation<?> operation = Operation.fromObject(op);
		client.operations().wait(operation);
		log.debug("IPEX grant operation completed");

		// Extract grant SAID from the exchange message
		String grantSaid = result.exn().getKed().get("d").toString();
		log.info("IPEX Grant sent with SAID: " + grantSaid);

		// Update IssuedCredential entity
		IssuedCredential.setStatus(context, keriaintegration.proxies.Enum_CredentialStatus.Granted);
		IssuedCredential.setGrantedAt(context, new Date());
		IssuedCredential.setGrantSAID(context, grantSaid);

		Core.commit(context, IssuedCredential.getMendixObject());
		log.info("IssuedCredential updated to status=Granted, GrantSAID: " + grantSaid);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GrantCredentialToWallet";
	}

	// BEGIN EXTRA CODE
	private String getConstant(String constantName) {
		Object value = Core.getConfiguration().getConstantValue(constantName);
		return value != null ? value.toString() : null;
	}

	private void validateConstant(String value, String constantName) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalStateException(
				"Required constant KERIAIntegration." + constantName + " is not configured"
			);
		}
	}

	private Salter.Tier parseTier(String tierString) {
		if (tierString == null || tierString.trim().isEmpty()) {
			return Salter.Tier.low;
		}
		return switch (tierString.toLowerCase().trim()) {
			case "low" -> Salter.Tier.low;
			case "med" -> Salter.Tier.med;
			case "high" -> Salter.Tier.high;
			default -> Salter.Tier.low;
		};
	}
	// END EXTRA CODE
}
