// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.util.Map;
import java.util.Optional;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.cesr.Salter;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_GetBackendOOBI extends UserAction<java.lang.String>
{
	/** @deprecated use BackendIdentity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __BackendIdentity;
	private final keriaintegration.proxies.BackendIdentity BackendIdentity;

	public JA_GetBackendOOBI(
		IContext context,
		IMendixObject _backendIdentity
	)
	{
		super(context);
		this.__BackendIdentity = _backendIdentity;
		this.BackendIdentity = _backendIdentity == null ? null : keriaintegration.proxies.BackendIdentity.initialize(getContext(), _backendIdentity);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		ILogNode log = Core.getLogger("KERIAIntegration");

		// Validate input
		if (BackendIdentity == null) {
			throw new IllegalArgumentException("BackendIdentity entity is required");
		}

		// Validate AIDPrefix is set
		String aidPrefix = BackendIdentity.getAIDPrefix(context);
		if (aidPrefix == null || aidPrefix.trim().isEmpty()) {
			throw new IllegalStateException(
				"BackendIdentity.AIDPrefix is not set. " +
				"The backend identity must be bootstrapped before retrieving its OOBI."
			);
		}

		// Get identifier alias
		String identifierAlias = BackendIdentity.getIdentifierAlias(context);
		if (identifierAlias == null || identifierAlias.trim().isEmpty()) {
			throw new IllegalStateException(
				"BackendIdentity.IdentifierAlias is not set. " +
				"The backend identity must be bootstrapped before retrieving its OOBI."
			);
		}

		// Load constants (do not log the bran)
		String keriaUrl = getConstant("KERIAIntegration.KERIA_URL");
		String keriaBootUrl = getConstant("KERIAIntegration.KERIA_BOOT_URL");
		String controllerBran = getConstant("KERIAIntegration.KERIA_CONTROLLER_BRAN");
		String tierString = getConstant("KERIAIntegration.KERIA_SALTER_TIER");

		// Validate required constants
		validateConstant(keriaUrl, "KERIA_URL");
		validateConstant(keriaBootUrl, "KERIA_BOOT_URL");
		validateConstant(controllerBran, "KERIA_CONTROLLER_BRAN");

		// Parse tier
		Salter.Tier tier = parseTier(tierString);

		log.debug("Retrieving OOBI for backend identifier: " + identifierAlias);

		// Create SignifyClient and connect
		SignifyClient client = new SignifyClient(
			keriaUrl,
			controllerBran,
			tier,
			keriaBootUrl,
			null
		);

		// Connect to existing agent (do not boot - agent must already exist)
		client.connect();
		log.debug("Connected to KERIA agent");

		// Retrieve OOBI for the backend identifier with default "agent" role
		Object oobiResponse = client.oobis().get(identifierAlias, "agent");

		if (oobiResponse == null) {
			throw new RuntimeException(
				"No OOBI found for identifier: " + identifierAlias + ". " +
				"Ensure the identifier exists and has an agent role configured."
			);
		}

		// Extract the OOBI URL from the response
		String oobiUrl = extractOobiUrl(oobiResponse, identifierAlias, log);

		log.info("Retrieved OOBI for backend identifier: " + identifierAlias);
		log.debug("OOBI: " + oobiUrl);

		return oobiUrl;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetBackendOOBI";
	}

	// BEGIN EXTRA CODE
	/**
	 * Retrieves a Mendix constant value by its full name.
	 * @param constantName The full constant name (e.g., "ModuleName.ConstantName")
	 * @return The constant value as String, or null if not found
	 */
	private String getConstant(String constantName) {
		Object value = Core.getConfiguration().getConstantValue(constantName);
		return value != null ? value.toString() : null;
	}

	/**
	 * Validates that a constant has a non-empty value.
	 * @param value The constant value
	 * @param constantName The constant name for error messaging
	 * @throws IllegalStateException if the constant is null or empty
	 */
	private void validateConstant(String value, String constantName) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalStateException(
				"Required constant KERIAIntegration." + constantName + " is not configured"
			);
		}
	}

	/**
	 * Parses the tier string to a Salter.Tier enum value.
	 * Defaults to Tier.low if the string is invalid or null.
	 * @param tierString The tier string ("low", "med", or "high")
	 * @return The corresponding Salter.Tier value
	 */
	private Salter.Tier parseTier(String tierString) {
		if (tierString == null || tierString.trim().isEmpty()) {
			return Salter.Tier.low;
		}
		return switch (tierString.toLowerCase().trim()) {
			case "low" -> Salter.Tier.low;
			case "med" -> Salter.Tier.med;
			case "high" -> Salter.Tier.high;
			default -> Salter.Tier.low;
		};
	}

	/**
	 * Extracts the OOBI URL from the KERIA response.
	 * The response structure is: {"oobis": ["http://..."]}
	 * @param response The response object from KERIA
	 * @param identifierAlias The identifier alias (for error messages)
	 * @return The first OOBI URL
	 * @throws RuntimeException if no OOBI is found in the response
	 */
	@SuppressWarnings("unchecked")
	private String extractOobiUrl(Object response, String identifierAlias, ILogNode log) {
		// Log the full response for debugging
		log.debug("OOBI response type: " + (response != null ? response.getClass().getName() : "null"));
		log.debug("OOBI response content: " + response);

		// Unwrap Optional if present (cf-signify-java 0.1.2+ returns Optional<Map>)
		Object unwrapped = response;
		if (response instanceof Optional) {
			Optional<?> opt = (Optional<?>) response;
			if (opt.isEmpty()) {
				throw new RuntimeException(
					"Empty OOBI response (Optional.empty) for identifier: " + identifierAlias
				);
			}
			unwrapped = opt.get();
			log.debug("Unwrapped Optional, inner type: " + unwrapped.getClass().getName());
		}

		if (unwrapped instanceof Map) {
			Map<String, Object> responseMap = (Map<String, Object>) unwrapped;
			log.debug("Response keys: " + responseMap.keySet());

			// Try "oobis" key first (array format)
			Object oobisObj = responseMap.get("oobis");
			if (oobisObj instanceof java.util.List) {
				java.util.List<Object> oobisList = (java.util.List<Object>) oobisObj;
				if (!oobisList.isEmpty()) {
					Object firstOobi = oobisList.get(0);
					if (firstOobi != null) {
						return firstOobi.toString();
					}
				}
			} else if (oobisObj instanceof String) {
				// Maybe it's a single string, not an array
				return (String) oobisObj;
			}

			// Try "oobi" key (singular, non-array format)
			Object oobiObj = responseMap.get("oobi");
			if (oobiObj instanceof String) {
				return (String) oobiObj;
			}

			// Try direct URL in response (some KERIA versions)
			Object urlObj = responseMap.get("url");
			if (urlObj instanceof String) {
				return (String) urlObj;
			}
		}

		// If response is directly a String, return it
		if (unwrapped instanceof String) {
			return (String) unwrapped;
		}

		throw new RuntimeException(
			"Unable to extract OOBI URL from KERIA response for identifier: " + identifierAlias +
			". Response: " + response
		);
	}
	// END EXTRA CODE
}
