// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.util.concurrent.TimeUnit;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.app.aiding.EventResult;
import org.cardanofoundation.signify.app.aiding.CreateIdentifierArgs;
import org.cardanofoundation.signify.core.States.HabState;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import communitycommons.StringUtils;

public class JA_HelloSignify extends UserAction<java.lang.String>
{
	public JA_HelloSignify(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        // Mendix log
        ILogNode log = Core.getLogger("SignifyHello");
        log.info("JA_HelloSignify action started");

        // ------------------------------------------------------------
        // 1. Configure your KERIA sandbox URLs
        // ------------------------------------------------------------
        // KERIA uses different ports:
        // - Port 3901: Admin/connect port for Signify clients
        // - Port 3903: Boot port for onboarding new agents (often restricted)
        // TODO: Update these URLs based on your KERIA deployment
        // String keriaAdminUrl = "https://keria.demo.idw-sandboxes.cf-deployments.org";
        // String keriaBootUrl = "https://keria-boot.demo.idw-sandboxes.cf-deployments.org"; // May need different URL/port
        String keriaAdminUrl = "https://keria.landano.io";
        String keriaBootUrl = "https://keria-boot.landano.io"; // May need different URL/port

        log.info("Using KERIA Admin URL: " + keriaAdminUrl);
        log.info("Using KERIA Boot URL: " + keriaBootUrl);  

        // ------------------------------------------------------------
        // 2. Create the SignifyClient
        // ------------------------------------------------------------
        // VERY IMPORTANT: pass a temp passcode — only for testing
        // Passcode must be 21 characters using only base64url-safe chars: A-Z, a-z, 0-9, -, _
        String base64urlChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
        StringBuilder passcodeBuilder = new StringBuilder(21);
        java.security.SecureRandom random = new java.security.SecureRandom();
        for (int i = 0; i < 21; i++) {
            passcodeBuilder.append(base64urlChars.charAt(random.nextInt(base64urlChars.length())));
        }
        String passcode = passcodeBuilder.toString();

        // Constructor: SignifyClient(url, bran, tier, bootUrl, externalModules)
        SignifyClient client = new SignifyClient(keriaAdminUrl, passcode, null, keriaBootUrl, null);
        log.info("Signify client created with passcode: " + passcode);

        // Boot the agent in KERIA (creates agent if it doesn't exist)
        log.info("Booting KERIA agent...");
        client.boot();
        log.info("KERIA agent booted successfully");

        // Connect to the agent (initializes manager and authenticator)
        log.info("Connecting to KERIA agent...");
        client.connect();
        log.info("Connected to KERIA agent successfully");

        // ------------------------------------------------------------
        // 3. Test connection by listing existing identifiers
        // ------------------------------------------------------------
        log.info("Testing API connection by listing identifiers...");
        try {
            var existingIds = client.identifiers().list();
            log.info("Successfully listed identifiers: " + (existingIds != null ? existingIds.toString() : "null"));
        } catch (Exception e) {
            log.warn("Failed to list identifiers: " + e.getMessage());
            // Continue anyway - might be first time
        }

        // ------------------------------------------------------------
        // 4. Create an identifier
        // ------------------------------------------------------------
        // Use only alphanumeric name (no special chars or hyphens)
        String localName = "hello" + StringUtils.randomString(6).toLowerCase();
        log.info("Creating identifier with name: " + localName);

        CreateIdentifierArgs args = CreateIdentifierArgs.builder().build();
        EventResult ident = client.identifiers().create(localName, args);

        log.info("Identifier creation started for: " + localName);

        // ------------------------------------------------------------
        // 5. Wait for KERIA to process it
        // ------------------------------------------------------------
        // KERIA works asynchronously — we poll for completion
        HabState result = null;
        for (int i = 0; i < 20; i++) {
            try {
                result = client.identifiers().get(localName).orElse(null);
                if (result != null) {
                    break;
                }
            } catch (Exception e) {
                // Identifier not yet available, wait and retry
            }
            TimeUnit.SECONDS.sleep(1);
        }

        if (result == null) {
            throw new RuntimeException("Identifier was not anchored in time");
        }

        // ------------------------------------------------------------
        // 6. Extract and return the AID
        // ------------------------------------------------------------
        // In KERI, "i" is the identifier prefix (AID)
        // Try different possible accessor methods using reflection
        String aid = null;
        String[] possibleMethods = {"i", "getI", "prefix", "getPrefix", "getId", "getAid"};

        for (String methodName : possibleMethods) {
            try {
                java.lang.reflect.Method method = result.getClass().getMethod(methodName);
                Object value = method.invoke(result);
                if (value instanceof String) {
                    aid = (String) value;
                    log.info("Successfully extracted AID using method: " + methodName);
                    break;
                }
            } catch (Exception e) {
                // Method doesn't exist or failed, try next one
            }
        }

        if (aid == null) {
            log.error("Could not extract AID. Available methods:");
            for (java.lang.reflect.Method m : result.getClass().getMethods()) {
                if (m.getParameterCount() == 0 && m.getReturnType() == String.class) {
                    log.error("  " + m.getName() + "() returns String");
                }
            }
            throw new RuntimeException("Could not extract AID from HabState");
        }

        log.info("Created AID: " + aid);

        return aid;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_HelloSignify";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
