// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.app.coring.Operation;
import org.cardanofoundation.signify.app.coring.Operations;
import org.cardanofoundation.signify.app.credentialing.credentials.CredentialData;
import org.cardanofoundation.signify.app.credentialing.credentials.IssueCredentialResult;
import org.cardanofoundation.signify.cesr.Salter;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_IssueCredential extends UserAction<java.lang.Void>
{
	/** @deprecated use BackendIdentity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __BackendIdentity;
	private final keriaintegration.proxies.BackendIdentity BackendIdentity;
	/** @deprecated use WalletContact.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __WalletContact;
	private final keriaintegration.proxies.WalletContact WalletContact;
	/** @deprecated use CredentialRegistry.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CredentialRegistry;
	private final keriaintegration.proxies.CredentialRegistry CredentialRegistry;
	/** @deprecated use IssuedCredential.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __IssuedCredential;
	private final keriaintegration.proxies.IssuedCredential IssuedCredential;
	private final java.lang.String CredentialSubjectJSON;

	public JA_IssueCredential(
		IContext context,
		IMendixObject _backendIdentity,
		IMendixObject _walletContact,
		IMendixObject _credentialRegistry,
		IMendixObject _issuedCredential,
		java.lang.String _credentialSubjectJSON
	)
	{
		super(context);
		this.__BackendIdentity = _backendIdentity;
		this.BackendIdentity = _backendIdentity == null ? null : keriaintegration.proxies.BackendIdentity.initialize(getContext(), _backendIdentity);
		this.__WalletContact = _walletContact;
		this.WalletContact = _walletContact == null ? null : keriaintegration.proxies.WalletContact.initialize(getContext(), _walletContact);
		this.__CredentialRegistry = _credentialRegistry;
		this.CredentialRegistry = _credentialRegistry == null ? null : keriaintegration.proxies.CredentialRegistry.initialize(getContext(), _credentialRegistry);
		this.__IssuedCredential = _issuedCredential;
		this.IssuedCredential = _issuedCredential == null ? null : keriaintegration.proxies.IssuedCredential.initialize(getContext(), _issuedCredential);
		this.CredentialSubjectJSON = _credentialSubjectJSON;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		ILogNode log = Core.getLogger("KERIAIntegration");

		// Validate inputs
		if (BackendIdentity == null) {
			throw new IllegalArgumentException("BackendIdentity is required");
		}
		if (WalletContact == null) {
			throw new IllegalArgumentException("WalletContact is required");
		}
		if (CredentialRegistry == null) {
			throw new IllegalArgumentException("CredentialRegistry is required");
		}
		if (IssuedCredential == null) {
			throw new IllegalArgumentException("IssuedCredential is required");
		}

		String holderPrefix = WalletContact.getAIDPrefix(context);
		if (holderPrefix == null || holderPrefix.trim().isEmpty()) {
			throw new IllegalArgumentException("WalletContact has no AIDPrefix set");
		}
		String registryId = CredentialRegistry.getRegistryID(context);
		if (registryId == null || registryId.trim().isEmpty()) {
			throw new IllegalArgumentException("CredentialRegistry has no RegistryID set");
		}
		String issuerPrefix = BackendIdentity.getAIDPrefix(context);
		if (issuerPrefix == null || issuerPrefix.trim().isEmpty()) {
			throw new IllegalArgumentException("BackendIdentity has no AIDPrefix set");
		}

		// Load constants
		String keriaUrl = getConstant("KERIAIntegration.KERIA_URL");
		String keriaBootUrl = getConstant("KERIAIntegration.KERIA_BOOT_URL");
		String controllerBran = getConstant("KERIAIntegration.KERIA_CONTROLLER_BRAN");
		String tierString = getConstant("KERIAIntegration.KERIA_SALTER_TIER");
		String identifierAlias = getConstant("KERIAIntegration.BACKEND_IDENTIFIER_ALIAS");
		String qviSchemaSaid = getConstant("KERIAIntegration.QVI_SCHEMA_SAID");
		String vleiServerUrl = getConstant("KERIAIntegration.VLEI_SERVER_URL");

		validateConstant(keriaUrl, "KERIA_URL");
		validateConstant(keriaBootUrl, "KERIA_BOOT_URL");
		validateConstant(controllerBran, "KERIA_CONTROLLER_BRAN");
		validateConstant(identifierAlias, "BACKEND_IDENTIFIER_ALIAS");
		validateConstant(qviSchemaSaid, "QVI_SCHEMA_SAID");

		Salter.Tier tier = parseTier(tierString);

		log.info("Issuing credential to holder: " + holderPrefix + " with schema: " + qviSchemaSaid);

		// Parse credential subject JSON into map
		Map<String, Object> subjectData = new HashMap<>();
		if (CredentialSubjectJSON != null && !CredentialSubjectJSON.trim().isEmpty()) {
			ObjectMapper mapper = new ObjectMapper();
			@SuppressWarnings("unchecked")
			Map<String, Object> parsed = mapper.readValue(CredentialSubjectJSON, Map.class);
			subjectData.putAll(parsed);
		}

		// Connect to KERIA
		SignifyClient client = new SignifyClient(keriaUrl, controllerBran, tier, keriaBootUrl, null);
		client.connect();
		log.debug("Connected to KERIA agent");

		// Ensure schema is loaded in KERIA agent (required before issuing credentials)
		// First check if already cached, then resolve OOBI if not
		boolean schemaLoaded = false;
		try {
			client.schemas().get(qviSchemaSaid).get();
			log.debug("Schema already loaded in KERIA: " + qviSchemaSaid);
			schemaLoaded = true;
		} catch (Exception e) {
			log.debug("Schema not yet loaded in KERIA, will resolve OOBI");
		}

		if (!schemaLoaded) {
			if (vleiServerUrl == null || !vleiServerUrl.startsWith("http")) {
				throw new IllegalStateException(
					"Schema " + qviSchemaSaid + " not loaded in KERIA and VLEI_SERVER_URL is not configured. " +
					"Set VLEI_SERVER_URL to a valid vLEI schema server (e.g. https://schema.testnet.gleif.org:7723)");
			}
			String schemaOobiUrl = vleiServerUrl + "/oobi/" + qviSchemaSaid;
			log.info("Resolving schema OOBI: " + schemaOobiUrl);
			Object resolveResult = client.oobis().resolve(schemaOobiUrl, "");
			Operation<?> resolveOp = Operation.fromObject(resolveResult);

			Operations.AbortSignal abortSignal = new Operations.AbortSignal();
			abortSignal.setTimeout(60_000L);
			Operations.WaitOptions waitOptions = Operations.WaitOptions.builder()
				.abortSignal(abortSignal)
				.build();
			client.operations().wait(resolveOp, waitOptions);
			log.info("Schema OOBI resolved successfully: " + qviSchemaSaid);
		}

		// Build credential subject per ACDC standard:
		// d (SAID) = computed by library
		// i (issuee) = holder AID prefix
		// dt (datetime) = ISO 8601 issuance timestamp
		// additional properties = schema-specific claim attributes from CredentialSubjectJSON
		String dt = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSSSS'+00:00'")
			.withZone(ZoneOffset.UTC)
			.format(Instant.now());

		CredentialData.CredentialSubject subject = CredentialData.CredentialSubject.builder().build();
		subject.setI(holderPrefix);
		subject.setDt(dt);
		subject.setAdditionalProperties(subjectData);

		// Build credential data
		CredentialData cData = CredentialData.builder().build();
		cData.setRi(registryId);
		cData.setS(qviSchemaSaid);
		cData.setA(subject);

		// Issue credential
		log.info("Calling credentials().issue() for alias: " + identifierAlias);
		IssueCredentialResult issResult = client.credentials().issue(identifierAlias, cData);

		// IssueCredentialResult.getOp() returns Operation<?> directly (unlike RegistryResult)
		client.operations().wait(issResult.getOp());
		log.debug("Credential issuance operation completed");

		// Extract credential SAID from the ACDC
		String credentialId = issResult.getAcdc().getKed().get("d").toString();
		log.info("Credential issued with ID: " + credentialId);

		// Populate IssuedCredential entity
		IssuedCredential.setCredentialID(context, credentialId);
		IssuedCredential.setSchemaSAID(context, qviSchemaSaid);
		IssuedCredential.setHolderAIDPrefix(context, holderPrefix);
		IssuedCredential.setIssuerAIDPrefix(context, issuerPrefix);
		IssuedCredential.setCredentialData(context, CredentialSubjectJSON);
		IssuedCredential.setStatus(context, keriaintegration.proxies.Enum_CredentialStatus.Issued);
		IssuedCredential.setIssuedAt(context, new Date());
		IssuedCredential.setIssuedCredential_WalletContact_Receiver(context, WalletContact);
		IssuedCredential.setIssuedCredential_CredentialRegistry(context, CredentialRegistry);
		IssuedCredential.setIssuedCredential_BackendIdentity(context, BackendIdentity);

		Core.commit(context, IssuedCredential.getMendixObject());
		log.info("IssuedCredential committed with status=Issued, ID: " + credentialId);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_IssueCredential";
	}

	// BEGIN EXTRA CODE
	private String getConstant(String constantName) {
		Object value = Core.getConfiguration().getConstantValue(constantName);
		return value != null ? value.toString() : null;
	}

	private void validateConstant(String value, String constantName) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalStateException(
				"Required constant KERIAIntegration." + constantName + " is not configured"
			);
		}
	}

	private Salter.Tier parseTier(String tierString) {
		if (tierString == null || tierString.trim().isEmpty()) {
			return Salter.Tier.low;
		}
		return switch (tierString.toLowerCase().trim()) {
			case "low" -> Salter.Tier.low;
			case "med" -> Salter.Tier.med;
			case "high" -> Salter.Tier.high;
			default -> Salter.Tier.low;
		};
	}
	// END EXTRA CODE
}
