// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.util.Date;
import java.util.LinkedHashMap;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.app.coring.Operation;
import org.cardanofoundation.signify.cesr.Salter;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_ResolveWalletOOBI extends UserAction<java.lang.Void>
{
	/** @deprecated use WalletContact.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __WalletContact;
	private final keriaintegration.proxies.WalletContact WalletContact;
	private final java.lang.String WalletOOBI;

	public JA_ResolveWalletOOBI(
		IContext context,
		IMendixObject _walletContact,
		java.lang.String _walletOOBI
	)
	{
		super(context);
		this.__WalletContact = _walletContact;
		this.WalletContact = _walletContact == null ? null : keriaintegration.proxies.WalletContact.initialize(getContext(), _walletContact);
		this.WalletOOBI = _walletOOBI;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		ILogNode log = Core.getLogger("KERIAIntegration");

		// Validate inputs
		if (WalletContact == null) {
			throw new IllegalArgumentException("WalletContact entity is required");
		}
		if (WalletOOBI == null || WalletOOBI.trim().isEmpty()) {
			throw new IllegalArgumentException("WalletOOBI is required");
		}

		// Get alias from WalletContact, or extract from OOBI URL if not set
		String alias = WalletContact.getAlias(context);
		if (alias == null || alias.trim().isEmpty()) {
			// Try to extract alias from OOBI URL (e.g., ?name=Chief)
			alias = extractAliasFromOobiUrl(WalletOOBI);
			if (alias != null && !alias.trim().isEmpty()) {
				log.debug("Extracted alias from OOBI URL: " + alias);
				WalletContact.setAlias(context, alias);
			}
		}

		// If still no alias, generate one from the AID in the URL
		if (alias == null || alias.trim().isEmpty()) {
			String aidFromUrl = extractAidFromOobiUrl(WalletOOBI, log);
			if (aidFromUrl != null && aidFromUrl.length() > 8) {
				alias = "wallet-" + aidFromUrl.substring(0, 8);
				log.debug("Generated alias from AID: " + alias);
				WalletContact.setAlias(context, alias);
			}
		}

		if (alias == null || alias.trim().isEmpty()) {
			throw new IllegalArgumentException(
				"Could not determine alias. Please set WalletContact.Alias or use an OOBI with ?name= parameter"
			);
		}

		// Load constants
		String keriaUrl = getConstant("KERIAIntegration.KERIA_URL");
		String keriaBootUrl = getConstant("KERIAIntegration.KERIA_BOOT_URL");
		String controllerBran = getConstant("KERIAIntegration.KERIA_CONTROLLER_BRAN");
		String tierString = getConstant("KERIAIntegration.KERIA_SALTER_TIER");

		// Validate required constants
		validateConstant(keriaUrl, "KERIA_URL");
		validateConstant(keriaBootUrl, "KERIA_BOOT_URL");
		validateConstant(controllerBran, "KERIA_CONTROLLER_BRAN");

		// Parse tier
		Salter.Tier tier = parseTier(tierString);

		log.info("Resolving wallet OOBI for alias: " + alias);
		log.debug("Wallet OOBI: " + WalletOOBI);

		// Create SignifyClient and connect
		SignifyClient client = new SignifyClient(
			keriaUrl,
			controllerBran,
			tier,
			keriaBootUrl,
			null
		);

		// Connect to existing agent
		client.connect();
		log.debug("Connected to KERIA agent");

		// Resolve the wallet OOBI
		log.debug("Resolving OOBI...");
		Object resolveResult = client.oobis().resolve(WalletOOBI, alias);

		// Wait for the operation to complete
		Operation<?> operation = Operation.fromObject(resolveResult);
		client.operations().wait(operation);
		log.debug("OOBI resolution completed");

		// Extract the AID prefix from the response
		String aidPrefix = extractAidFromResponse(operation.getResponse(), log);

		// If response didn't contain AID, look up the contact that was created
		if (aidPrefix == null || aidPrefix.trim().isEmpty()) {
			log.debug("Response didn't contain AID, looking up contact by alias...");
			aidPrefix = getContactAidByAlias(client, alias, log);
		}

		// If still no AID, try to extract from the OOBI URL itself
		if (aidPrefix == null || aidPrefix.trim().isEmpty()) {
			log.debug("Contact lookup failed, extracting AID from OOBI URL...");
			aidPrefix = extractAidFromOobiUrl(WalletOOBI, log);
		}

		if (aidPrefix == null || aidPrefix.trim().isEmpty()) {
			throw new RuntimeException(
				"Failed to extract AID prefix from OOBI resolution. " +
				"Tried: response, contact lookup, and URL parsing."
			);
		}

		log.info("Resolved wallet AID: " + aidPrefix);

		// Populate the WalletContact entity
		WalletContact.setAIDPrefix(context, aidPrefix);
		WalletContact.setOOBI(context, WalletOOBI);
		WalletContact.setResolvedAt(context, new Date());

		// Optionally get and store key state (as JSON string)
		try {
			String keyState = getKeyState(client, aidPrefix, log);
			if (keyState != null) {
				WalletContact.setKeyState(context, keyState);
			}
		} catch (Exception e) {
			log.warn("Could not retrieve key state: " + e.getMessage());
			// Non-fatal - continue without key state
		}

		// Commit the changes
		Core.commit(context, WalletContact.getMendixObject());
		log.info("WalletContact saved successfully for alias: " + alias);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ResolveWalletOOBI";
	}

	// BEGIN EXTRA CODE
	/**
	 * Retrieves a Mendix constant value by its full name.
	 */
	private String getConstant(String constantName) {
		Object value = Core.getConfiguration().getConstantValue(constantName);
		return value != null ? value.toString() : null;
	}

	/**
	 * Validates that a constant has a non-empty value.
	 */
	private void validateConstant(String value, String constantName) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalStateException(
				"Required constant KERIAIntegration." + constantName + " is not configured"
			);
		}
	}

	/**
	 * Parses the tier string to a Salter.Tier enum value.
	 */
	private Salter.Tier parseTier(String tierString) {
		if (tierString == null || tierString.trim().isEmpty()) {
			return Salter.Tier.low;
		}
		return switch (tierString.toLowerCase().trim()) {
			case "low" -> Salter.Tier.low;
			case "med" -> Salter.Tier.med;
			case "high" -> Salter.Tier.high;
			default -> Salter.Tier.low;
		};
	}

	/**
	 * Extracts the AID prefix from the OOBI resolution response.
	 * The response typically contains an "i" field with the AID.
	 */
	@SuppressWarnings("unchecked")
	private String extractAidFromResponse(Object response, ILogNode log) {
		log.debug("OOBI resolution response type: " +
			(response != null ? response.getClass().getName() : "null"));
		log.debug("OOBI resolution response: " + response);

		if (response instanceof LinkedHashMap) {
			LinkedHashMap<String, Object> responseMap = (LinkedHashMap<String, Object>) response;
			log.debug("Response keys: " + responseMap.keySet());

			// The AID is typically in the "i" field
			Object aidObj = responseMap.get("i");
			if (aidObj != null) {
				return aidObj.toString();
			}

			// Fallback: try "id" or "prefix"
			aidObj = responseMap.get("id");
			if (aidObj != null) {
				return aidObj.toString();
			}

			aidObj = responseMap.get("prefix");
			if (aidObj != null) {
				return aidObj.toString();
			}
		}

		return null;
	}

	/**
	 * Retrieves the key state for an AID as a JSON string.
	 */
	private String getKeyState(SignifyClient client, String aidPrefix, ILogNode log) {
		try {
			// Get key state via the keyStates API
			Object keyState = client.keyStates().get(aidPrefix);
			if (keyState != null) {
				// Convert to JSON string for storage
				return com.fasterxml.jackson.databind.ObjectMapper
					.class.getDeclaredConstructor().newInstance()
					.writeValueAsString(keyState);
			}
		} catch (Exception e) {
			log.debug("Could not retrieve key state for " + aidPrefix + ": " + e.getMessage());
		}
		return null;
	}

	/**
	 * Looks up a contact by alias and returns its AID.
	 */
	private String getContactAidByAlias(SignifyClient client, String alias, ILogNode log) {
		try {
			// Filter contacts by alias using regex
			org.cardanofoundation.signify.app.Contacting.Contact[] contacts =
				client.contacts().list(null, "alias", "^" + alias + "$");

			if (contacts != null && contacts.length > 0) {
				String id = contacts[0].getId();
				log.debug("Found contact with alias '" + alias + "', AID: " + id);
				return id;
			}
			log.debug("No contact found with alias: " + alias);
		} catch (Exception e) {
			log.debug("Error looking up contact by alias: " + e.getMessage());
		}
		return null;
	}

	/**
	 * Extracts the alias/name from an OOBI URL query parameter.
	 * Looks for ?name=... or &name=... in the URL.
	 */
	private String extractAliasFromOobiUrl(String oobiUrl) {
		try {
			// Look for name= parameter
			String searchFor = "name=";
			int startIdx = oobiUrl.indexOf("?" + searchFor);
			if (startIdx < 0) {
				startIdx = oobiUrl.indexOf("&" + searchFor);
			}
			if (startIdx >= 0) {
				startIdx += searchFor.length() + 1; // +1 for ? or &
				int endIdx = oobiUrl.indexOf("&", startIdx);
				if (endIdx < 0) {
					endIdx = oobiUrl.length();
				}
				String name = oobiUrl.substring(startIdx, endIdx);
				// URL decode if needed
				return java.net.URLDecoder.decode(name, java.nio.charset.StandardCharsets.UTF_8);
			}
		} catch (Exception e) {
			// Ignore errors, return null
		}
		return null;
	}

	/**
	 * Extracts the AID from an OOBI URL.
	 * OOBI format: http://host:port/oobi/{AID}/agent/{agentAID}?name=...
	 */
	private String extractAidFromOobiUrl(String oobiUrl, ILogNode log) {
		try {
			// Look for /oobi/{AID}/ pattern
			String marker = "/oobi/";
			int startIdx = oobiUrl.indexOf(marker);
			if (startIdx >= 0) {
				startIdx += marker.length();
				int endIdx = oobiUrl.indexOf("/", startIdx);
				if (endIdx < 0) {
					endIdx = oobiUrl.indexOf("?", startIdx);
				}
				if (endIdx < 0) {
					endIdx = oobiUrl.length();
				}
				String aid = oobiUrl.substring(startIdx, endIdx);
				log.debug("Extracted AID from OOBI URL: " + aid);
				return aid;
			}
		} catch (Exception e) {
			log.debug("Error extracting AID from OOBI URL: " + e.getMessage());
		}
		return null;
	}
	// END EXTRA CODE
}
