// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.app.Exchanging;
import org.cardanofoundation.signify.cesr.Saider;
import org.cardanofoundation.signify.cesr.Salter;
import org.cardanofoundation.signify.cesr.Serder;
import org.cardanofoundation.signify.core.States.HabState;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_RequestCredentialSignature extends UserAction<java.lang.String>
{
	/** @deprecated use Chief.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Chief;
	private final keriaintegration.proxies.WalletContact Chief;
	/** @deprecated use Representative.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Representative;
	private final keriaintegration.proxies.WalletContact Representative;
	/** @deprecated use CredentialRegistry.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CredentialRegistry;
	private final keriaintegration.proxies.CredentialRegistry CredentialRegistry;
	private final java.lang.String CredentialSubjectJSON;
	/** @deprecated use IssuedCredential.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __IssuedCredential;
	private final keriaintegration.proxies.IssuedCredential IssuedCredential;

	public JA_RequestCredentialSignature(
		IContext context,
		IMendixObject _chief,
		IMendixObject _representative,
		IMendixObject _credentialRegistry,
		java.lang.String _credentialSubjectJSON,
		IMendixObject _issuedCredential
	)
	{
		super(context);
		this.__Chief = _chief;
		this.Chief = _chief == null ? null : keriaintegration.proxies.WalletContact.initialize(getContext(), _chief);
		this.__Representative = _representative;
		this.Representative = _representative == null ? null : keriaintegration.proxies.WalletContact.initialize(getContext(), _representative);
		this.__CredentialRegistry = _credentialRegistry;
		this.CredentialRegistry = _credentialRegistry == null ? null : keriaintegration.proxies.CredentialRegistry.initialize(getContext(), _credentialRegistry);
		this.CredentialSubjectJSON = _credentialSubjectJSON;
		this.__IssuedCredential = _issuedCredential;
		this.IssuedCredential = _issuedCredential == null ? null : keriaintegration.proxies.IssuedCredential.initialize(getContext(), _issuedCredential);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		ILogNode log = Core.getLogger("KERIAIntegration");

		// Validate inputs
		if (Chief == null) {
			throw new IllegalArgumentException("Chief is required - the Chief signs the credential");
		}
		if (Representative == null) {
			throw new IllegalArgumentException("Representative is required - the credential holder");
		}
		if (CredentialRegistry == null) {
			throw new IllegalArgumentException("CredentialRegistry is required");
		}
		if (CredentialSubjectJSON == null || CredentialSubjectJSON.trim().isEmpty()) {
			throw new IllegalArgumentException("CredentialSubjectJSON is required");
		}
		if (IssuedCredential == null) {
			throw new IllegalArgumentException("IssuedCredential is required");
		}

		// Get required data from entities
		String chiefPrefix = Chief.getAIDPrefix(context);
		String representativePrefix = Representative.getAIDPrefix(context);
		String registryId = CredentialRegistry.getRegistryID(context);
		String backendAlias = CredentialRegistry.getIdentifierAlias(context);

		if (chiefPrefix == null || chiefPrefix.trim().isEmpty()) {
			throw new IllegalArgumentException("Chief has no AIDPrefix set");
		}
		if (representativePrefix == null || representativePrefix.trim().isEmpty()) {
			throw new IllegalArgumentException("Representative has no AIDPrefix set");
		}
		if (registryId == null || registryId.trim().isEmpty()) {
			throw new IllegalArgumentException("CredentialRegistry has no RegistryID set");
		}
		if (backendAlias == null || backendAlias.trim().isEmpty()) {
			throw new IllegalArgumentException("CredentialRegistry has no IdentifierAlias set");
		}

		log.info("Requesting credential signature from Chief: " + chiefPrefix);
		log.info("Credential will be issued to Representative: " + representativePrefix);

		// Load constants
		String keriaUrl = getConstant("KERIAIntegration.KERIA_URL");
		String keriaBootUrl = getConstant("KERIAIntegration.KERIA_BOOT_URL");
		String controllerBran = getConstant("KERIAIntegration.KERIA_CONTROLLER_BRAN");
		String tierString = getConstant("KERIAIntegration.KERIA_SALTER_TIER");
		String qviSchemaSaid = getConstant("KERIAIntegration.QVI_SCHEMA_SAID");

		validateConstant(keriaUrl, "KERIA_URL");
		validateConstant(keriaBootUrl, "KERIA_BOOT_URL");
		validateConstant(controllerBran, "KERIA_CONTROLLER_BRAN");
		validateConstant(qviSchemaSaid, "QVI_SCHEMA_SAID");

		Salter.Tier tier = parseTier(tierString);

		// Parse credential subject JSON into map
		Map<String, Object> subjectData = new LinkedHashMap<>();
		ObjectMapper mapper = new ObjectMapper();
		@SuppressWarnings("unchecked")
		Map<String, Object> parsed = mapper.readValue(CredentialSubjectJSON, Map.class);
		subjectData.putAll(parsed);

		// Connect to KERIA
		SignifyClient client = new SignifyClient(keriaUrl, controllerBran, tier, keriaBootUrl, null);
		client.connect();
		log.debug("Connected to KERIA agent");

		// Get the backend's HabState (for sending the exchange)
		HabState senderState = client.identifiers().get(backendAlias)
			.orElseThrow(() -> new RuntimeException("Backend identity not found: " + backendAlias));
		log.debug("Retrieved backend HabState for: " + backendAlias);

		// Build ACDC credential structure for Chief to sign
		// Credential subject (a): {d, i, dt, ...custom fields}
		String dt = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSSSS'+00:00'")
			.withZone(ZoneOffset.UTC)
			.format(Instant.now());

		Map<String, Object> credentialSubject = new LinkedHashMap<>();
		credentialSubject.put("d", "");  // Subject SAID placeholder
		credentialSubject.put("i", representativePrefix);  // Holder (Representative)
		credentialSubject.put("dt", dt);  // Issuance datetime
		credentialSubject.putAll(subjectData);  // Custom claim attributes

		// SAIDify the credential subject
		Saider.SaidifyResult subjectSaidResult = Saider.saidify(credentialSubject);
		Map<String, Object> saidifiedSubject = subjectSaidResult.sad();

		// Build complete ACDC credential structure
		// v: ACDC version, d: SAID, i: issuer, ri: registry, s: schema, a: attributes
		Map<String, Object> credential = new LinkedHashMap<>();
		credential.put("v", "ACDC10JSON000000_");  // ACDC version string
		credential.put("d", "");  // Credential SAID placeholder
		credential.put("i", chiefPrefix);  // Issuer (Chief's AID)
		credential.put("ri", registryId);  // Registry ID
		credential.put("s", qviSchemaSaid);  // Schema SAID
		credential.put("a", saidifiedSubject);  // Credential subject

		// SAIDify the complete credential
		Saider.SaidifyResult credentialSaidResult = Saider.saidify(credential);
		Map<String, Object> saidifiedCredential = credentialSaidResult.sad();

		log.info("Built ACDC credential structure:");
		log.info("  Issuer (i): " + chiefPrefix);
		log.info("  Holder (a.i): " + representativePrefix);
		log.info("  Schema (s): " + qviSchemaSaid);
		log.info("  Registry (ri): " + registryId);
		log.info("  Credential SAID: " + saidifiedCredential.get("d"));

		// Use the same route as challenge signing — wallet only shows known routes
		// Correlation via SAID matching distinguishes credential vs challenge requests
		String route = "/remotesign/ixn/req";

		// Create payload wrapper for the credential
		Map<String, Object> payload = new LinkedHashMap<>();
		payload.put("d", "");  // Payload SAID placeholder
		payload.put("credential", saidifiedCredential);  // The full ACDC structure
		payload.put("description", "Please sign this credential to issue it to " +
			representativePrefix);

		// SAIDify the payload
		Saider.SaidifyResult payloadSaidResult = Saider.saidify(payload);
		Map<String, Object> saidifiedPayload = payloadSaidResult.sad();

		log.debug("Saidified payload: " + saidifiedPayload);

		Map<String, List<Object>> embeds = new LinkedHashMap<>();

		// Create the exchange message
		Exchanging.Exchanges exchanges = client.exchanges();
		Exchanging.ExchangeMessageResult result = exchanges.createExchangeMessage(
			senderState,
			route,
			saidifiedPayload,
			embeds,
			chiefPrefix,  // Send to Chief's wallet
			null,  // datetime - use default
			null   // dig - no digest
		);

		Serder exn = result.exn();
		List<String> sigs = result.sigs();
		String atc = result.atc();

		// Log the exchange message for debugging
		log.info("=== CREDENTIAL SIGNING REQUEST ===");
		log.info("Route (r): " + exn.getKed().get("r"));
		log.info("Recipient (rp): " + exn.getKed().get("rp"));
		log.info("Sender (i): " + exn.getKed().get("i"));
		log.info("Request SAID (d): " + exn.getKed().get("d"));
		log.info("==================================");

		// Send the exchange message
		Object sendResult = exchanges.sendFromEvents(
			backendAlias,
			"credential-signing",  // topic
			exn,
			sigs,
			atc,
			List.of(chiefPrefix)  // Recipients
		);

		log.info("Send result: " + sendResult);

		// Extract the request SAID for correlation
		String requestSaid = (String) exn.getKed().get("d");
		String credentialSaid = (String) saidifiedCredential.get("d");

		// Populate IssuedCredential entity
		IssuedCredential.setCredentialID(context, credentialSaid);
		IssuedCredential.setSchemaSAID(context, qviSchemaSaid);
		IssuedCredential.setHolderAIDPrefix(context, representativePrefix);
		IssuedCredential.setIssuerAIDPrefix(context, chiefPrefix);
		IssuedCredential.setAuthorizedByAIDPrefix(context, chiefPrefix);
		IssuedCredential.setRequestSAID(context, requestSaid);
		IssuedCredential.setCredentialData(context, CredentialSubjectJSON);
		IssuedCredential.setStatus(context, keriaintegration.proxies.Enum_CredentialStatus.PendingSignature);
		IssuedCredential.setIssuedAt(context, new Date());
		IssuedCredential.setIssuedCredential_WalletContact_Receiver(context, Representative);
		IssuedCredential.setIssuedCredential_WalletContact_Issuer(context, Chief);
		IssuedCredential.setIssuedCredential_CredentialRegistry(context, CredentialRegistry);

		Core.commit(context, IssuedCredential.getMendixObject());
		log.info("IssuedCredential committed, credential SAID: " + credentialSaid);

		log.info("Credential signing request sent to Chief");
		log.info("Request SAID: " + requestSaid);
		log.info("Chief must approve in Veridian wallet");

		return requestSaid;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_RequestCredentialSignature";
	}

	// BEGIN EXTRA CODE
	/**
	 * Retrieves a Mendix constant value by its full name.
	 */
	private String getConstant(String constantName) {
		Object value = Core.getConfiguration().getConstantValue(constantName);
		return value != null ? value.toString() : null;
	}

	/**
	 * Validates that a constant has a non-empty value.
	 */
	private void validateConstant(String value, String constantName) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalStateException(
				"Required constant KERIAIntegration." + constantName + " is not configured"
			);
		}
	}

	/**
	 * Parses the tier string to a Salter.Tier enum value.
	 */
	private Salter.Tier parseTier(String tierString) {
		if (tierString == null || tierString.trim().isEmpty()) {
			return Salter.Tier.low;
		}
		String tier = tierString.toLowerCase().trim();
		switch (tier) {
			case "low":
				return Salter.Tier.low;
			case "med":
				return Salter.Tier.med;
			case "high":
				return Salter.Tier.high;
			default:
				return Salter.Tier.low;
		}
	}
	// END EXTRA CODE
}
