// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.app.Exchanging;
import org.cardanofoundation.signify.cesr.Saider;
import org.cardanofoundation.signify.cesr.Salter;
import org.cardanofoundation.signify.cesr.Serder;
import org.cardanofoundation.signify.core.States.HabState;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_SendChallenge extends UserAction<java.lang.String>
{
	/** @deprecated use BackendIdentity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __BackendIdentity;
	private final keriaintegration.proxies.BackendIdentity BackendIdentity;
	/** @deprecated use WalletContact.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __WalletContact;
	private final keriaintegration.proxies.WalletContact WalletContact;
	private final java.lang.String ChallengePayload;

	public JA_SendChallenge(
		IContext context,
		IMendixObject _backendIdentity,
		IMendixObject _walletContact,
		java.lang.String _challengePayload
	)
	{
		super(context);
		this.__BackendIdentity = _backendIdentity;
		this.BackendIdentity = _backendIdentity == null ? null : keriaintegration.proxies.BackendIdentity.initialize(getContext(), _backendIdentity);
		this.__WalletContact = _walletContact;
		this.WalletContact = _walletContact == null ? null : keriaintegration.proxies.WalletContact.initialize(getContext(), _walletContact);
		this.ChallengePayload = _challengePayload;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		ILogNode log = Core.getLogger("KERIAIntegration");

		// Validate inputs
		if (BackendIdentity == null) {
			throw new IllegalArgumentException("BackendIdentity is required");
		}
		if (WalletContact == null) {
			throw new IllegalArgumentException("WalletContact is required");
		}
		if (ChallengePayload == null || ChallengePayload.trim().isEmpty()) {
			throw new IllegalArgumentException("ChallengePayload is required");
		}

		// Get identity details
		String backendAlias = BackendIdentity.getIdentifierAlias(context);
		String walletAid = WalletContact.getAIDPrefix(context);

		log.info("Sending challenge from backend '" + backendAlias + "' to wallet AID: " + walletAid);
		log.debug("Challenge payload: " + ChallengePayload);

		// Load constants
		String keriaUrl = getConstant("KERIAIntegration.KERIA_URL");
		String keriaBootUrl = getConstant("KERIAIntegration.KERIA_BOOT_URL");
		String controllerBran = getConstant("KERIAIntegration.KERIA_CONTROLLER_BRAN");
		String tierString = getConstant("KERIAIntegration.KERIA_SALTER_TIER");

		// Validate required constants
		validateConstant(keriaUrl, "KERIA_URL");
		validateConstant(keriaBootUrl, "KERIA_BOOT_URL");
		validateConstant(controllerBran, "KERIA_CONTROLLER_BRAN");

		// Parse tier
		Salter.Tier tier = parseTier(tierString);

		// Create SignifyClient and connect
		SignifyClient client = new SignifyClient(
			keriaUrl,
			controllerBran,
			tier,
			keriaBootUrl,
			null
		);
		client.connect();
		log.debug("Connected to KERIA agent");

		// Get the backend's HabState
		HabState senderState = client.identifiers().get(backendAlias)
			.orElseThrow(() -> new RuntimeException("Backend identity not found: " + backendAlias));
		log.debug("Retrieved backend HabState for: " + backendAlias);

		// Veridian wallet expects notifications with route: /exn/remotesign/ixn/req
		// When creating exchange, we use the route WITHOUT /exn prefix
		// KERIA adds the /exn prefix in the notification
		String route = "/remotesign/ixn/req";

		// CRITICAL: The payload MUST be saidified (have a 'd' field with valid hash)
		// The Veridian wallet validates this and silently discards invalid payloads
		Map<String, Object> payload = new LinkedHashMap<>();
		payload.put("d", "");  // Placeholder for SAID
		payload.put("payload", ChallengePayload);

		// Saidify the payload - this computes the hash and sets the 'd' field
		Saider.SaidifyResult saidResult = Saider.saidify(payload);
		Map<String, Object> saidifiedPayload = saidResult.sad();
		log.debug("Saidified payload: " + saidifiedPayload);

		Map<String, List<Object>> embeds = new LinkedHashMap<>();

		// Create the exchange message
		Exchanging.Exchanges exchanges = client.exchanges();
		Exchanging.ExchangeMessageResult result = exchanges.createExchangeMessage(
			senderState,
			route,
			saidifiedPayload,
			embeds,
			walletAid,
			null,  // datetime - use default
			null   // dig - no digest
		);

		Serder exn = result.exn();
		List<String> sigs = result.sigs();
		String atc = result.atc();

		// Log the exchange message for debugging
		log.info("=== EXCHANGE MESSAGE DEBUG ===");
		log.info("Route (r): " + exn.getKed().get("r"));
		log.info("Recipient (rp): " + exn.getKed().get("rp"));
		log.info("Sender (i): " + exn.getKed().get("i"));
		log.info("==============================");

		// Send the exchange message
		Object sendResult = exchanges.sendFromEvents(
			backendAlias,
			"remotesign",  // topic
			exn,
			sigs,
			atc,
			List.of(walletAid)
		);

		log.info("Send result: " + sendResult);

		// Extract and return the SAID
		String said = (String) exn.getKed().get("d");
		log.info("Challenge sent with SAID: " + said);

		return said;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_SendChallenge";
	}

	// BEGIN EXTRA CODE
	/**
	 * Retrieves a Mendix constant value by its full name.
	 */
	private String getConstant(String constantName) {
		Object value = Core.getConfiguration().getConstantValue(constantName);
		return value != null ? value.toString() : null;
	}

	/**
	 * Validates that a constant has a non-empty value.
	 */
	private void validateConstant(String value, String constantName) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalStateException(
				"Required constant KERIAIntegration." + constantName + " is not configured"
			);
		}
	}

	/**
	 * Parses the tier string to a Salter.Tier enum value.
	 */
	private Salter.Tier parseTier(String tierString) {
		if (tierString == null || tierString.trim().isEmpty()) {
			return Salter.Tier.low;
		}
		return switch (tierString.toLowerCase().trim()) {
			case "low" -> Salter.Tier.low;
			case "med" -> Salter.Tier.med;
			case "high" -> Salter.Tier.high;
			default -> Salter.Tier.low;
		};
	}
	// END EXTRA CODE
}
