// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package keriaintegration.actions;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.cardanofoundation.signify.app.clienting.SignifyClient;
import org.cardanofoundation.signify.app.Notifying;
import org.cardanofoundation.signify.cesr.Salter;
import org.cardanofoundation.signify.cesr.util.Utils;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_VerifyChallengeResponse extends UserAction<java.lang.Boolean>
{
	private final java.lang.String ChallengeSAID;

	public JA_VerifyChallengeResponse(
		IContext context,
		java.lang.String _challengeSAID
	)
	{
		super(context);
		this.ChallengeSAID = _challengeSAID;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode log = Core.getLogger("KERIAIntegration");

		// ChallengeSAID is the SAID of the original challenge exchange we sent
		if (ChallengeSAID == null || ChallengeSAID.trim().isEmpty()) {
			throw new IllegalArgumentException("ChallengeSAID is required");
		}

		log.info("Checking for challenge response to SAID: " + ChallengeSAID);

		// Load constants
		String keriaUrl = getConstant("KERIAIntegration.KERIA_URL");
		String keriaBootUrl = getConstant("KERIAIntegration.KERIA_BOOT_URL");
		String controllerBran = getConstant("KERIAIntegration.KERIA_CONTROLLER_BRAN");
		String tierString = getConstant("KERIAIntegration.KERIA_SALTER_TIER");

		// Validate required constants
		validateConstant(keriaUrl, "KERIA_URL");
		validateConstant(keriaBootUrl, "KERIA_BOOT_URL");
		validateConstant(controllerBran, "KERIA_CONTROLLER_BRAN");

		// Parse tier
		Salter.Tier tier = parseTier(tierString);

		// Create SignifyClient and connect
		SignifyClient client = new SignifyClient(
			keriaUrl,
			controllerBran,
			tier,
			keriaBootUrl,
			null
		);
		client.connect();
		log.debug("Connected to KERIA agent");

		// Get notifications
		Notifying.Notifications notifications = client.notifications();
		Notifying.Notifications.NotificationListResponse notifResponse = notifications.list(0, 1000);

		log.info("Retrieved " + notifResponse.total() + " notifications");

		// Parse notifications JSON
		String notesJson = notifResponse.notes();
		if (notesJson == null || notesJson.isEmpty() || notesJson.equals("[]")) {
			log.info("No notifications found");
			return false;
		}

		// Parse the notifications array
		List<Map<String, Object>> notesList = Utils.fromJson(notesJson, List.class);

		// Look for a remotesign reference notification.
		// The wallet responds with route /exn/remotesign/ixn/ref.
		// Notification structure: top-level 'r' is read status (boolean),
		// the actual route is at a.r, and a.d is the exchange SAID.
		// To match request→response: compare request exn.d with response exn.p.
		for (Map<String, Object> note : notesList) {
			Object aObj = note.get("a");
			if (!(aObj instanceof Map)) {
				continue;
			}

			@SuppressWarnings("unchecked")
			Map<String, Object> attrs = (Map<String, Object>) aObj;

			// The route is inside the attributes (a.r), not top-level
			Object attrRoute = attrs.get("r");
			String route = attrRoute != null ? attrRoute.toString() : "";

			if (!route.contains("/remotesign/ixn/ref")) {
				continue;
			}

			log.info("Found remotesign ref notification: route=" + route + " a=" + attrs);

			// Get the exchange SAID from a.d and look up the full exchange
			Object exchangeSaidObj = attrs.get("d");
			if (exchangeSaidObj == null) {
				log.debug("Notification has no a.d field, skipping");
				continue;
			}

			String exchangeSaid = exchangeSaidObj.toString();
			try {
				Object exnResultObj = client.exchanges().get(exchangeSaid);

				// Handle Optional wrapper if present
				Object exnResult = null;
				if (exnResultObj instanceof Optional) {
					Optional<?> optResult = (Optional<?>) exnResultObj;
					exnResult = optResult.orElse(null);
				} else {
					exnResult = exnResultObj;
				}

				if (exnResult == null) {
					log.debug("Exchange not found for SAID: " + exchangeSaid);
					continue;
				}

				log.info("Exchange result type: " + exnResult.getClass().getName());
				log.info("Exchange result: " + exnResult);

				if (exnResult instanceof Map) {
					@SuppressWarnings("unchecked")
					Map<String, Object> resultMap = (Map<String, Object>) exnResult;

					// The exchange result is nested: {exn: {...}, pathed: {...}}
					// The actual exchange data is inside the "exn" key
					Object exnObj = resultMap.get("exn");
					@SuppressWarnings("unchecked")
					Map<String, Object> exn = (exnObj instanceof Map)
						? (Map<String, Object>) exnObj : resultMap;

					// Match: response exn.p should equal our request's SAID (ChallengeSAID)
					Object exnPrior = exn.get("p");
					log.info("Exchange p=" + exnPrior + " (looking for " + ChallengeSAID + ")");

					if (exnPrior != null && ChallengeSAID.equals(exnPrior.toString())) {
						log.info("Found matching challenge response!");

						// Extract the KEL sequence number from exn.a.sn
						Object exnAttrs = exn.get("a");
						if (exnAttrs instanceof Map) {
							@SuppressWarnings("unchecked")
							Map<String, Object> exnA = (Map<String, Object>) exnAttrs;
							Object sn = exnA.get("sn");
							log.info("KEL sequence number (sn): " + sn);
						}

						// Mark notification as read
						Object noteSaid = note.get("i");
						if (noteSaid != null) {
							try {
								notifications.mark(noteSaid.toString());
								log.debug("Marked notification as read: " + noteSaid);
							} catch (Exception e) {
								log.warn("Could not mark notification as read: " + e.getMessage());
							}
						}

						log.info("Challenge response verified successfully");
						return true;
					}
				}
			} catch (Exception e) {
				log.warn("Could not lookup exchange " + exchangeSaid + ": " + e.getMessage());
			}
		}

		log.info("No matching challenge response found yet");
		return false;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_VerifyChallengeResponse";
	}

	// BEGIN EXTRA CODE
	/**
	 * Retrieves a Mendix constant value by its full name.
	 */
	private String getConstant(String constantName) {
		Object value = Core.getConfiguration().getConstantValue(constantName);
		return value != null ? value.toString() : null;
	}

	/**
	 * Validates that a constant has a non-empty value.
	 */
	private void validateConstant(String value, String constantName) {
		if (value == null || value.trim().isEmpty()) {
			throw new IllegalStateException(
				"Required constant KERIAIntegration." + constantName + " is not configured"
			);
		}
	}

	/**
	 * Parses the tier string to a Salter.Tier enum value.
	 */
	private Salter.Tier parseTier(String tierString) {
		if (tierString == null || tierString.trim().isEmpty()) {
			return Salter.Tier.low;
		}
		return switch (tierString.toLowerCase().trim()) {
			case "low" -> Salter.Tier.low;
			case "med" -> Salter.Tier.med;
			case "high" -> Salter.Tier.high;
			default -> Salter.Tier.low;
		};
	}
	// END EXTRA CODE
}
