// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import cardanowallet.Utils;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # Java Action: ConvertPublicAddressToHex
 * 
 * ## Introduction
 * 
 * The `ConvertPublicAddressToHex` Java action converts a public address into a hexadecimal string.
 * 
 * ## Parameters
 * 
 * The `ConvertPublicAddressToHex` action has the following parameter:
 * 
 * ### PublicAddress
 * 
 * The `PublicAddress` parameter is of type `CodeActions$BasicParameterType`. This parameter is used to pass the public address that needs to be converted to a hexadecimal string. 
 * 
 * **Note:** The description for this parameter is not provided.
 * 
 * ## Return Type
 * 
 * The `ConvertPublicAddressToHex` action returns a hexadecimal string representation of the provided public address.
 * 
 * ## Exceptions
 * 
 * The `ConvertPublicAddressToHex` action throws an exception if the provided public address is null or if the conversion to a hexadecimal string fails for any reason.
 * 
 * ## Usage
 * 
 * To use the `ConvertPublicAddressToHex` action, you need to pass a valid public address as the `PublicAddress` parameter. The action will return the hexadecimal string representation of the provided public address.
 * 
 * Example:
 * 
 * ```java
 * String publicAddress = "your public address here";
 * String hexAddress = ConvertPublicAddressToHex(publicAddress);
 * ```
 * 
 * In the above example, `hexAddress` will hold the hexadecimal string representation of the `publicAddress`.
 */
public class ConvertPublicAddressToHex extends UserAction<java.lang.String>
{
	private final java.lang.String PublicAddress;

	public ConvertPublicAddressToHex(
		IContext context,
		java.lang.String _publicAddress
	)
	{
		super(context);
		this.PublicAddress = _publicAddress;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			String witnessAddressHex = Utils.ConvertPublicAddressToHex(this.PublicAddress);
			return witnessAddressHex;
		} catch (Exception e) {
			throw new Exception("Error converting public address to hex: " + e.getMessage());
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConvertPublicAddressToHex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
