// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.address.Address;
import com.bloxbean.cardano.client.util.HexUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import cardanowallet.Utils;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # Java Action: ConvertHexToBech32
 * 
 * ## Introduction
 * 
 * The `ConvertHexToBech32` is a Java action in Mendix. This action is designed to convert a hexadecimal string to Bech32 format.
 * 
 * ## Parameters
 * 
 * The `ConvertHexToBech32` action has one parameter:
 * 
 * ### HexString
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter represents the hexadecimal string that will be converted to Bech32 format. The description for this parameter is not provided.
 * 
 * ## Return Type
 * 
 * The `ConvertHexToBech32` action returns a string in Bech32 format.
 * 
 * ## Exceptions
 * 
 * The `ConvertHexToBech32` action may throw an exception if the input hexadecimal string is not valid.
 * 
 * ## Usage
 * 
 * To use the `ConvertHexToBech32` action, you need to pass a valid hexadecimal string to the `HexString` parameter. The action will then return the converted Bech32 string.
 * 
 * ## Example
 * 
 * ```java
 * String hexString = "68656c6c6f";
 * String bech32String = ConvertHexToBech32(hexString);
 * System.out.println(bech32String);
 * ```
 * 
 * In this example, the hexadecimal string "68656c6c6f" (which represents the string "hello" in ASCII) is converted to Bech32 format. The converted Bech32 string is then printed to the console.
 */
public class ConvertHexToBech32 extends UserAction<java.lang.String>
{
	private final java.lang.String HexString;

	public ConvertHexToBech32(
		IContext context,
		java.lang.String _hexString
	)
	{
		super(context);
		this.HexString = _hexString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			if (this.HexString == null || this.HexString.isEmpty()) {
				throw new Exception("Hex string is empty");
			}
			Address address = new Address(HexUtil.decodeHexString(this.HexString));
			return address.toBech32();
		} catch (Exception e) {
			throw new Exception("Error converting hex to bech32: " + e.getMessage());
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConvertHexToBech32";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
