// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.common.cbor.CborSerializationUtil;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # Java Action: DecodeCborToJSON
 * 
 * ## Introduction
 * 
 * The `DecodeCborToJSON` Java action is designed to convert a CBOR (Concise Binary Object Representation) hex string into a JSON (JavaScript Object Notation) format.
 * 
 * ## Parameters
 * 
 * The `DecodeCborToJSON` action requires the following parameter:
 * 
 * ### CBORHexString
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter represents the CBOR hex string that needs to be converted to JSON. The CBOR hex string is a compact and efficient binary format for data serialization. 
 * 
 * ## Usage
 * 
 * To use the `DecodeCborToJSON` action, you need to pass the `CBORHexString` parameter which is the CBOR data that you want to convert into JSON format.
 * 
 * ## Output
 * 
 * The `DecodeCborToJSON` action returns a JSON string which is the equivalent representation of the input CBOR hex string.
 * 
 * ## Example
 * 
 * Here is a basic example of how to use the `DecodeCborToJSON` action:
 * 
 * ```java
 * String cborHexString = "BF61610161629F0203FFFF"; // Sample CBOR hex string
 * String json = DecodeCborToJSON(cborHexString); // Convert CBOR to JSON
 * ```
 * 
 * In this example, the `DecodeCborToJSON` action converts the provided `cborHexString` into a JSON string and stores the result in the `json` variable.
 */
public class DecodeCborToJSON extends UserAction<java.lang.String>
{
	private final java.lang.String CBORHexString;

	public DecodeCborToJSON(
		IContext context,
		java.lang.String _cBORHexString
	)
	{
		super(context);
		this.CBORHexString = _cBORHexString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		final ILogNode LOG = Core.getLogger("CardanoWallet");

		try {
			byte[] cborData = hexStringToByteArray(CBORHexString);
			return Transaction.deserialize(cborData).toJson();
        } catch (Exception e) {
            throw new RuntimeException("Error decoding CBOR data", e);
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DecodeCborToJSON";
	}

	// BEGIN EXTRA CODE
	private byte[] hexStringToByteArray(String s) {
        int len = s.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4)
                                + Character.digit(s.charAt(i + 1), 16));
        }
        return data;
    }
	// END EXTRA CODE
}
