// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.function.Output;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.cip.cip20.MessageMetadata;
import com.bloxbean.cardano.client.function.helper.AuxDataProviders;
import com.bloxbean.cardano.client.function.helper.BalanceTxBuilders;
import com.bloxbean.cardano.client.function.helper.InputBuilders;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import static com.bloxbean.cardano.client.common.CardanoConstants.LOVELACE;
import com.bloxbean.cardano.client.quicktx.*;
import java.util.ArrayList;
import java.util.List;
import static com.bloxbean.cardano.client.common.ADAConversionUtil.adaToLovelace;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import cardanowallet.proxies.Mnemonic_word;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_Account_GenerateMnemonics Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_Account_GenerateMnemonics` Java action is a part of the Mendix application suite. This action is responsible for generating mnemonics for a given wallet on the Cardano network.
 * 
 * ## Parameters
 * 
 * The `JA_Account_GenerateMnemonics` action requires the following parameters:
 * 
 * ### Wallet
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter represents the wallet for which the mnemonics are to be generated. The specific details of the wallet, such as its ID or name, should be provided here.
 * 
 * ### CARDANONETWORK
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter represents the Cardano network where the wallet is located. This could be the main Cardano network or a test network.
 * 
 * ## Return Type
 * 
 * This action returns a list of mnemonics as a string. These mnemonics can be used for various purposes, such as recovering a wallet or transferring ownership.
 * 
 * ## Exceptions
 * 
 * This action may throw exceptions if the provided wallet does not exist on the specified Cardano network, or if there is a problem generating the mnemonics.
 * 
 * ## Usage
 * 
 * This action is typically used when a user wants to generate mnemonics for a wallet. The generated mnemonics can then be stored securely for future use.
 */
public class JA_Account_GenerateMnemonics extends UserAction<IMendixObject>
{
	/** @deprecated use Wallet.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Wallet;
	private final cardanowallet.proxies.WalletAPI Wallet;
	private final java.lang.String CARDANONETWORK;

	public JA_Account_GenerateMnemonics(
		IContext context,
		IMendixObject _wallet,
		java.lang.String _cARDANONETWORK
	)
	{
		super(context);
		this.__Wallet = _wallet;
		this.Wallet = _wallet == null ? null : cardanowallet.proxies.WalletAPI.initialize(getContext(), _wallet);
		this.CARDANONETWORK = _cARDANONETWORK;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		Network selectedNetwork;
		String networkString = this.Wallet.getCardanoNetwork().name();
		networkString =  networkString.length() > 0 ? networkString: "mainnet";
		if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
		} else if(networkString.equalsIgnoreCase("preview")) {
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
		}
		Account newAccount = new Account(selectedNetwork);
		String mnemonicSentence = newAccount.mnemonic();
		this.Wallet.setMnemonic(mnemonicSentence);
		this.Wallet.setBaseAddress(newAccount.baseAddress());
		this.Wallet.setStakeAddress(newAccount.stakeAddress());

		IMendixObject newObject = Core.instantiate(context, "CardanoWallet.Mnemonic_sentence");
		cardanowallet.proxies.Mnemonic_sentence mnemonicSentenceMx = cardanowallet.proxies.Mnemonic_sentence.initialize(context, newObject);
		mnemonicSentenceMx.setCompleteSentence(mnemonicSentence);
		mnemonicSentenceMx.setMnemonic_sentence_WalletAPI(this.Wallet);
		this.Wallet.setMnemonic_sentence_WalletAPI(mnemonicSentenceMx);

		
		String[] mnenomicArray = mnemonicSentence.split(" ");

		Integer index = 0;
		for(String mnemonicWord : mnenomicArray) {
			IMendixObject Mnemonic_wordMx = Core.instantiate(context, "CardanoWallet.Mnemonic_word");
			cardanowallet.proxies.Mnemonic_word mnemonicWordMx = cardanowallet.proxies.Mnemonic_word.initialize(context, Mnemonic_wordMx);
			index++;
			mnemonicWordMx.setOrder(index);
			mnemonicWordMx.setValue(mnemonicWord);
			mnemonicWordMx.setMnemonic_word_Mnemonic_sentence(mnemonicSentenceMx);
			mnemonicWordMx.setMnemonic_word_WalletAPI(this.Wallet);
		}

		return this.Wallet.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Account_GenerateMnemonics";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
