// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.bloxbean.cardano.client.backend.blockfrost.service.*;
import com.mendix.systemwideinterfaces.core.*;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_Account_CreateFromMnemonic Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_Account_CreateFromMnemonic` Java action is a function that allows you to create an account using a mnemonic and a network enumeration.
 * 
 * ## Parameters
 * 
 * The `JA_Account_CreateFromMnemonic` Java action requires the following parameters:
 * 
 * ### mnemonic
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The `mnemonic` parameter represents a mnemonic phrase that is used to generate a private key for an account. This is a secret series of words that allows you to recover your account. It is important to keep this information secure and private.
 * 
 * ### CardanoNetworkEnum
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The `CardanoNetworkEnum` parameter represents the specific Cardano network to which the account will be associated. This parameter helps to define the network where the account will be created and used.
 * 
 * ## Usage
 * 
 * To use the `JA_Account_CreateFromMnemonic` Java action, you need to provide the required parameters. The `mnemonic` parameter should be a valid mnemonic phrase, and the `CardanoNetworkEnum` should be a valid network enumeration value.
 * 
 * Please note that no default values are provided for these parameters, and they must be specified when calling the action.
 * 
 * ## Example
 * 
 * Here is an example of how to use the `JA_Account_CreateFromMnemonic` Java action:
 * 
 * ```java
 * // Define the mnemonic and network
 * String mnemonic = "your mnemonic phrase here";
 * String network = "CardanoNetworkEnum value here";
 * 
 * // Call the action
 * JA_Account_CreateFromMnemonic(mnemonic, network);
 * ```
 * 
 * Remember to replace `"your mnemonic phrase here"` and `"CardanoNetworkEnum value here"` with your actual mnemonic phrase and network enumeration value.
 */
public class JA_Account_CreateFromMnemonic extends UserAction<IMendixObject>
{
	private final java.lang.String mnemonic;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetworkEnum;

	public JA_Account_CreateFromMnemonic(
		IContext context,
		java.lang.String _mnemonic,
		java.lang.String _cardanoNetworkEnum
	)
	{
		super(context);
		this.mnemonic = _mnemonic;
		this.CardanoNetworkEnum = _cardanoNetworkEnum == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetworkEnum);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		Network selectedNetwork;
		String networkString = this.CardanoNetworkEnum.name();
		if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
		} else if(networkString.equalsIgnoreCase("preview")) {
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
		}
		// create object
		IMendixObject newObject = Core.instantiate(getContext(), "CardanoWallet.WalletAPI");
		cardanowallet.proxies.WalletAPI wallet = cardanowallet.proxies.WalletAPI.initialize(getContext(),newObject);

		Account newAccount = new Account(selectedNetwork, this.mnemonic);
		wallet.setBaseAddress(newAccount.baseAddress());
		wallet.setStakeAddress(newAccount.stakeAddress());

		return wallet.getMendixObject();

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Account_CreateFromMnemonic";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
