// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import static com.bloxbean.cardano.client.common.ADAConversionUtil.adaToLovelace;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.cip.cip20.MessageMetadata;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.function.Output;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.function.helper.AuxDataProviders;
import com.bloxbean.cardano.client.function.helper.BalanceTxBuilders;
import com.bloxbean.cardano.client.function.helper.InputBuilders;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.mendix.systemwideinterfaces.core.IContext;
import static com.bloxbean.cardano.client.common.CardanoConstants.LOVELACE;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_CardanoTransaction_UnSigned
 * 
 * This Java action, `JA_CardanoTransaction_UnSigned`, is used to create an unsigned transaction on the Cardano network.
 * 
 * ## Parameters
 * 
 * The `JA_CardanoTransaction_UnSigned` action has the following parameters:
 * 
 * ### SenderAddress
 * 
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter represents the address of the sender in the transaction. It is required to identify the source of the funds.
 * 
 * ### ReceiverAddress
 * 
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter represents the address of the receiver in the transaction. It is required to identify the destination of the funds.
 * 
 * ### AmountInAda
 * 
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter represents the amount of ADA (the native cryptocurrency of the Cardano network) to be transferred in the transaction.
 * 
 * ### CardanoNetwork
 * 
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter represents the specific Cardano network on which the transaction is to be made. This could be the mainnet or a testnet.
 * 
 * ### TransactionMetaData
 * 
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter represents any additional data or metadata to be included with the transaction. This could include information such as transaction purpose, comments, or any other relevant details.
 * 
 * ## Usage
 * 
 * To use this action, you need to provide values for all the parameters. The action will then create an unsigned transaction on the specified Cardano network, transferring the specified amount of ADA from the sender address to the receiver address, with the provided transaction metadata.
 */
public class JA_CardanoTransaction_UnSigned extends UserAction<java.lang.String>
{
	private final java.lang.String SenderAddress;
	private final java.lang.String ReceiverAddress;
	private final java.math.BigDecimal AmountInAda;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;
	private final java.lang.String TransactionMetaData;

	public JA_CardanoTransaction_UnSigned(
		IContext context,
		java.lang.String _senderAddress,
		java.lang.String _receiverAddress,
		java.math.BigDecimal _amountInAda,
		java.lang.String _cardanoNetwork,
		java.lang.String _transactionMetaData
	)
	{
		super(context);
		this.SenderAddress = _senderAddress;
		this.ReceiverAddress = _receiverAddress;
		this.AmountInAda = _amountInAda;
		this.CardanoNetwork = _cardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetwork);
		this.TransactionMetaData = _transactionMetaData;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		final ILogNode LOG = Core.getLogger("CardanoWallet");
		
		LOG.debug("Start Execution of JA_CardanoTransaction_UnSigned");

		String blockfrostUrl;
		Network selectedNetwork;

		String networkString = CardanoNetwork.name();
		if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
			blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
			blockfrostUrl = Constants.BLOCKFROST_TESTNET_URL;
		} else if(networkString.equalsIgnoreCase("preview")) {
			blockfrostUrl = Constants.BLOCKFROST_PREVIEW_URL;
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
			blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
		}

		String senderAddress = this.SenderAddress;
		String receiverAddress1 = this.ReceiverAddress;

		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
		
		Tx tx1 = new Tx()
                .payToAddress(receiverAddress1, Amount.ada(this.AmountInAda.doubleValue()))
                .attachMetadata(MessageMetadata.create().add("This is a test message 2"))
                .from(senderAddress);
		
		BFBackendService backendService =
				new BFBackendService(blockfrostUrl, bfProjectId);
		
        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
        
        return quickTxBuilder
        		.compose(tx1)
        		.feePayer(senderAddress)
        		.build()
        		.serializeToHex();
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CardanoTransaction_UnSigned";
	}

	// BEGIN EXTRA CODE
	
	// END EXTRA CODE
}
