// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import cardanowallet.EncryptDecryptMnemonic;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_DecryptMnemonic
 * 
 * ## Overview
 * 
 * The `JA_DecryptMnemonic` is a Java action designed to decrypt a given mnemonic using a passphrase.
 * 
 * ## Parameters
 * 
 * The `JA_DecryptMnemonic` action takes the following parameters:
 * 
 * ### EncryptedMnemonic
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter represents the encrypted mnemonic that needs to be decrypted. The encrypted mnemonic is a string of words that represent a secret cryptographic key in a human-readable format. This key is encrypted for security purposes and needs to be decrypted before it can be used.
 * 
 * ### Passphrase
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter represents the passphrase that will be used to decrypt the mnemonic. The passphrase is a string of characters that is used as a key to unlock the encrypted mnemonic. It is crucial to keep this passphrase secure as it can be used to decrypt the mnemonic and gain access to the secret cryptographic key.
 * 
 * ## Returns
 * 
 * The `JA_DecryptMnemonic` action returns the decrypted mnemonic as a string.
 * 
 * ## Exceptions
 * 
 * The `JA_DecryptMnemonic` action will throw an exception if the provided encrypted mnemonic or passphrase is invalid or if the decryption process fails for any reason.
 * 
 * ## Usage
 * 
 * To use the `JA_DecryptMnemonic` action, you need to pass in the encrypted mnemonic and the passphrase as parameters. The action will then return the decrypted mnemonic.
 * 
 * Please note that the security of the decrypted mnemonic depends on the security of the passphrase. Therefore, it is recommended to use a strong and secure passphrase.
 */
public class JA_DecryptMnemonic extends UserAction<java.lang.String>
{
	private final java.lang.String EncryptedMnemonic;
	private final java.lang.String Passphrase;

	public JA_DecryptMnemonic(
		IContext context,
		java.lang.String _encryptedMnemonic,
		java.lang.String _passphrase
	)
	{
		super(context);
		this.EncryptedMnemonic = _encryptedMnemonic;
		this.Passphrase = _passphrase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		EncryptDecryptMnemonic encryptDecryptMnemonic = new EncryptDecryptMnemonic();
		return encryptDecryptMnemonic.decrypt(this.EncryptedMnemonic, this.Passphrase);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_DecryptMnemonic";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
