// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import cardanowallet.EncryptDecryptMnemonic;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_EncryptMnemonic Java Action Documentation
 * 
 * ## Introduction
 * 
 * The JA_EncryptMnemonic is a Java action designed to encrypt a mnemonic using a passphrase. This action is part of the Mendix's CodeActions package.
 * 
 * ## Parameters
 * 
 * The JA_EncryptMnemonic action requires two parameters:
 * 
 * ### Mnemonic
 * 
 * - **Type:** CodeActions$BasicParameterType
 * - **Description:** This parameter represents the mnemonic that needs to be encrypted. A mnemonic is a secret sequence of words that represents a password or key. The mnemonic should be passed as a string.
 * 
 * ### Passphrase
 * 
 * - **Type:** CodeActions$BasicParameterType
 * - **Description:** This parameter represents the passphrase that will be used to encrypt the mnemonic. The passphrase should be passed as a string.
 * 
 * ## Usage
 * 
 * To use the JA_EncryptMnemonic action, you need to pass the required parameters (Mnemonic and Passphrase) in the specified format. The action will then return the encrypted mnemonic.
 * 
 * Please note that the descriptions for the parameters are not provided. For more detailed information about the parameters or the action, please refer to the Mendix's CodeActions package documentation or contact the package maintainer.
 */
public class JA_EncryptMnemonic extends UserAction<java.lang.String>
{
	private final java.lang.String Mnemonic;
	private final java.lang.String Passphrase;

	public JA_EncryptMnemonic(
		IContext context,
		java.lang.String _mnemonic,
		java.lang.String _passphrase
	)
	{
		super(context);
		this.Mnemonic = _mnemonic;
		this.Passphrase = _passphrase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		EncryptDecryptMnemonic encryptDecryptMnemonic = new EncryptDecryptMnemonic();
		return encryptDecryptMnemonic.encrypt(this.Mnemonic, this.Passphrase);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_EncryptMnemonic";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
