// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_GenerateAssetUnitId Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_GenerateAssetUnitId` is a Java action in Mendix that is designed to generate an asset unit ID based on the provided parameters.
 * 
 * ## Parameters
 * 
 * The `JA_GenerateAssetUnitId` action accepts two parameters:
 * 
 * ### AssetName
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter represents the name of the asset for which the unit ID is to be generated. The specific details of how this parameter is used within the action are not provided.
 * 
 * ### PolicyId
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter represents the ID of the policy associated with the asset. The specific details of how this parameter is used within the action are not provided.
 * 
 * ## Usage
 * 
 * To use the `JA_GenerateAssetUnitId` action, you need to provide values for both the `AssetName` and `PolicyId` parameters. The action will then generate a unique asset unit ID based on these inputs.
 * 
 * Please note that the specific details of how the `AssetName` and `PolicyId` parameters are used to generate the asset unit ID are not provided in the action's description. For more information, please refer to the action's implementation details or contact the action's developer.
 * 
 * ## Example
 * 
 * ```java
 * // Assuming you have assetName and policyId variables defined
 * String assetUnitId = JA_GenerateAssetUnitId(assetName, policyId);
 * ```
 * 
 * This will generate an asset unit ID based on the provided asset name and policy ID.
 */
public class JA_GenerateAssetUnitId extends UserAction<java.lang.String>
{
	private final java.lang.String AssetName;
	private final java.lang.String PolicyId;

	public JA_GenerateAssetUnitId(
		IContext context,
		java.lang.String _assetName,
		java.lang.String _policyId
	)
	{
		super(context);
		this.AssetName = _assetName;
		this.PolicyId = _policyId;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder AssetHex = new StringBuilder();
	    for (char ch : AssetName.toCharArray()) {
	        AssetHex.append(String.format("%02x", (int) ch));
	    }
	    return PolicyId + AssetHex.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GenerateAssetUnitId";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
