// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.util.HexUtil;
import com.bloxbean.cardano.client.util.Tuple;
import com.bloxbean.cardano.client.api.util.AssetUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_GetAssetName Java Action Documentation
 * 
 * ## Introduction
 * 
 * The `JA_GetAssetName` is a Java action in the Mendix platform. This action is used to retrieve the name of an asset based on the provided asset unit.
 * 
 * ## Parameters
 * 
 * This action has one parameter:
 * 
 * ### AssetUnit
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter represents the asset unit for which the name is to be retrieved. The specific details of the asset unit are not provided in the description.
 * 
 * ## Usage
 * 
 * To use this action, you need to pass the `AssetUnit` parameter. The `AssetUnit` should be of type `CodeActions$BasicParameterType`.
 * 
 * Here is an example of how to use the `JA_GetAssetName` action:
 * 
 * ```java
 * // Define the asset unit
 * CodeActions$BasicParameterType assetUnit = ...;
 * 
 * // Call the JA_GetAssetName action
 * String assetName = JA_GetAssetName(assetUnit);
 * 
 * // Now you can use the assetName
 * System.out.println("The name of the asset is: " + assetName);
 * ```
 * 
 * ## Output
 * 
 * The `JA_GetAssetName` action returns a string representing the name of the asset associated with the provided asset unit. If the asset unit does not have an associated name, the action will return null.
 * 
 * ## Error Handling
 * 
 * If the provided asset unit is null, the action will throw an `IllegalArgumentException`. Make sure to handle this exception in your code.
 * 
 * ## Conclusion
 * 
 * The `JA_GetAssetName` action is a useful tool for retrieving asset names in your Mendix applications. Make sure to provide a valid `AssetUnit` when calling this action.
 */
public class JA_GetAssetName extends UserAction<java.lang.String>
{
	private final java.lang.String AssetUnit;

	public JA_GetAssetName(
		IContext context,
		java.lang.String _assetUnit
	)
	{
		super(context);
		this.AssetUnit = _assetUnit;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        Tuple<String, String> policyIdAssetName = AssetUtil.getPolicyIdAndAssetName(this.AssetUnit);
        String assetName = new String( HexUtil.decodeHexString(policyIdAssetName._2));
        return assetName;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetAssetName";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
