// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.nio.charset.StandardCharsets;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.util.HexUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_HexToString Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_HexToString` Java action is designed to convert hexadecimal input into a string. 
 * 
 * ## Parameters
 * 
 * The `JA_HexToString` Java action requires the following parameter:
 * 
 * ### HexInput
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter is used to provide the hexadecimal input that you want to convert into a string. The parameter type is `CodeActions$BasicParameterType`, which means it accepts basic data types. No further description is provided.
 * 
 * ## Usage
 * 
 * To use the `JA_HexToString` Java action, you need to provide a hexadecimal input as a parameter. The action will then convert this input into a string.
 * 
 * Please note that the hexadecimal input should be provided in the `HexInput` parameter. The input should be a valid hexadecimal number.
 * 
 * ## Output
 * 
 * The output of the `JA_HexToString` Java action is a string that represents the provided hexadecimal input.
 * 
 * ## Error Handling
 * 
 * In case of any errors during the execution of the `JA_HexToString` Java action, an exception will be thrown. Please make sure to handle these exceptions properly in your application to prevent any unexpected behavior.
 * 
 * ## Example
 * 
 * Here is an example of how to use the `JA_HexToString` Java action:
 * 
 * ```java
 * try {
 *     String result = JA_HexToString("4A");
 *     System.out.println(result);
 * } catch (Exception e) {
 *     e.printStackTrace();
 * }
 * ```
 * 
 * In this example, the hexadecimal input "4A" is converted into a string. The result is then printed to the console. If there is an error during the execution of the action, the error message will be printed to the console.
 */
public class JA_HexToString extends UserAction<java.lang.String>
{
	private final java.lang.String HexInput;

	public JA_HexToString(
		IContext context,
		java.lang.String _hexInput
	)
	{
		super(context);
		this.HexInput = _hexInput;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        // Convert hex to bytes using Cardano Client Library
        byte[] bytes = HexUtil.decodeHexString(HexInput);

        // Convert byte array to a readable string
        return new String(bytes, StandardCharsets.UTF_8).trim();		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_HexToString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
