// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.transaction.spec.script.NativeScript;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import cardanowallet.Utils;
import cardanowallet.proxies.RecipientNP;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_MultiSig_Transaction_Build Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_MultiSig_Transaction_Build` is a Java action intended to build multi-signature transactions. 
 * 
 * ## Parameters
 * 
 * This action takes a single parameter:
 * 
 * ### Transaction
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter represents the transaction that needs to be processed. The specific details of the transaction are not provided in the description. 
 * 
 * ## Usage
 * 
 * To use the `JA_MultiSig_Transaction_Build` action, you need to provide the necessary transaction details as an argument of type `CodeActions$BasicParameterType`.
 * 
 * Please note that the specific implementation details of this action, such as the return type, any exceptions it might throw, or side effects it might have, are not provided in this documentation. For more detailed information, please refer to the source code or any additional documentation provided with the action.
 * 
 * ## Example
 * 
 * Here is a basic example of how you might call this action:
 * 
 * ```java
 * CodeActions$BasicParameterType transaction = ...; // Your transaction details here
 * JA_MultiSig_Transaction_Build(transaction);
 * ```
 * 
 * Please replace the `...` with your actual transaction details.
 */
public class JA_MultiSig_Transaction_Build extends UserAction<java.lang.String>
{
	/** @deprecated use Transaction.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Transaction;
	private final cardanowallet.proxies.TransactionNP Transaction;

	public JA_MultiSig_Transaction_Build(
		IContext context,
		IMendixObject _transaction
	)
	{
		super(context);
		this.__Transaction = _transaction;
		this.Transaction = _transaction == null ? null : cardanowallet.proxies.TransactionNP.initialize(getContext(), _transaction);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
	    Utils utils = new Utils(this.Transaction.getTransactionNP_Policy()
                .getCardanonetwork()
                .toString()
                .toLowerCase());

        // NativeScript from the JSON policy script
        NativeScript nativeScript = NativeScript.deserializeJson(
            this.Transaction.getTransactionNP_Policy().getScriptJSON()
        );

        // 2. Prepare the QuickTxBuilder. You need a valid TransactionProcessor instance.
        //    If your `utils` class does not provide one, you'll need to create your own or
        //    fetch it from wherever the code sets up the bloxbean backend.
        //    For example, if you have:
        //      TransactionProcessor transactionProcessor = 
        //          new DefaultTransactionProcessor(utils.getTransactionService());
        //    then do:
		BFBackendService backendService =
				new BFBackendService(utils.getBlockfrostUrl(), cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID());

        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);

        // 3. Create a script transaction, specifying the script address as the "sender"
        //    for balancing purposes. In native multi-sig, the script address can hold UTxOs,
        //    and the transaction must pay fees from that script address if you are spending them.
        String scriptAddress = this.Transaction.getTransactionNP_Policy().getAddress();
        
        Tx multiSigTx = new Tx()
        		.from(scriptAddress); // returns Tx, so you can chain if desired

        // 5) Add recipients
        List<IMendixObject> recipients = Core.retrieveByPath(
            getContext(),
            this.Transaction.getMendixObject(),
            RecipientNP.MemberNames.RecipientNP_TransactionNP.toString()
        );

        for (IMendixObject obj : recipients) {
            RecipientNP recipient = RecipientNP.initialize(getContext(), obj);
            multiSigTx.payToAddress(
                recipient.getAddress(),
                Amount.lovelace(BigInteger.valueOf(recipient.getAmountInLong()))
            );
        }

        // 6) Let’s account for how many signers you expect
        int witnessCount = this.Transaction
                .getTransactionNP_Policy()
                .getWitnessCount();

        // 7) Compose + attach the native script with a "preBalanceTx" lambda.
        //    That way, the library knows about the script in time for balancing.
        com.bloxbean.cardano.client.transaction.spec.Transaction unsignedTx = quickTxBuilder
            .compose(multiSigTx)
            .feePayer(scriptAddress)           // if same as ".from(...)" 
            .additionalSignersCount(witnessCount)
            .preBalanceTx((context, txn) -> {
                // Ensure the list is non-null, then add your native script
                if (txn.getWitnessSet().getNativeScripts() == null) {
                    txn.getWitnessSet().setNativeScripts(new ArrayList<>());
                }
                txn.getWitnessSet().getNativeScripts().add(nativeScript);
            })
            .build(); // build an unsigned transaction

        // 8) Serialize to hex CBOR for external signing
        return unsignedTx.serializeToHex();		
        
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_MultiSig_Transaction_Build";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("LandanoTest");
	// END EXTRA CODE
}
