// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.util.ArrayList;
import java.util.List;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.exception.CborDeserializationException;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.TransactionWitnessSet;
import com.bloxbean.cardano.client.transaction.spec.VkeyWitness;
import com.bloxbean.cardano.client.util.HexUtil;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import cardanowallet.Utils;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_MultiSig_Transaction_Submit Java Action Documentation
 * 
 * ## Overview
 * The `JA_MultiSig_Transaction_Submit` Java action is used to submit a multi-signature transaction in a Cardano network. 
 * 
 * ## Parameters
 * 
 * ### TxnSigningList
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter is used to pass the list of transaction signatures that are required for the multi-signature transaction. The specific format and structure of the list depend on the implementation details of the multi-signature transaction.
 * 
 * ### Txn
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter is used to pass the transaction that needs to be submitted. The transaction should be in a format that is compatible with the Cardano network.
 * 
 * ### CardanoNetwork
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter is used to specify the Cardano network where the transaction will be submitted. The value should be a valid identifier of a Cardano network.
 * 
 * ## Usage
 * To use the `JA_MultiSig_Transaction_Submit` action, you need to provide the `TxnSigningList`, `Txn`, and `CardanoNetwork` parameters. The action will then submit the transaction to the specified Cardano network.
 * 
 * Please note that the transaction submission might fail if the transaction is not valid, the signatures in the `TxnSigningList` are not sufficient, or the specified `CardanoNetwork` is not available. Therefore, you should always check the result of the action and handle any errors appropriately.
 * 
 * ## Example
 * Here is an example of how to use the `JA_MultiSig_Transaction_Submit` action:
 * 
 * ```java
 * List<String> txnSigningList = Arrays.asList("signature1", "signature2");
 * String txn = "transaction data";
 * String cardanoNetwork = "mainnet";
 * 
 * try {
 *     JA_MultiSig_Transaction_Submit(txnSigningList, txn, cardanoNetwork);
 * } catch (Exception e) {
 *     // Handle error
 * }
 * ```
 * 
 * In this example, the action is used to submit a transaction to the Cardano mainnet. The transaction is signed by two signatures, which are provided in the `txnSigningList`.
 */
public class JA_MultiSig_Transaction_Submit extends UserAction<java.lang.String>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(TxnSigningList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __TxnSigningList;
	private final java.util.List<cardanowallet.proxies.TransactionSigning> TxnSigningList;
	/** @deprecated use Txn.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Txn;
	private final cardanowallet.proxies.Transaction Txn;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;

	public JA_MultiSig_Transaction_Submit(
		IContext context,
		java.util.List<IMendixObject> _txnSigningList,
		IMendixObject _txn,
		java.lang.String _cardanoNetwork
	)
	{
		super(context);
		this.__TxnSigningList = _txnSigningList;
		this.TxnSigningList = java.util.Optional.ofNullable(_txnSigningList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(txnSigningListElement -> cardanowallet.proxies.TransactionSigning.initialize(getContext(), txnSigningListElement))
			.collect(java.util.stream.Collectors.toList());
		this.__Txn = _txn;
		this.Txn = _txn == null ? null : cardanowallet.proxies.Transaction.initialize(getContext(), _txn);
		this.CardanoNetwork = _cardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetwork);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        Transaction transaction = Transaction.deserialize(HexUtil.decodeHexString(this.Txn.getUnsignedCBOR()));
		var utils = new Utils(this.CardanoNetwork.getCaption());
		this.TxnSigningList.forEach(TxnSigningMx -> 
		{
			Transaction witnessSignedTxn;
			try {
				witnessSignedTxn = Transaction.deserialize(HexUtil.decodeHexString(TxnSigningMx.getSignedCBOR()));
				addWitness(transaction,witnessSignedTxn);
			} catch (CborDeserializationException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				LOG.error(e);
			}
		});
		
        Result<String> result = utils.backendService.getTransactionService().submitTransaction(transaction.serialize());
        LOG.info("MultiSig Transaction submitted");
        LOG.info(result);
        if(result.isSuccessful()) {
        	this.Txn.setSignedCbor(transaction.serializeToHex());
        	this.Txn.setTransactionId(result.getValue());
        	LOG.info("MultiSig Transaction submitted successfully "+ result.getValue());
        	utils.waitForTransactionHash(result); // we'll need a queuing system.
        } else {
        	LOG.error("Transaction failed");
        	LOG.error(result);
        	return "";
        }
        return result.getValue();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_MultiSig_Transaction_Submit";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger(cardanowallet.proxies.constants.Constants.getLogNodeName());
	
	/**
	 * Ensures the transaction has a witness set and appends a signing witness from another transaction.
	 *
	 * If the transaction does not have a witness set, it initializes and sets one.
	 *
	 * @param transaction The transaction to be assembled.
	 * @param witnessSignedTxn The transaction from which to pick the signing witness.
	 */
    public void addWitness(Transaction transaction, Transaction witnessSignedTxn) {
        TransactionWitnessSet witnessSet = transaction.getWitnessSet();
        List<VkeyWitness> vkeyWitnesses = witnessSet.getVkeyWitnesses();

        // Check if vkeyWitnesses is null and initialize if necessary
        if (vkeyWitnesses == null) {
            vkeyWitnesses = new ArrayList<>();
            witnessSet.setVkeyWitnesses(vkeyWitnesses);
        }

        // Add the witness
        vkeyWitnesses.add(witnessSignedTxn.getWitnessSet().getVkeyWitnesses().get(0));
    }

	// END EXTRA CODE
}
