// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.api.util.PolicyUtil;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.cip.cip25.NFT;
import com.bloxbean.cardano.client.cip.cip25.NFTFile;
import com.bloxbean.cardano.client.cip.cip25.NFTMetadata;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataList;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataMap;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.script.NativeScript;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.Utils;
import co.nstant.in.cbor.model.UnicodeString;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_Mint_NFT Java Action Documentation
 * 
 * ## Description
 * This Java action, `JA_Mint_NFT`, is designed to mint a Non-Fungible Token (NFT) on the Cardano network.
 * 
 * ## Parameters
 * 
 * ### EncryptedMnemonic
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to store the encrypted mnemonic phrase for the wallet. The mnemonic phrase is a list of words which store all the information needed to recover a cryptocurrency wallet.
 * 
 * ### Passphrase
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to store the passphrase for the wallet. The passphrase is used to encrypt the wallet's private keys.
 * 
 * ### ReceiverAddress
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to store the address of the receiver. The receiver is the entity that will receive the minted NFT.
 * 
 * ### CardanoNetwork
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to specify the Cardano network where the NFT will be minted. This could be either the mainnet or a testnet.
 * 
 * ### Metadata
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to store the metadata of the NFT. Metadata is a set of data that describes and gives information about the NFT.
 * 
 * ### MxNFT
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to store the Mendix NFT object. This object contains all the information about the NFT.
 * 
 * ### IPFSImage
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to store the InterPlanetary File System (IPFS) image hash. This hash is used to retrieve the image associated with the NFT from the IPFS.
 * 
 * ### NFTFileList
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to store a list of files associated with the NFT.
 * 
 * ### Policy
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to store the policy script for the NFT. The policy script defines the conditions under which the NFT can be minted.
 * 
 * ### PolicyPassphrase
 * - Type: `CodeActions$BasicParameterType`
 * - Description: This parameter is used to store the passphrase for the policy script. This passphrase is used to encrypt the policy script.
 */
public class JA_Mint_NFT extends UserAction<java.lang.String>
{
	private final java.lang.String EncryptedMnemonic;
	private final java.lang.String Passphrase;
	private final java.lang.String ReceiverAddress;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;
	private final java.lang.String Metadata;
	/** @deprecated use MxNFT.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MxNFT;
	private final cardanowallet.proxies.NFT MxNFT;
	private final java.lang.String IPFSImage;
	/** @deprecated use com.mendix.utils.ListUtils.map(NFTFileList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __NFTFileList;
	private final java.util.List<cardanowallet.proxies.NFTFile> NFTFileList;
	/** @deprecated use Policy.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Policy;
	private final cardanowallet.proxies.Policy Policy;
	private final java.lang.String PolicyPassphrase;

	public JA_Mint_NFT(
		IContext context,
		java.lang.String _encryptedMnemonic,
		java.lang.String _passphrase,
		java.lang.String _receiverAddress,
		java.lang.String _cardanoNetwork,
		java.lang.String _metadata,
		IMendixObject _mxNFT,
		java.lang.String _iPFSImage,
		java.util.List<IMendixObject> _nFTFileList,
		IMendixObject _policy,
		java.lang.String _policyPassphrase
	)
	{
		super(context);
		this.EncryptedMnemonic = _encryptedMnemonic;
		this.Passphrase = _passphrase;
		this.ReceiverAddress = _receiverAddress;
		this.CardanoNetwork = _cardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetwork);
		this.Metadata = _metadata;
		this.__MxNFT = _mxNFT;
		this.MxNFT = _mxNFT == null ? null : cardanowallet.proxies.NFT.initialize(getContext(), _mxNFT);
		this.IPFSImage = _iPFSImage;
		this.__NFTFileList = _nFTFileList;
		this.NFTFileList = java.util.Optional.ofNullable(_nFTFileList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(nFTFileListElement -> cardanowallet.proxies.NFTFile.initialize(getContext(), nFTFileListElement))
			.collect(java.util.stream.Collectors.toList());
		this.__Policy = _policy;
		this.Policy = _policy == null ? null : cardanowallet.proxies.Policy.initialize(getContext(), _policy);
		this.PolicyPassphrase = _policyPassphrase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Utils utils = new Utils(this.Policy.getCardanonetwork().toString().toLowerCase());
		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
        BFBackendService backendService = new BFBackendService(this.blockfrostUrl, bfProjectId);
		String mnemonic = EncryptDecryptMnemonic.decrypt(this.EncryptedMnemonic, this.Passphrase);
		sender = new Account(utils.getCardanoNetwork(), mnemonic);
        String senderAddress = sender.baseAddress();
        LOG.info("Sender address"+senderAddress);

        Policy policy = null;
        if(this.Policy != null) {
        	LOG.debug("Using existing mx policy");
	        try {
	    		NativeScript nativeScript = NativeScript.deserializeJson(this.Policy.getScriptJSON());
	            policy = new Policy(nativeScript);
	            
	            //TODO: find out how to add key to policy
	        } catch (Exception e) {
	        	System.out.println("Json object mapper read value error");
	        	e.printStackTrace();
	        }
        } else {
        	LOG.debug("Creating a fresh Policy for the NFT");
        	policy = PolicyUtil.createMultiSigScriptAllPolicy(this.MxNFT.getPolicyName(),1);	
        }

        Asset asset = new Asset(this.MxNFT.getAssetName(), BigInteger.valueOf(1));
        NFT nft = NFT.create()
        		.assetName(asset.getName())
        		.name(this.MxNFT.getName())
        		.image(this.MxNFT.getIPFSImage())
        		.description(this.MxNFT.getDescription());
        
        String stringMetadata = this.MxNFT.getJSONMetadata();
        if((stringMetadata != null && !stringMetadata.isEmpty()) && !stringMetadata.startsWith("{")) {
        	stringMetadata = "{"+stringMetadata+"}";
        }
		try {
            Map<String, Object> properties = createPropertiesFromJsonString(stringMetadata);

            // Now you can use this properties map to generate NFT metadata
            generateNFTMetadata(nft, properties);
            for (cardanowallet.proxies.NFTFile entry : this.NFTFileList) {
            	nft.addFile(NFTFile.create()
            			.name(entry.getName())
            			.mediaType(entry.getMediaType())
            			.src(entry.getSourceUrl())
            	);
            }
        } catch (Exception e) { 
            e.printStackTrace(); 
        }
        var version = this.MxNFT.getVersion().toString();
		NFTMetadata nftMetadata = NFTMetadata.create()
                .addNFT(policy.getPolicyId(), nft);

        Tx tx = new Tx()
                .mintAssets(policy.getPolicyScript(), asset, sender.baseAddress())
                .attachMetadata(nftMetadata)
                .from(sender.baseAddress());
        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
        Result<String> result = quickTxBuilder.compose(tx)
                .withSigner(SignerProviders.signerFrom(sender))
                .withSigner(SignerProviders.signerFrom(policy))
                .complete();

        if (result.isSuccessful())
            LOG.info("Transaction Id: " + result.getValue());
        else
            LOG.info("Transaction failed: " + result);
        return result.getValue();
	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Mint_NFT";
	}

	// BEGIN EXTRA CODE
    private String blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
	private Account sender;
    public static ILogNode LOG = Core.getLogger("LandanoTest - NFT Creation");
    
    public static NFT generateNFTMetadata(NFT nft, Map<String, Object> properties) {
    	LOG.info("NFT Map::::::");
    	LOG.info(nft.getMap());
    	
        
        for (Map.Entry<String, Object> entry : properties.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();
            System.out.println("properties Key::"+ key);
            System.out.println("properties Value::"+ value);
            
            if (value instanceof Map) {
                CBORMetadataMap nestedMap = convertToCBORMetadataMap((Map<String, Object>) value);
                var nftMap = nft.getMap();
                nftMap.put(new UnicodeString(key), nestedMap.getMap());
                
            } else if (value instanceof List) {
                CBORMetadataList nestedList = convertToCBORMetadataList((List<Object>) value);
                var nftMap = nft.getMap();
                nftMap.put(new UnicodeString(key),nestedList.getArray());
            } else {
                nft.property(key, value.toString());
            }
        }
        
        return nft;
    }

    private static CBORMetadataMap convertToCBORMetadataMap(Map<String, Object> map) {
	    CBORMetadataMap cborMap = new CBORMetadataMap();
	    System.out.println("Map::::::::");
	    System.out.println(map);
	    for (Map.Entry<String, Object> entry : map.entrySet()) {
	        String key = entry.getKey();
	        Object value = entry.getValue();
	        if (value instanceof Map) {
	            cborMap.put(key, convertToCBORMetadataMap((Map<String, Object>) value));
	        } else if (value instanceof List) {
	            cborMap.put(key, convertToCBORMetadataList((List<Object>) value));
	        } else {
	            cborMap.put(key, value.toString());
	        }
	    }
	    return cborMap;
	}
    
    private static CBORMetadataList convertToCBORMetadataList(List<Object> list) {
	    CBORMetadataList cborList = new CBORMetadataList();
	    System.out.println("List::::::::");
	    System.out.println(list);
	    for (Object item : list) {
	        if (item instanceof Map) {
	            cborList.add(convertToCBORMetadataMap((Map<String, Object>) item));
	        } else if (item instanceof List) {
	            cborList.add(convertToCBORMetadataList((List<Object>) item));
	        } else {
	        	System.out.println("LISTITEM TYPE::::" + item.getClass().toString());
	            cborList.add(item.toString());
	        }
	    }
	    return cborList;
	}
    
    public static Map<String, Object> createPropertiesFromJsonString(String jsonString) throws Exception {
    	System.out.println(jsonString);
        ObjectMapper mapper = new ObjectMapper();
        JsonNode rootNode = mapper.readTree(jsonString);
        System.out.println(rootNode);
        
        return convertJsonNodeToMap(rootNode);
    }

    private static Map<String, Object> convertJsonNodeToMap(JsonNode node) {
        Map<String, Object> map = new HashMap<>();
        
        node.fields().forEachRemaining(entry -> {
            String key = entry.getKey();
            JsonNode value = entry.getValue();
            System.out.println("Key:::"+key);
            System.out.println("Value::"+value);
            
            if (value.isObject()) {
                map.put(key, convertJsonNodeToMap(value));
            } else if (value.isArray()) {
                map.put(key, convertJsonNodeToList(value));
            } else if (value.isNumber()) {
                map.put(key, value.numberValue());
            } else if (value.isBoolean()) {
                map.put(key, value.booleanValue());
            } else {
                map.put(key, value.asText());
            }
        });
        
        return map;
    }

    private static List<Object> convertJsonNodeToList(JsonNode node) {
        List<Object> list = new ArrayList<>();
        
        for (JsonNode element : node) {
            if (element.isObject()) {
                list.add(convertJsonNodeToMap(element));
            } else if (element.isArray()) {
                list.add(convertJsonNodeToList(element));
            } else if (element.isNumber()) {
                list.add(element.numberValue());
            } else if (element.isBoolean()) {
                list.add(element.booleanValue());
            } else {
                list.add(element.asText());
            }
        }
        
        return list;
    }
    
	// END EXTRA CODE
}
