// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.api.util.PolicyUtil;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.cip.cip25.NFT;
import com.bloxbean.cardano.client.cip.cip25.NFTFile;
import com.bloxbean.cardano.client.cip.cip25.NFTMetadata;
import com.bloxbean.cardano.client.crypto.SecretKey;
import com.bloxbean.cardano.client.crypto.bip32.key.HdPrivateKey;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.metadata.Metadata;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadata;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataList;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataMap;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.script.NativeScript;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.Utils;
import cardanowallet.proxies.NFTFileNP;
import cardanowallet.proxies.NFTNP;
import cardanowallet.proxies.RecipientNP;
import cardanowallet.proxies.TokenType;
import cardanowallet.proxies.Wallet;
import co.nstant.in.cbor.model.UnicodeString;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_NFT_Mint Java Action Documentation
 * 
 * ## Overview
 * The `JA_NFT_Mint` action is a Java-based function in the Mendix platform. This action is primarily used for minting Non-Fungible Tokens (NFTs).
 * 
 * ## Parameters
 * 
 * The `JA_NFT_Mint` action accepts two parameters:
 * 
 * ### TransactionNP
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter is currently lacking a detailed description. It is recommended to provide a meaningful description for better understanding of its purpose and usage. For instance, if this parameter is used to hold transaction data for the NFT minting process, a suitable description could be "This parameter holds the necessary transaction data for the NFT minting process."
 * 
 * ### Passphrase
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter is currently lacking a detailed description. It is recommended to provide a meaningful description for better understanding of its purpose and usage. For instance, if this parameter is used to authenticate the user initiating the NFT minting process, a suitable description could be "This parameter is used to authenticate the user initiating the NFT minting process."
 * 
 * ## Usage
 * 
 * To use the `JA_NFT_Mint` action, you need to provide values for the `TransactionNP` and `Passphrase` parameters. The specific values you need to provide will depend on your application's requirements and the specific use case you are addressing.
 * 
 * ## Notes
 * 
 * Please ensure to handle these parameters with care, especially the `Passphrase` as it may contain sensitive information. Always follow your organization's security best practices when dealing with sensitive information.
 */
public class JA_NFT_Mint extends UserAction<java.lang.String>
{
	/** @deprecated use TransactionNP.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TransactionNP;
	private final cardanowallet.proxies.TransactionNP TransactionNP;
	private final java.lang.String Passphrase;

	public JA_NFT_Mint(
		IContext context,
		IMendixObject _transactionNP,
		java.lang.String _passphrase
	)
	{
		super(context);
		this.__TransactionNP = _transactionNP;
		this.TransactionNP = _transactionNP == null ? null : cardanowallet.proxies.TransactionNP.initialize(getContext(), _transactionNP);
		this.Passphrase = _passphrase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
	    // Prepare the sender wallet and NFT data
	    Wallet wallet = TransactionNP.getTransactionNP_Wallet();
	    NFTNP nftNP = TransactionNP.getTransactionNP_NFTNP();

	    // Determine network from policy if available, otherwise from wallet
	    var existingPolicy = TransactionNP.getTransactionNP_Policy();
	    String networkName;
	    if (existingPolicy != null) {
	        networkName = existingPolicy.getCardanonetwork().toString().toLowerCase();
	    } else {
	        networkName = wallet.getCardanonetwork().toString().toLowerCase();
	    }
	    Utils utils = new Utils(networkName);

		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
        BFBackendService backendService = new BFBackendService(utils.getBlockfrostUrl(), bfProjectId);

        String mnemonic = EncryptDecryptMnemonic.decrypt(wallet.getMnemonicEncrypted(), this.Passphrase);
		Account senderAccount = new Account(utils.getCardanoNetwork(), mnemonic);
		mnemonic = null;
		String senderAddress = senderAccount.baseAddress();

        // Build or auto-create minting policy
        Policy policy;
        NativeScript nativeScript;
        if (existingPolicy != null) {
            LOG.debug("Using existing policy");
            nativeScript = NativeScript.deserializeJson(existingPolicy.getScriptJSON());
            HdPrivateKey hdPrivateKey = senderAccount.hdKeyPair().getPrivateKey();
            SecretKey secretKey = SecretKey.create(hdPrivateKey.getKeyData());
            policy = new Policy(nativeScript).addKey(secretKey);
        } else {
            LOG.debug("No policy provided, creating a fresh policy");
            policy = PolicyUtil.createMultiSigScriptAllPolicy(nftNP.getName(), 1);
            nativeScript = (NativeScript) policy.getPolicyScript();
        }
        Metadata metadata = null;

        // Build the NFT meta data
        Integer quantityOfTokens = Objects.requireNonNullElse(nftNP.getQuantity(), 1) ;
        
        Asset asset = new Asset(nftNP.getName(), BigInteger.valueOf(quantityOfTokens));
        if(TokenType.NFT.equals(nftNP.getTokenType())) {
	        NFT nft = NFT.create()
	        		.assetName(asset.getName())
	        		.name(nftNP.getName())
	        		.image(nftNP.getImageURL())
	        		.description(nftNP.getDescription());
	        
	        String stringMetadata = nftNP.getMetadataJSON();
	        if((stringMetadata != null && !stringMetadata.isEmpty()) && !stringMetadata.startsWith("{")) {
	        	stringMetadata = "{"+stringMetadata+"}";
	        }
			try {
	            Map<String, Object> properties = createPropertiesFromJsonString(stringMetadata);
	
	            // Now you can use this properties map to generate NFT metadata
	            generateNFTMetadata(nft, properties);
	            
	            List<IMendixObject> nftFiles = Core.retrieveByPath(
	                    getContext(),
	                    nftNP.getMendixObject(),
	                    NFTFileNP.MemberNames.NFTFileNP_NFTNP.toString()
	                );
	
	            for (IMendixObject nftNPobj : nftFiles) {
	            	NFTFileNP nftFileNP = NFTFileNP.initialize(getContext(), nftNPobj);
	            	nft.addFile(NFTFile.create()
	            			.name(nftFileNP.getName())
	            			.mediaType(nftFileNP.getMediaType())
	            			.src(nftFileNP.getSourceUrl())
	            	);
	            }
	        } catch (Exception e) { 
	            e.printStackTrace(); 
	        }
	
			metadata = NFTMetadata.create()
	                .addNFT(nativeScript.getPolicyId(), nft);
        } else if(TokenType.FT.equals(nftNP.getTokenType())){
        	CBORMetadataMap tokenInfoMap = new CBORMetadataMap()
	            .put("token", nftNP.getName())
	            .put("ticker", nftNP.getTicker())
	            .put("decimals", BigInteger.valueOf(nftNP.getDecimals()));

		    /*CBORMetadataList tagList
		            = new CBORMetadataList()
		            .add("tag1")
		            .add("tag2");*/
		
		    metadata = new CBORMetadata()
		            .put(new BigInteger("670001"), tokenInfoMap); // CIP-68 
		    	// .put(new BigInteger("670002"), tagList); // CIP-68
        } else {
        	LOG.error("An asset should be either NFT or FT");
        }

		RecipientNP recipient = TransactionNP.getTransactionNP_RecipientNP_Single();
		
		
		// Build the transaction
        Tx tx = new Tx()
                .mintAssets(nativeScript, asset, recipient.getAddress())
                .attachMetadata(metadata)
                .from(senderAddress);        
        
        // Compose, sign and submit the transaction
        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
        Result<String> signedTx = quickTxBuilder
                .compose(tx)
                .feePayer(senderAddress)
                .withSigner(SignerProviders.signerFrom(senderAccount)) // Sign with sender's private key
                .withSigner(SignerProviders.signerFrom(policy)) // Sign with policy key
                .preBalanceTx((context, txn) -> {
                    txn.getWitnessSet().getNativeScripts().add(nativeScript); // Explicitly add the script witness
                })
                .completeAndWait(LOG::debug);
		
        if (signedTx.isSuccessful()) {
            LOG.debug("NFT Minting Transaction Submitted: " + signedTx.getValue());
            return signedTx.getValue();
        } else {
            LOG.error("NFT Minting Failed: " + signedTx.getResponse());
            throw new Exception("NFT Minting Failed: " + signedTx.getResponse());
        }                	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_NFT_Mint";
	}

	// BEGIN EXTRA CODE
    public static ILogNode LOG = Core.getLogger(cardanowallet.proxies.constants.Constants.getLogNodeName());
    
    public static NFT generateNFTMetadata(NFT nft, Map<String, Object> properties) {
    	LOG.debug("NFT Map::::::");
    	LOG.debug(nft.getMap());
    	
        
        for (Map.Entry<String, Object> entry : properties.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();
            System.out.println("properties Key::"+ key);
            System.out.println("properties Value::"+ value);
            
            if (value instanceof Map) {
                CBORMetadataMap nestedMap = convertToCBORMetadataMap((Map<String, Object>) value);
                var nftMap = nft.getMap();
                nftMap.put(new UnicodeString(key), nestedMap.getMap());
                
            } else if (value instanceof List) {
                CBORMetadataList nestedList = convertToCBORMetadataList((List<Object>) value);
                var nftMap = nft.getMap();
                nftMap.put(new UnicodeString(key),nestedList.getArray());
            } else {
                nft.property(key, value.toString());
            }
        }
        
        return nft;
    }

    private static CBORMetadataMap convertToCBORMetadataMap(Map<String, Object> map) {
	    CBORMetadataMap cborMap = new CBORMetadataMap();
	    System.out.println("Map::::::::");
	    System.out.println(map);
	    for (Map.Entry<String, Object> entry : map.entrySet()) {
	        String key = entry.getKey();
	        Object value = entry.getValue();
	        if (value instanceof Map) {
	            cborMap.put(key, convertToCBORMetadataMap((Map<String, Object>) value));
	        } else if (value instanceof List) {
	            cborMap.put(key, convertToCBORMetadataList((List<Object>) value));
	        } else {
	            cborMap.put(key, value.toString());
	        }
	    }
	    return cborMap;
	}
    
    private static CBORMetadataList convertToCBORMetadataList(List<Object> list) {
	    CBORMetadataList cborList = new CBORMetadataList();
	    System.out.println("List::::::::");
	    System.out.println(list);
	    for (Object item : list) {
	        if (item instanceof Map) {
	            cborList.add(convertToCBORMetadataMap((Map<String, Object>) item));
	        } else if (item instanceof List) {
	            cborList.add(convertToCBORMetadataList((List<Object>) item));
	        } else {
	        	System.out.println("LISTITEM TYPE::::" + item.getClass().toString());
	            cborList.add(item.toString());
	        }
	    }
	    return cborList;
	}
    
    public static Map<String, Object> createPropertiesFromJsonString(String jsonString) throws Exception {
    	System.out.println(jsonString);
        ObjectMapper mapper = new ObjectMapper();
        JsonNode rootNode = mapper.readTree(jsonString);
        System.out.println(rootNode);
        
        return convertJsonNodeToMap(rootNode);
    }

    private static Map<String, Object> convertJsonNodeToMap(JsonNode node) {
        Map<String, Object> map = new HashMap<>();
        
        node.fields().forEachRemaining(entry -> {
            String key = entry.getKey();
            JsonNode value = entry.getValue();
            System.out.println("Key:::"+key);
            System.out.println("Value::"+value);
            
            if (value.isObject()) {
                map.put(key, convertJsonNodeToMap(value));
            } else if (value.isArray()) {
                map.put(key, convertJsonNodeToList(value));
            } else if (value.isNumber()) {
                map.put(key, value.numberValue());
            } else if (value.isBoolean()) {
                map.put(key, value.booleanValue());
            } else {
                map.put(key, value.asText());
            }
        });
        
        return map;
    }

    private static List<Object> convertJsonNodeToList(JsonNode node) {
        List<Object> list = new ArrayList<>();
        
        for (JsonNode element : node) {
            if (element.isObject()) {
                list.add(convertJsonNodeToMap(element));
            } else if (element.isArray()) {
                list.add(convertJsonNodeToList(element));
            } else if (element.isNumber()) {
                list.add(element.numberValue());
            } else if (element.isBoolean()) {
                list.add(element.booleanValue());
            } else {
                list.add(element.asText());
            }
        }
        
        return list;
    }
    
	// END EXTRA CODE
}
