// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.api.DefaultProtocolParamsSupplier;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import static com.bloxbean.cardano.client.function.helper.SignerProviders.signerFrom;
import com.bloxbean.cardano.client.cip.cip20.MessageMetadata;
import com.bloxbean.cardano.client.cip.cip25.NFT;
import com.bloxbean.cardano.client.cip.cip25.NFTFile;
import com.bloxbean.cardano.client.cip.cip25.NFTMetadata;
import com.bloxbean.cardano.client.crypto.SecretKey;
import com.bloxbean.cardano.client.crypto.bip32.key.HdPrivateKey;
import com.bloxbean.cardano.client.function.Output;
import com.bloxbean.cardano.client.function.TxBuilder;
import com.bloxbean.cardano.client.function.TxBuilderContext;
import com.bloxbean.cardano.client.function.helper.BalanceTxBuilders;
import com.bloxbean.cardano.client.function.helper.InputBuilders;
import com.bloxbean.cardano.client.function.helper.MintCreators;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.metadata.Metadata;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadata;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataList;
import com.bloxbean.cardano.client.metadata.cbor.CBORMetadataMap;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.transaction.spec.Asset;
import com.bloxbean.cardano.client.transaction.spec.MultiAsset;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.TransactionOutput;
import com.bloxbean.cardano.client.transaction.spec.script.NativeScript;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.Utils;
import cardanowallet.proxies.NFTFileNP;
import cardanowallet.proxies.NFTNP;
import cardanowallet.proxies.RecipientNP;
import cardanowallet.proxies.TokenType;
import cardanowallet.proxies.Wallet;
import co.nstant.in.cbor.model.UnicodeString;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_NFT_Burn Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_NFT_Burn` action is a Java-based action designed to facilitate the burning of Non-Fungible Tokens (NFTs) in a blockchain environment.
 * 
 * ## Parameters
 * 
 * This action requires the following parameters:
 * 
 * ### TransactionNP
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter represents the transaction details for the NFT that is to be burned. The specific format and content of this parameter may vary depending on the specifics of the blockchain platform being used. As no specific description has been provided, it is recommended to refer to the relevant blockchain platform documentation for further guidance.
 * 
 * ### Passphrase
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter represents the passphrase that is used to authenticate the burning transaction. This is typically the passphrase associated with the wallet or account that currently owns the NFT. As no specific description has been provided, it is recommended to refer to the relevant blockchain platform documentation for further guidance.
 * 
 * ## Usage
 * 
 * To use the `JA_NFT_Burn` action, you will need to provide the necessary parameters as described above. The action will then execute the burning process, effectively removing the specified NFT from circulation within the blockchain platform.
 * 
 * Please note that due to the immutable nature of blockchain transactions, once an NFT is burned, it cannot be recovered. Therefore, it is crucial to ensure that the correct NFT is specified and that the burning process is indeed desired before executing this action.
 */
public class JA_NFT_Burn extends UserAction<java.lang.String>
{
	/** @deprecated use TransactionNP.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TransactionNP;
	private final cardanowallet.proxies.TransactionNP TransactionNP;
	private final java.lang.String Passphrase;

	public JA_NFT_Burn(
		IContext context,
		IMendixObject _transactionNP,
		java.lang.String _passphrase
	)
	{
		super(context);
		this.__TransactionNP = _transactionNP;
		this.TransactionNP = _transactionNP == null ? null : cardanowallet.proxies.TransactionNP.initialize(getContext(), _transactionNP);
		this.Passphrase = _passphrase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
	    Utils utils = new Utils(this.TransactionNP.getTransactionNP_Policy()
                .getCardanonetwork()
                .toString()
                .toLowerCase());
	    
		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
        BFBackendService backendService = new BFBackendService(utils.getBlockfrostUrl(), bfProjectId);
        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);

        // Prepare the sender wallet
	    Wallet wallet = TransactionNP.getTransactionNP_Wallet();        
        String mnemonic = EncryptDecryptMnemonic.decrypt(wallet.getMnemonicEncrypted(), this.Passphrase);
		Account senderAccount = new Account(utils.getCardanoNetwork(), mnemonic);
		mnemonic = null;

        // NativeScript from the JSON policy script
        NativeScript nativeScript = NativeScript.deserializeJson(
            TransactionNP.getTransactionNP_Policy().getScriptJSON()
        );
        HdPrivateKey hdPrivateKey = senderAccount.hdKeyPair().getPrivateKey();
        SecretKey secretKey = SecretKey.create(hdPrivateKey.getKeyData());
        Policy policy = new Policy(nativeScript)
        		.addKey(secretKey);
        
        // Build the NFT meta data
        NFTNP nftNP = TransactionNP.getTransactionNP_NFTNP();
        Integer quantityOfTokens = Objects.requireNonNullElse(nftNP.getQuantity(), 1) ;
        
        Asset asset = new Asset(nftNP.getName(), BigInteger.valueOf(quantityOfTokens).negate());

        Tx burnTx = new Tx()
        		.payToAddress(senderAccount.baseAddress(), Amount.ada(1.0))
                .mintAssets(policy.getPolicyScript(), List.of(asset))
                .attachMetadata(MessageMetadata.create().add("Burning tx")) //metadata is not necessary
                .from(senderAccount.baseAddress());

        Result<String> burnResult = quickTxBuilder.compose(burnTx)
                .withSigner(SignerProviders.signerFrom(senderAccount))
                .withSigner(SignerProviders.signerFrom(policy))
                .completeAndWait(LOG::debug);

        return burnResult.getValue();
        
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_NFT_Burn";
	}

	// BEGIN EXTRA CODE
    public static ILogNode LOG = Utils.LOG;
	// END EXTRA CODE
}
