// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import cardanowallet.Utils;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.transaction.spec.Policy;
import com.bloxbean.cardano.client.transaction.spec.script.NativeScript;
import com.bloxbean.cardano.client.transaction.util.NativeScriptDeserializer;
import com.bloxbean.cardano.client.util.HexUtil;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_PolicyScript_Create Java Action Documentation
 * 
 * ## Introduction
 * 
 * The `JA_PolicyScript_Create` is a Java action that is used within the Mendix platform. This document provides the necessary details about this action.
 * 
 * ## Parameters
 * 
 * The `JA_PolicyScript_Create` action has one parameter:
 * 
 * ### Policy
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is not described in the provided information. However, based on its name, it can be inferred that it is likely used to pass some form of policy-related data to the action. The exact nature of this data and how it is used by the action would depend on the specific implementation details of the action.
 * 
 * ## Usage
 * 
 * To use the `JA_PolicyScript_Create` action, you need to pass the required parameter as per the specific requirements of your application. The `Policy` parameter should be an instance of `CodeActions$BasicParameterType`.
 * 
 * Please note that the exact usage of this action and its effects will depend on the specific implementation details of the action. For more detailed information, please refer to the code documentation or the developer who implemented the action.
 * 
 * ## Conclusion
 * 
 * This document provides a basic overview of the `JA_PolicyScript_Create` Java action. For more detailed information, please refer to the specific implementation details of the action or consult with the developer who implemented the action.
 */
public class JA_PolicyScript_Create extends UserAction<java.lang.Void>
{
	/** @deprecated use Policy.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Policy;
	private final cardanowallet.proxies.Policy Policy;

	public JA_PolicyScript_Create(
		IContext context,
		IMendixObject _policy
	)
	{
		super(context);
		this.__Policy = _policy;
		this.Policy = _policy == null ? null : cardanowallet.proxies.Policy.initialize(getContext(), _policy);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		var utils = new Utils(this.Policy.getCardanonetwork().toString().toLowerCase());
		NativeScript nativeScript = NativeScript.deserializeJson(this.Policy.getScriptJSON());
        byte[] serializedBytes = nativeScript.serializeScriptBody();
        String hexRepresentation = HexUtil.encodeHexString(serializedBytes);
		this.Policy.setScriptHash(hexRepresentation);
	    String nativeScriptBech32Address = AddressProvider.getEntAddress(nativeScript, utils.getCardanoNetwork()).toBech32();
	    this.Policy.setAddress(nativeScriptBech32Address);
		Policy policy = new Policy(this.Policy.getName(), nativeScript);
		this.Policy.setPolicyId(policy.getPolicyId());
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_PolicyScript_Create";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
