// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.address.Address;
import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.api.model.Utxo;
import com.bloxbean.cardano.client.backend.api.BackendService;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.api.TransactionService;
import com.bloxbean.cardano.client.backend.api.UtxoService;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.backend.model.TransactionContent;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.plutus.blueprint.PlutusBlueprintUtil;
import com.bloxbean.cardano.client.plutus.blueprint.model.PlutusVersion;
import com.bloxbean.cardano.client.plutus.spec.BytesPlutusData;
import com.bloxbean.cardano.client.plutus.spec.ConstrPlutusData;
import com.bloxbean.cardano.client.plutus.spec.PlutusData;
import com.bloxbean.cardano.client.plutus.spec.PlutusScript;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.util.JsonUtil;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import cardanowallet.EncryptDecryptMnemonic;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_SmartContract_Lock Java Action Documentation
 * 
 * The `JA_SmartContract_Lock` Java action is designed to execute a smart contract lock operation. 
 * 
 * ## Parameters
 * 
 * The `JA_SmartContract_Lock` action requires the following parameters:
 * 
 * ### PlutusScriptCode
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to specify the Plutus script code for the smart contract. The specific details of the code are not provided.
 * 
 * ### CardanoNetwork
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to specify the Cardano network where the smart contract will be executed. The specific details of the network are not provided.
 * 
 * ### SenderPassPhrase
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to provide the passphrase of the sender's wallet. This is required for authorizing the smart contract execution.
 * 
 * ### ContractScript
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to specify the script of the smart contract. The specific details of the script are not provided.
 * 
 * ### ContractAmount
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to specify the amount of the contract. This could be the amount of cryptocurrency to be locked in the contract.
 * 
 * ### SenderWallet
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to specify the sender's wallet. This could be the wallet from which the contract amount will be deducted.
 * 
 * ### ReceiverAddress
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to specify the receiver's address. This could be the address where the contract amount will be sent after the contract execution.
 * 
 * Please note that the specific details for each parameter might vary based on the implementation of the `JA_SmartContract_Lock` Java action.
 */
public class JA_SmartContract_Lock extends UserAction<IMendixObject>
{
	private final java.lang.String PlutusScriptCode;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;
	private final java.lang.String SenderPassPhrase;
	/** @deprecated use ContractScript.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ContractScript;
	private final cardanowallet.proxies.Script ContractScript;
	private final java.math.BigDecimal ContractAmount;
	/** @deprecated use SenderWallet.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __SenderWallet;
	private final cardanowallet.proxies.Wallet SenderWallet;
	private final java.lang.String ReceiverAddress;

	public JA_SmartContract_Lock(
		IContext context,
		java.lang.String _plutusScriptCode,
		java.lang.String _cardanoNetwork,
		java.lang.String _senderPassPhrase,
		IMendixObject _contractScript,
		java.math.BigDecimal _contractAmount,
		IMendixObject _senderWallet,
		java.lang.String _receiverAddress
	)
	{
		super(context);
		this.PlutusScriptCode = _plutusScriptCode;
		this.CardanoNetwork = _cardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetwork);
		this.SenderPassPhrase = _senderPassPhrase;
		this.__ContractScript = _contractScript;
		this.ContractScript = _contractScript == null ? null : cardanowallet.proxies.Script.initialize(getContext(), _contractScript);
		this.ContractAmount = _contractAmount;
		this.__SenderWallet = _senderWallet;
		this.SenderWallet = _senderWallet == null ? null : cardanowallet.proxies.Wallet.initialize(getContext(), _senderWallet);
		this.ReceiverAddress = _receiverAddress;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		compiledCode = this.PlutusScriptCode;
		assignBlockfrostNetwork(CardanoNetwork.name());
		backendService = new BFBackendService(blockfrostUrl, blockfrostProjectID);
		transactionService = backendService.getTransactionService();
		this.lock();
		return this.ContractScript.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_SmartContract_Lock";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("LandanoTest");
	private Network selectedNetwork;
	private String blockfrostUrl;
	private String blockfrostProjectID = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
	
	private Account sender;
	private String compiledCode;
	
	    //Blockfrost
	 private BackendService backendService;
	 private TransactionService transactionService;
	
	 private PlutusScript plutusScript;
	 private String scriptAddr;
	
    public String lock() {
    	/*
		Map<String, Object> params = new HashMap<String, Object>();
        params.put("value", this.SenderWallet.getMnemonicEncrypted()); // Adjust parameter names as needed
        params.put("key", encryption.proxies.constants.Constants.getEncryptionKey() + this.SenderPassPhrase); // Adjust parameter names as needed
        params.put("prefix", encryption.proxies.constants.Constants.getEncryptionPrefix()); // Adjust parameter names as needed
        params.put("legacyKey", encryption.proxies.constants.Constants.getLegacyEncryptionKey()); // Adjust parameter names as needed
        
        String mnemonic = (String) Core.userActionCall("Encryption.DecryptString")
        		.withParams(this.getContext(), params)
        		.execute(this.getContext());
        */
    	var decrypt = new EncryptDecryptMnemonic();
    	try {
    		// optionally we should allow users to input their mnemonics directly in the UI instead of even saving them on our servers.
			String mnemonic = decrypt.decrypt(this.SenderWallet.getMnemonicEncrypted(), this.SenderPassPhrase);
			sender = new Account(selectedNetwork, mnemonic);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			LOG.error(e);
		}
		plutusScript = PlutusBlueprintUtil.getPlutusScriptFromCompiledCode(compiledCode, PlutusVersion.v3);
		scriptAddr = AddressProvider.getEntAddress(plutusScript, selectedNetwork).toBech32();
        //create datum
		PlutusData datum = ConstrPlutusData.of(0, BytesPlutusData.of((new Address(this.ReceiverAddress)).getPaymentCredentialHash().get()));

        Tx tx = new Tx()
            .payToContract(scriptAddr, Amount.ada(this.ContractAmount.doubleValue()), datum)
            .from(sender.baseAddress());

        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(this.backendService);
        Result<String> result = quickTxBuilder.compose(tx)
                .withSigner(SignerProviders.signerFrom(this.sender))
                .completeAndWait(System.out::println);

        LOG.info("=======RESULT======");
        LOG.info(result);
        LOG.info("======LOCK===DONE======");
        
        if(result.isSuccessful()) {
        	this.ContractScript.setLockTransactionHash(result.getValue());
        	this.ContractScript.setScriptAddress(scriptAddr);
        	this.ContractScript.setPlutusScriptCode(PlutusScriptCode);
        	this.ContractScript.setSenderAddress(sender.getBaseAddress().toBech32());
        	try {
				this.ContractScript.commit();
			} catch (CoreException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				LOG.error(e);
			}
        }
        Utxo refUtxo = Utxo.builder()
                .txHash(result.getValue())
                .outputIndex(0)
                .build();
        System.out.println("UTXO address is getaddress method:"+refUtxo.getAddress());
        System.out.println("UTXO address is :"+refUtxo.toString());
        LOG.info("===Reference UTXOs=====");
        LOG.info(refUtxo);
//        System.out.println(result.getResponse());
        
        return result.getValue();
    }


	private void assignBlockfrostNetwork(String networkString) {
		if(networkString.equalsIgnoreCase("preprod")) {
			selectedNetwork = Networks.preprod();
			blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
		} else if(networkString.equalsIgnoreCase("testnet")) {
			selectedNetwork = Networks.testnet();
			blockfrostUrl = Constants.BLOCKFROST_TESTNET_URL;
		} else if(networkString.equalsIgnoreCase("preview")) {
			blockfrostUrl = Constants.BLOCKFROST_PREVIEW_URL;
			selectedNetwork = Networks.preview();
		} else {
			selectedNetwork = Networks.mainnet();
			blockfrostUrl = Constants.BLOCKFROST_MAINNET_URL;
		}
		selectedNetwork = Networks.preprod();
		blockfrostUrl = Constants.BLOCKFROST_PREPROD_URL;
	}
    
	public void waitForTransaction(Result<String> result) {
		try {
			if (result.isSuccessful()) { //Wait for transaction to be mined
				int count = 0;
				while (count < 60) {
					Result<TransactionContent> txnResult = transactionService.getTransaction(result.getValue());
					if (txnResult.isSuccessful()) {
						System.out.println(JsonUtil.getPrettyJson(txnResult.getValue()));
						break;
					} else {
						System.out.println("Waiting for transaction to be mined ....");
					}
					count++;
					Thread.sleep(2000);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	private Optional<Utxo> getAvailableUtxo (UtxoService utxoService, String txHash, String address) {
		Optional<Utxo> utxo = Optional.empty();
        int count = 0;
        while (utxo.isEmpty()) {
            if (count++ >= 20)
                break;
            List<Utxo> utxos = new DefaultUtxoSupplier(utxoService).getAll(address);
            utxo = utxos.stream().filter(u -> u.getTxHash().equals(txHash))
                    .findFirst();
            if(utxo.isPresent()) {
                System.out.println("Output got is::::"+String.valueOf(count) +" :::::::: " + utxo.get().toString());
            } else {
            	System.out.println("Try to get new output... txhash: " + txHash);            	
            }

            try {
                Thread.sleep(1000);
            } catch (Exception e) {}
        }
        return utxo;
    }
	// END EXTRA CODE
}
