// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.address.Address;
import com.bloxbean.cardano.client.cip.cip30.CIP30DataSigner;
import com.bloxbean.cardano.client.cip.cip30.DataSignature;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.Utils;

public class JA_SignPayloadWithCardanoWallet extends UserAction<java.lang.Void>
{
	/** @deprecated use CardanoSignature.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CardanoSignature;
	private final cardanowallet.proxies.CardanoSignature CardanoSignature;
	private final java.lang.String Passphrase;

	public JA_SignPayloadWithCardanoWallet(
		IContext context,
		IMendixObject _cardanoSignature,
		java.lang.String _passphrase
	)
	{
		super(context);
		this.__CardanoSignature = _cardanoSignature;
		this.CardanoSignature = _cardanoSignature == null ? null : cardanowallet.proxies.CardanoSignature.initialize(getContext(), _cardanoSignature);
		this.Passphrase = _passphrase;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode log = Core.getLogger("CardanoWallet");

		if (CardanoSignature == null) {
			throw new IllegalArgumentException("CardanoSignature is required");
		}
		if (Passphrase == null || Passphrase.trim().isEmpty()) {
			throw new IllegalArgumentException("Passphrase is required");
		}

		// Get payload and wallet from the CardanoSignature entity
		String payload = CardanoSignature.getPayload();
		if (payload == null || payload.trim().isEmpty()) {
			throw new IllegalArgumentException("Payload is required on CardanoSignature");
		}

		cardanowallet.proxies.Wallet wallet = CardanoSignature.getCardanoSignature_Wallet();
		if (wallet == null) {
			throw new IllegalArgumentException("CardanoSignature must be associated with a Wallet");
		}

		// Decrypt mnemonic and create account
		String networkName = wallet.getCardanonetwork().toString().toLowerCase();
		Utils utils = new Utils(networkName);
		String mnemonic = EncryptDecryptMnemonic.decrypt(wallet.getMnemonicEncrypted(), this.Passphrase);
		Account account = new Account(utils.getCardanoNetwork(), mnemonic);
		mnemonic = null;

		// Get address bytes from account
		byte[] addressBytes = new Address(account.baseAddress()).getBytes();

		// Convert plain text payload to bytes
		byte[] payloadBytes = payload.getBytes(java.nio.charset.StandardCharsets.UTF_8);

		// Sign using CIP-30 data signer
		DataSignature dataSignature = CIP30DataSigner.INSTANCE.signData(addressBytes, payloadBytes, account);

		// Set results on the input CardanoSignature entity
		CardanoSignature.setSignatureHex(dataSignature.signature());
		CardanoSignature.setKeyHex(dataSignature.key());
		CardanoSignature.setSignerAddress(new Address(dataSignature.address()).getAddress());
		CardanoSignature.setCreatedAt(new java.util.Date());

		log.info("Payload signed successfully with Cardano wallet");

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_SignPayloadWithCardanoWallet";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
