// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.math.BigInteger;
import java.util.List;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.MetadataUtils;
import cardanowallet.Utils;
import cardanowallet.proxies.RecipientNP;
import cardanowallet.proxies.RecipientTokenNP;
import cardanowallet.proxies.Wallet;
import cardanowallet.proxies.Asset;
import system.proxies.Error;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_Simple_TransactionBuild Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_Simple_TransactionBuild` is a Java action that is used to perform a specific task in the Mendix application. This action requires certain parameters to be passed in order to execute successfully.
 * 
 * ## Parameters
 * 
 * The `JA_Simple_TransactionBuild` Java action requires the following parameter:
 * 
 * ### TransactionNP
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter is required for the `JA_Simple_TransactionBuild` Java action. However, no specific description has been provided for this parameter. It is of the type `CodeActions$BasicParameterType`, which is a basic parameter type in Mendix.
 * 
 * ## Usage
 * 
 * To use the `JA_Simple_TransactionBuild` Java action, you need to pass the required parameter `TransactionNP` of type `CodeActions$BasicParameterType`.
 * 
 * Please note that the specific usage of this Java action and the impact of the `TransactionNP` parameter on its behavior depends on the implementation of the action. For more detailed information, please refer to the specific code of the action or consult with the developer who implemented it.
 * 
 * ## Conclusion
 * 
 * The `JA_Simple_TransactionBuild` is a Java action in Mendix that requires one parameter for its execution. The parameter is `TransactionNP` of type `CodeActions$BasicParameterType`. For more specific details about its usage and implementation, it is recommended to refer to the action's code or consult the developer.
 */
public class JA_Simple_TransactionBuild extends UserAction<java.lang.String>
{
	/** @deprecated use TransactionNP.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TransactionNP;
	private final cardanowallet.proxies.TransactionNP TransactionNP;

	public JA_Simple_TransactionBuild(
		IContext context,
		IMendixObject _transactionNP
	)
	{
		super(context);
		this.__TransactionNP = _transactionNP;
		this.TransactionNP = _transactionNP == null ? null : cardanowallet.proxies.TransactionNP.initialize(getContext(), _transactionNP);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
	    Wallet wallet = TransactionNP.getTransactionNP_Wallet();
	    Utils utils = new Utils(wallet.getCardanonetwork()
	    		.toString()
	    		.toLowerCase());
	    
		// Decrypt the mnemonic
		String senderAddress = wallet.getBaseAddress();
		
		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
		BFBackendService backendService =
		        new BFBackendService(utils.getBlockfrostUrl(), bfProjectId);
        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);

		// Build the transaction output
		Tx tx = new Tx().from(senderAddress);
		
		List<IMendixObject> recipients = Core.retrieveByPath(
                getContext(),
                this.TransactionNP.getMendixObject(),
                RecipientNP.MemberNames.RecipientNP_TransactionNP.toString()
        );

        for (IMendixObject obj : recipients) {
            RecipientNP recipient = RecipientNP.initialize(getContext(), obj);
            tx.payToAddress(
                recipient.getAddress(),
                Amount.lovelace(BigInteger.valueOf(recipient.getAmountInLong()))
            );

    		List<IMendixObject> tokens = Core.retrieveByPath(
                    getContext(),
                    recipient.getMendixObject(),
                    RecipientTokenNP.MemberNames.RecipientTokenNP_RecipientNP.toString()
            );
    		
    		for (IMendixObject tokenObj : tokens) {
    			RecipientTokenNP token = RecipientTokenNP.initialize(getContext(), tokenObj);
    			Asset assetDetails = token.getRecipientTokenNP_Asset();
    			tx.payToAddress(
    				recipient.getAddress(),
    				Amount.asset(
    					assetDetails.getNameHex(), 
    					token.getAmount())
    				);
    		}
        }
		
		
		
		// Add the meta data
        String messageMetaData = TransactionNP.getMessageMetadata();
        if (messageMetaData != null && !messageMetaData.isEmpty()){
            tx.attachMetadata(MetadataUtils.createMessageMetadata(messageMetaData));
        }
        Transaction builtTx = null;
        try {
			builtTx = quickTxBuilder
		            .compose(tx)
	                .feePayer(senderAddress)
	                .build();
        } catch(Exception ex) {
        	throw ex;
        }
		return builtTx.serializeToHex();
		

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Simple_TransactionBuild";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
