// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.math.BigInteger;
import java.util.List;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.Tx;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.MetadataUtils;
import cardanowallet.Utils;
import cardanowallet.proxies.RecipientNP;
import cardanowallet.proxies.RecipientTokenNP;
import cardanowallet.proxies.Wallet;
import cardanowallet.proxies.Asset;
import system.proxies.Error;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_Simple_TransactionBuildSignSubmit Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_Simple_TransactionBuildSignSubmit` Java action is a function that facilitates the process of building, signing, and submitting a transaction. 
 * 
 * ## Parameters
 * 
 * This action requires two parameters:
 * 
 * ### TransactionNP
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is currently without a description. It is recommended to provide a clear and concise description for better understanding of its purpose and usage.
 * 
 * ### Passphrase
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is currently without a description. It is recommended to provide a clear and concise description for better understanding of its purpose and usage.
 * 
 * ## Usage
 * 
 * To use the `JA_Simple_TransactionBuildSignSubmit` action, you need to provide the required parameters `TransactionNP` and `Passphrase`. The exact usage of these parameters depends on their purpose, which is currently not described.
 * 
 * Please ensure that the parameters are of the correct type (`CodeActions$BasicParameterType`) and that they are correctly initialized before calling the action.
 * 
 * ## Example
 * 
 * ```java
 * CodeActions$BasicParameterType transactionNP = ...; // Initialize transactionNP
 * CodeActions$BasicParameterType passphrase = ...; // Initialize passphrase
 * 
 * // Call the action
 * JA_Simple_TransactionBuildSignSubmit(transactionNP, passphrase);
 * ```
 * 
 * **Note:** Replace the `...` in the example with the actual values or variables.
 * 
 * ## Error Handling
 * 
 * Please ensure to handle any exceptions that this action might throw due to incorrect parameters or other issues.
 */
public class JA_Simple_TransactionBuildSignSubmit extends UserAction<java.lang.String>
{
	/** @deprecated use TransactionNP.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TransactionNP;
	private final cardanowallet.proxies.TransactionNP TransactionNP;
	private final java.lang.String Passphrase;

	public JA_Simple_TransactionBuildSignSubmit(
		IContext context,
		IMendixObject _transactionNP,
		java.lang.String _passphrase
	)
	{
		super(context);
		this.__TransactionNP = _transactionNP;
		this.TransactionNP = _transactionNP == null ? null : cardanowallet.proxies.TransactionNP.initialize(getContext(), _transactionNP);
		this.Passphrase = _passphrase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
	    Wallet wallet = TransactionNP.getTransactionNP_Wallet();
	    Utils utils = new Utils(wallet.getCardanonetwork()
	    		.toString()
	    		.toLowerCase());
	    
		// Decrypt the mnemonic
		String mnemonic = EncryptDecryptMnemonic.decrypt(wallet.getMnemonicEncrypted(), this.Passphrase);
		
		Account senderAccount = new Account(utils.getCardanoNetwork(), mnemonic);
		mnemonic = null;
		String senderAddress = senderAccount.baseAddress();
		
		String bfProjectId = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
		BFBackendService backendService =
		        new BFBackendService(utils.getBlockfrostUrl(), bfProjectId);
        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);

		// Build the transaction output
		Tx tx = new Tx().from(senderAddress);
		
		List<IMendixObject> recipients = Core.retrieveByPath(
                getContext(),
                this.TransactionNP.getMendixObject(),
                RecipientNP.MemberNames.RecipientNP_TransactionNP.toString()
        );

        for (IMendixObject obj : recipients) {
            RecipientNP recipient = RecipientNP.initialize(getContext(), obj);
            tx.payToAddress(
                recipient.getAddress(),
                Amount.lovelace(BigInteger.valueOf(recipient.getAmountInLong()))
            );

    		List<IMendixObject> tokens = Core.retrieveByPath(
                    getContext(),
                    recipient.getMendixObject(),
                    RecipientTokenNP.MemberNames.RecipientTokenNP_RecipientNP.toString()
            );
    		
    		for (IMendixObject tokenObj : tokens) {
    			RecipientTokenNP token = RecipientTokenNP.initialize(getContext(), tokenObj);
    			Asset assetDetails = token.getRecipientTokenNP_Asset();
    			tx.payToAddress(
    				recipient.getAddress(),
    				Amount.asset(
    					assetDetails.getNameHex(), 
    					token.getAmount())
    				);
    		}
        }
		
		
		
		// Add the meta data
        String messageMetaData = TransactionNP.getMessageMetadata();
        if (messageMetaData != null && !messageMetaData.isEmpty()){
            tx.attachMetadata(MetadataUtils.createMessageMetadata(messageMetaData));
        }
        String errorResponse = "Error: \n";
        Result<String> signedTx = null;
        try {
			signedTx = quickTxBuilder
		            .compose(tx)
	                .feePayer(senderAddress)
		            .withSigner(SignerProviders.signerFrom(senderAccount))
	                .completeAndWait(Utils.LOG::debug);
			if(!signedTx.isSuccessful()) {
				Utils.LOG.error(signedTx);
				if(signedTx.getResponse().contains("MaxTxSizeUTxO")) {
					errorResponse = errorResponse + "Transaction size is big\r\n"
							+ "hint:reduce metadata, reduce number of recipients, etc\n\n";
				}
				if(signedTx.getResponse().contains("javax.crypto.BadPaddingException")) {
					errorResponse = errorResponse + " Invalid Passphrase\n\n";
				}
				throw new Exception(errorResponse);
			}
        } catch(Exception ex) {
        	throw ex;
        }
		return signedTx.getValue();
		

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Simple_TransactionBuildSignSubmit";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
