// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.util.List;
import java.util.Optional;
import com.bloxbean.cardano.client.account.Account;
import com.bloxbean.cardano.client.address.AddressProvider;
import com.bloxbean.cardano.client.api.model.Amount;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.api.model.Utxo;
import com.bloxbean.cardano.client.backend.api.BackendService;
import com.bloxbean.cardano.client.backend.api.DefaultUtxoSupplier;
import com.bloxbean.cardano.client.backend.api.TransactionService;
import com.bloxbean.cardano.client.backend.blockfrost.common.Constants;
import com.bloxbean.cardano.client.backend.blockfrost.service.BFBackendService;
import com.bloxbean.cardano.client.backend.model.TransactionContent;
import com.bloxbean.cardano.client.common.model.Network;
import com.bloxbean.cardano.client.common.model.Networks;
import com.bloxbean.cardano.client.function.helper.SignerProviders;
import com.bloxbean.cardano.client.plutus.blueprint.PlutusBlueprintUtil;
import com.bloxbean.cardano.client.plutus.blueprint.model.PlutusVersion;
import com.bloxbean.cardano.client.plutus.spec.BytesPlutusData;
import com.bloxbean.cardano.client.plutus.spec.ConstrPlutusData;
import com.bloxbean.cardano.client.plutus.spec.PlutusData;
import com.bloxbean.cardano.client.plutus.spec.PlutusScript;
import com.bloxbean.cardano.client.quicktx.QuickTxBuilder;
import com.bloxbean.cardano.client.quicktx.ScriptTx;
import com.bloxbean.cardano.client.util.JsonUtil;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import cardanowallet.EncryptDecryptMnemonic;
import cardanowallet.Utils;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_SmartContract_Unlock
 * 
 * ## Overview
 * 
 * The `JA_SmartContract_Unlock` is a Java action that is used to unlock a smart contract. This action requires several parameters to function properly.
 * 
 * ## Parameters
 * 
 * ### PlutusScriptCode
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The Plutus script code used in the smart contract. This parameter is required to unlock the smart contract.
 * 
 * ### ReceiverAddress
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The address of the receiver. This is where the unlocked funds will be sent.
 * 
 * ### CardanoNetwork
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The Cardano network where the smart contract is deployed. This could be the mainnet or a testnet.
 * 
 * ### RedeemerGuess
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The redeemer's guess. This is used to unlock the smart contract.
 * 
 * ### ContractScript
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The script of the smart contract. This is used to verify the authenticity of the contract.
 * 
 * ### ContractAmount
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The amount of ADA in the smart contract. This is the amount that will be unlocked.
 * 
 * ### SignerWallet
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The wallet of the signer. This is used to sign the transaction for unlocking the smart contract.
 * 
 * ### SignerWalletPassphrase
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** The passphrase of the signer's wallet. This is used to authenticate the signer's wallet.
 * 
 * ## Usage
 * 
 * To use this action, you need to provide all the parameters listed above. After providing the parameters, you can call this action to unlock the smart contract.
 */
public class JA_SmartContract_Unlock extends UserAction<IMendixObject>
{
	private final java.lang.String PlutusScriptCode;
	private final java.lang.String ReceiverAddress;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;
	private final java.lang.String RedeemerGuess;
	/** @deprecated use ContractScript.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ContractScript;
	private final cardanowallet.proxies.Script ContractScript;
	private final java.math.BigDecimal ContractAmount;
	/** @deprecated use SignerWallet.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __SignerWallet;
	private final cardanowallet.proxies.Wallet SignerWallet;
	private final java.lang.String SignerWalletPassphrase;

	public JA_SmartContract_Unlock(
		IContext context,
		java.lang.String _plutusScriptCode,
		java.lang.String _receiverAddress,
		java.lang.String _cardanoNetwork,
		java.lang.String _redeemerGuess,
		IMendixObject _contractScript,
		java.math.BigDecimal _contractAmount,
		IMendixObject _signerWallet,
		java.lang.String _signerWalletPassphrase
	)
	{
		super(context);
		this.PlutusScriptCode = _plutusScriptCode;
		this.ReceiverAddress = _receiverAddress;
		this.CardanoNetwork = _cardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetwork);
		this.RedeemerGuess = _redeemerGuess;
		this.__ContractScript = _contractScript;
		this.ContractScript = _contractScript == null ? null : cardanowallet.proxies.Script.initialize(getContext(), _contractScript);
		this.ContractAmount = _contractAmount;
		this.__SignerWallet = _signerWallet;
		this.SignerWallet = _signerWallet == null ? null : cardanowallet.proxies.Wallet.initialize(getContext(), _signerWallet);
		this.SignerWalletPassphrase = _signerWalletPassphrase;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		Utils utils = new Utils(this.SignerWallet.getCardanonetwork()
				.toString()
				.toLowerCase());
		selectedNetwork = utils.getCardanoNetwork();
		blockfrostProjectID = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
		backendService = new BFBackendService(utils.getBlockfrostUrl(), blockfrostProjectID);
		transactionService = backendService.getTransactionService();
		
		this.unlock();
		return this.ContractScript.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_SmartContract_Unlock";
	}

	// BEGIN EXTRA CODE
	
	public static ILogNode LOG = Utils.LOG;
	private Network selectedNetwork;
	private String blockfrostProjectID = cardanowallet.proxies.constants.Constants.getBLOCKFROST_PROJECTID();
	
	private Account signer;
	private BackendService backendService; // = new BFBackendService(blockfrostUrl, blockfrostProjectID);
	private TransactionService transactionService;
	
	private PlutusScript plutusScript; // = PlutusBlueprintUtil.getPlutusScriptFromCompiledCode(compiledCode, PlutusVersion.v3);
	private String scriptAddr; // = AddressProvider.getEntAddress(plutusScript, Networks.testnet()).toBech32();

    public String unlock() throws Exception {
    	var resultString = "";
    	try {
    		var decrypt = new EncryptDecryptMnemonic();
        	try {
    			String mnemonic = decrypt.decrypt(this.SignerWallet.getMnemonicEncrypted(), this.SignerWalletPassphrase);
        		signer = new Account(selectedNetwork, mnemonic);
    		} catch (Exception e) {
    			// TODO Auto-generated catch block
    			LOG.error("Error signing unlock transaction", e);
    			throw e;
    		}
        	
	    	plutusScript = PlutusBlueprintUtil.getPlutusScriptFromCompiledCode(this.ContractScript.getPlutusScriptCode(), PlutusVersion.v3);
	    	LOG.debug("plutus:::" + plutusScript);
	    	scriptAddr = AddressProvider.getEntAddress(plutusScript, selectedNetwork).toBech32();
	    	LOG.debug("scriptAddr:::" + scriptAddr);
	    	LOG.debug("Script Address from ContractStript:::"+this.ContractScript.getScriptAddress());
	    	
	        Utxo scriptUtxo = null;
	        Optional<Utxo> UtxoO = checkIfUtxoAvailable2(this.ContractScript.getLockTransactionHash(), scriptAddr); //.orElseThrow();
	        if(UtxoO.isPresent()) {
	            scriptUtxo = UtxoO.get();
	            LOG.debug("Utxo is present:::" + scriptUtxo.toString());
	        } else {
	            LOG.debug("Utxo is not present::::NULL"); //checkIfUtxoAvailable2(contractTxHash, scrtiptAddr).isPresent(); //ScriptUtxoFinders.findFirstByInlineDatum(utxoSupplier, scrtiptAddr, datum).orElseThrow();
	        }
	        PlutusData redeemer = ConstrPlutusData.of(0, BytesPlutusData.of(this.RedeemerGuess));
	        ScriptTx scriptTx = new ScriptTx()
	                .collectFrom(scriptUtxo, redeemer)
	                .payToAddress(signer.baseAddress(), Amount.ada(this.ContractAmount.doubleValue()))
	                .attachSpendingValidator(plutusScript);
	
	        QuickTxBuilder quickTxBuilder = new QuickTxBuilder(backendService);
	        Result<String> result = quickTxBuilder.compose(scriptTx)
	                .feePayer(signer.baseAddress())
	                .withSigner(SignerProviders.signerFrom(signer))
	                .withRequiredSigners(signer.getBaseAddress())
	                .completeAndWait(LOG::debug);

	        
			LOG.debug(result);  
			LOG.debug("=====RESULT======");
			LOG.debug(result);
			if(!result.isSuccessful()) {
				throw new Exception("Error: Failed Smart contract redemption:::"+ result.getResponse());
			}
			this.ContractScript.setUnLockTransactionHash(result.getValue());
			LOG.debug("=====SMART CONTRACT REDEMPTION DONE======");
			resultString = result.getValue();
		} catch (Exception e) {
			 LOG.error(e);
			 throw e;
		}
    	return resultString;
    }
    
	public void waitForTransaction(Result<String> result) {
		try {
			if (result.isSuccessful()) { //Wait for transaction to be mined
				int count = 0;
				while (count < 60) {
					Result<TransactionContent> txnResult = transactionService.getTransaction(result.getValue());
					if (txnResult.isSuccessful()) {
						LOG.debug(JsonUtil.getPrettyJson(txnResult.getValue()));
						break;
					} else {
						LOG.debug("Waiting for transaction to be mined ....");
					}
					count++;
					Thread.sleep(2000);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	private Optional<Utxo> getAvailableUtxo(String txHash, String address) {
		Optional<Utxo> utxo = Optional.empty();
        int count = 0;
        while (utxo.isEmpty()) {
            if (count++ >= 20)
                break;
            List<Utxo> utxos = new DefaultUtxoSupplier(backendService.getUtxoService()).getAll(address);
            utxo = utxos.stream().filter(u -> u.getTxHash().equals(txHash))
                    .findFirst();
            if(utxo.isPresent()) {
                LOG.debug("Output got is::::"+String.valueOf(count) +" :::::::: " + utxo.get().toString());
            } else {
            	LOG.debug("Try to get new output... txhash: " + txHash);
            }

            try {
                Thread.sleep(1000);
            } catch (Exception e) {}
        }
        return utxo;
    }
	
	protected Optional<Utxo> checkIfUtxoAvailable2(String txHash, String address) {
        Optional<Utxo> utxo = Optional.empty();
        int count = 0;
        while (utxo.isEmpty()) {
            if (count++ >= 20)
                break;
            List<Utxo> utxos = new DefaultUtxoSupplier(backendService.getUtxoService()).getAll(address);
            utxo = utxos.stream().filter(u -> u.getTxHash().equals(txHash))
                    .findFirst();
            LOG.debug("Try to get new output... txhash: " + txHash);
            try {
                Thread.sleep(1000);
            } catch (Exception e) {}
        }
        return utxo;
    }
	
	// END EXTRA CODE
}
