// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.nio.charset.StandardCharsets;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_StringToHex Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_StringToHex` is a Java action in Mendix that converts a given string to hexadecimal.
 * 
 * ## Parameters
 * 
 * The `JA_StringToHex` action has the following parameter:
 * 
 * ### StringToHex
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to specify the string that needs to be converted to hexadecimal. The specific details of the string are not provided in the description.
 * 
 * ## Usage
 * 
 * To use the `JA_StringToHex` action, you need to pass the `StringToHex` parameter to the action. The `StringToHex` parameter should be a string that you want to convert to hexadecimal.
 * 
 * ## Example
 * 
 * Here is an example of how to use the `JA_StringToHex` action:
 * 
 * ```java
 * String inputString = "Hello, World!";
 * CodeActions.JA_StringToHex(inputString);
 * ```
 * 
 * In this example, the `JA_StringToHex` action will convert the string "Hello, World!" to hexadecimal.
 * 
 * ## Output
 * 
 * The `JA_StringToHex` action returns a string in hexadecimal format. The returned value is the hexadecimal representation of the input string passed to the `StringToHex` parameter.
 * 
 * ## Error Handling
 * 
 * If the `JA_StringToHex` action encounters an error during execution, it will throw an exception. You should handle these exceptions in your code to prevent your application from crashing.
 */
public class JA_StringToHex extends UserAction<java.lang.String>
{
	private final java.lang.String StringToHex;

	public JA_StringToHex(
		IContext context,
		java.lang.String _stringToHex
	)
	{
		super(context);
		this.StringToHex = _stringToHex;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder hexString = new StringBuilder();
	    for (char ch : StringToHex.toCharArray()) {
	        hexString.append(String.format("%02x", (int) ch));
	    }
	    return hexString.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_StringToHex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
