// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import java.util.ArrayList;
import com.bloxbean.cardano.client.api.model.Result;
import com.bloxbean.cardano.client.common.cbor.CborSerializationUtil;
import com.bloxbean.cardano.client.transaction.spec.Transaction;
import com.bloxbean.cardano.client.transaction.spec.TransactionWitnessSet;
import com.bloxbean.cardano.client.util.HexUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import cardanowallet.Utils;
import co.nstant.in.cbor.model.DataItem;
import co.nstant.in.cbor.model.Map;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # JA_Transaction_Submit Java Action Documentation
 * 
 * ## Overview
 * 
 * The `JA_Transaction_Submit` Java action is designed to handle the submission of transactions within a specific network. 
 * 
 * ## Parameters
 * 
 * The `JA_Transaction_Submit` Java action accepts three parameters:
 * 
 * ### TransactionCBOR
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to pass the transaction in CBOR (Concise Binary Object Representation) format. CBOR is a binary data serialization format similar to JSON. More details about the transaction structure and format should be provided by the specific implementation or usage context.
 * 
 * ### WitnessCBOR
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to pass the witness data in CBOR format. In the context of blockchain transactions, a witness refers to the proof of authorization required to validate a transaction. More details about the witness structure and format should be provided by the specific implementation or usage context.
 * 
 * ### CardanoNetwork
 * 
 * - **Type:** `CodeActions$BasicParameterType`
 * - **Description:** This parameter is used to specify the Cardano network where the transaction will be submitted. Cardano has multiple networks (like the mainnet and various testnets), and this parameter allows specifying which one to use.
 * 
 * ## Usage
 * 
 * To use the `JA_Transaction_Submit` action, you need to provide the necessary parameters as per your transaction requirements. The action will process the transaction and witness data and submit it to the specified Cardano network. Please ensure that the CBOR data is correctly formatted and that the specified network is available and accessible.
 */
public class JA_Transaction_Submit extends UserAction<java.lang.String>
{
	private final java.lang.String TransactionCBOR;
	private final java.lang.String WitnessCBOR;
	private final cardanowallet.proxies.Enum_CardanoNetwork CardanoNetwork;

	public JA_Transaction_Submit(
		IContext context,
		java.lang.String _transactionCBOR,
		java.lang.String _witnessCBOR,
		java.lang.String _cardanoNetwork
	)
	{
		super(context);
		this.TransactionCBOR = _transactionCBOR;
		this.WitnessCBOR = _witnessCBOR;
		this.CardanoNetwork = _cardanoNetwork == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_cardanoNetwork);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		var utils = new Utils(this.CardanoNetwork.getCaption());
	    // 1. Deserialize original transaction
        Transaction transaction = Transaction.deserialize(HexUtil.decodeHexString(TransactionCBOR));

        // 2. Deserialize witness set from CIP-30
        DataItem witnessDI = CborSerializationUtil.deserialize(HexUtil.decodeHexString(WitnessCBOR));
        //TransactionWitnessSet walletWitnessSet = TransactionWitnessSet.deserialize((Map) witnessDI);
        TransactionWitnessSet walletWitnessSet = TransactionWitnessSet.deserialize((Map) witnessDI);

        // 3. Merge wallet witness into original transaction
        if (transaction.getWitnessSet() == null) {
            transaction.setWitnessSet(new TransactionWitnessSet());
        }

        if (transaction.getWitnessSet().getVkeyWitnesses() == null)
            transaction.getWitnessSet().setVkeyWitnesses(new ArrayList<>());

        transaction.getWitnessSet().getVkeyWitnesses().addAll(walletWitnessSet.getVkeyWitnesses());

        // 4. Submit transaction
        Result<String> result = utils.backendService.getTransactionService().submitTransaction(transaction.serialize());

        if (result.isSuccessful()) {
            return result.getValue(); // Transaction hash
        } else {
            throw new RuntimeException("Transaction submission failed: " + result.getResponse());
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Transaction_Submit";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
