// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.bloxbean.cardano.client.cip.cip30.CIP30DataSigner;
import com.bloxbean.cardano.client.cip.cip30.DataSignature;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_VerifyCardanoPayloadSignature extends UserAction<java.lang.Void>
{
	/** @deprecated use CardanoSignature.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CardanoSignature;
	private final cardanowallet.proxies.CardanoSignature CardanoSignature;

	public JA_VerifyCardanoPayloadSignature(
		IContext context,
		IMendixObject _cardanoSignature
	)
	{
		super(context);
		this.__CardanoSignature = _cardanoSignature;
		this.CardanoSignature = _cardanoSignature == null ? null : cardanowallet.proxies.CardanoSignature.initialize(getContext(), _cardanoSignature);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode log = Core.getLogger("CardanoWallet");

		if (CardanoSignature == null) {
			throw new IllegalArgumentException("CardanoSignature is required");
		}

		String signatureHex = CardanoSignature.getSignatureHex();
		String keyHex = CardanoSignature.getKeyHex();
		String expectedPayload = CardanoSignature.getPayload();

		if (signatureHex == null || signatureHex.trim().isEmpty()) {
			throw new IllegalArgumentException("SignatureHex is required");
		}
		if (keyHex == null || keyHex.trim().isEmpty()) {
			throw new IllegalArgumentException("KeyHex is required");
		}
		if (expectedPayload == null || expectedPayload.trim().isEmpty()) {
			throw new IllegalArgumentException("Payload is required for verification");
		}

		DataSignature dataSignature = new DataSignature(signatureHex, keyHex);

		// Verify cryptographic signature
		boolean signatureValid = CIP30DataSigner.INSTANCE.verify(dataSignature);

		// Extract and compare embedded payload against expected
		byte[] embeddedPayloadBytes = dataSignature.coseSign1().payload();
		String embeddedPayload = new String(embeddedPayloadBytes, java.nio.charset.StandardCharsets.UTF_8);
		boolean payloadMatches = expectedPayload.equals(embeddedPayload);

		if (!payloadMatches) {
			log.warn("Payload mismatch: embedded payload does not match expected payload");
		}

		boolean isValid = signatureValid && payloadMatches;

		// Extract signer address from COSE_Sign1 protected headers
		CardanoSignature.setSignerAddress(new com.bloxbean.cardano.client.address.Address(dataSignature.address()).getAddress());
		CardanoSignature.setIsVerified(isValid);

		log.info("Cardano payload signature verification result: " + isValid
			+ " (signatureValid=" + signatureValid + ", payloadMatches=" + payloadMatches + ")");

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_VerifyCardanoPayloadSignature";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
