// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cardanowallet.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * # Java Action: ParseDateTimeToCardanoSlot
 * 
 * ## Introduction
 * 
 * The `ParseDateTimeToCardanoSlot` Java action is used to convert a given date and time to a Cardano slot.
 * 
 * ## Parameters
 * 
 * The `ParseDateTimeToCardanoSlot` action takes the following parameters:
 * 
 * ### Network
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter is used to specify the Cardano network for which the date and time is to be converted. The network parameter is crucial as different Cardano networks may have different slot durations and epoch lengths.
 * 
 * ### InputDate
 * 
 * - **Type**: `CodeActions$BasicParameterType`
 * - **Description**: This parameter is used to provide the date and time that is to be converted to a Cardano slot. The date and time should be provided in a format that is compatible with the Java `Date` class.
 * 
 * ## Usage
 * 
 * To use the `ParseDateTimeToCardanoSlot` action, you need to provide the `Network` and `InputDate` parameters. The `Network` parameter should be a string representing the Cardano network, and the `InputDate` should be a `Date` object representing the date and time to be converted.
 * 
 * ## Example
 * 
 * Here is an example of how to use the `ParseDateTimeToCardanoSlot` action:
 * 
 * ```java
 * Date inputDate = new Date();
 * String network = "mainnet";
 * ParseDateTimeToCardanoSlot(network, inputDate);
 * ```
 * 
 * In this example, the current date and time is converted to a Cardano slot for the mainnet network.
 */
public class ParseDateTimeToCardanoSlot extends UserAction<java.lang.Long>
{
	private final cardanowallet.proxies.Enum_CardanoNetwork Network;
	private final java.util.Date InputDate;

	public ParseDateTimeToCardanoSlot(
		IContext context,
		java.lang.String _network,
		java.util.Date _inputDate
	)
	{
		super(context);
		this.Network = _network == null ? null : cardanowallet.proxies.Enum_CardanoNetwork.valueOf(_network);
		this.InputDate = _inputDate;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (InputDate == null) {
            throw new IllegalArgumentException("Date/Time input cannot be null");
        }

        // Convert java.util.Date to Unix Time (seconds)
        long inputUnixTime = InputDate.getTime() / 1000;

        // Shelley Hard Fork Timestamp (Unix time in seconds)
        long shelleyHardForkTime;
        
        switch (this.Network) {
            case Mainnet:
                shelleyHardForkTime = 1654041600L;
                break;
            case Preview:
                shelleyHardForkTime = 1666656000L;
                break;
            case Preprod:
                shelleyHardForkTime = 1654041600L;
                break;
            default:
                throw new IllegalArgumentException("Unsupported network: " + Network);
        }

        // Ensure the given date is after Shelley hard fork
        if (inputUnixTime < shelleyHardForkTime) {
            throw new IllegalArgumentException("Date must be after Shelley hard fork (July 29, 2020)");
        }

        // Calculate slot number (1 second per slot)
        return inputUnixTime - shelleyHardForkTime;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ParseDateTimeToCardanoSlot";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
